### PR TITLE
Set allow_agent=False for the client connection

### PR DESCRIPTION
**Pull request by remoteur**
Authentication on Cisco IOS fails when using the ssh agent.

### CODE REVIEW

**Comment by ktbyers** [comment]
Marius,

Can you show me an example session and maybe the exception? Cisco IOS is
working correctly for me.


Regards,

Kirk

On Wed, Feb 18, 2015 at 4:20 PM, Marius Cornea <notifications@github.com>
wrote:

> Authentication on Cisco IOS fails when using the ssh agent.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ktbyers/netmiko/pull/41
> Commit Summary
>
>    - Set allow_agent=False for the client connection
>
> File Changes
>
>    - *M* netmiko/base_connection.py
>    <https://github.com/ktbyers/netmiko/pull/41/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/ktbyers/netmiko/pull/41.patch
>    - https://github.com/ktbyers/netmiko/pull/41.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/pull/41>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by ktbyers** [comment]
Also what version of Paramiko are you using?

Regards,

Kirk

On Wed, Feb 18, 2015 at 5:20 PM, Kirk Byers <ktbyers@twb-tech.com> wrote:

> Marius,
>
> Can you show me an example session and maybe the exception? Cisco IOS is
> working correctly for me.
>
>
> Regards,
>
> Kirk
>
> On Wed, Feb 18, 2015 at 4:20 PM, Marius Cornea <notifications@github.com>
> wrote:
>
>> Authentication on Cisco IOS fails when using the ssh agent.
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/ktbyers/netmiko/pull/41
>> Commit Summary
>>
>>    - Set allow_agent=False for the client connection
>>
>> File Changes
>>
>>    - *M* netmiko/base_connection.py
>>    <https://github.com/ktbyers/netmiko/pull/41/files#diff-0> (2)
>>
>> Patch Links:
>>
>>    - https://github.com/ktbyers/netmiko/pull/41.patch
>>    - https://github.com/ktbyers/netmiko/pull/41.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ktbyers/netmiko/pull/41>.
>>
>
>
>
> --
> Kirk Byers
> CCIE #6243 emeritus
> ktbyers@twb-tech.com
> *http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
> (415) 264-6270
> Simplify your network management through automation
>
>
>


-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by remoteur** [comment]
Hi Kirk,

I'm running Paramiko version 1.10.1, on Ubuntu 14.04. Here's the debug of a failed session:
http://pastebin.com/idvcjJ28

I see other people have hit this when using Paramiko with Cisco devices:
http://stackoverflow.com/questions/14274566/paramiko-protocol-error-expected-packet-ssh-msg-userauth-request-got-ssh-msg-s
http://stackoverflow.com/questions/16751119/ssh-login-with-python-paramiko-module-into-cisco-device-fails

Thank you,
Marius

**Comment by ktbyers** [comment]
Okay, lete look at it


Kirk

On Wednesday, February 18, 2015, Marius Cornea <notifications@github.com>
wrote:

> Hi Kirk,
>
> I'm running Paramiko version 1.10.1, on Ubuntu 14.04. Here's the debug of
> a failed session:
> http://pastebin.com/idvcjJ28
>
> I see other people have hit this when using Paramiko with Cisco devices:
>
> http://stackoverflow.com/questions/14274566/paramiko-protocol-error-expected-packet-ssh-msg-userauth-request-got-ssh-msg-s
>
> http://stackoverflow.com/questions/16751119/ssh-login-with-python-paramiko-module-into-cisco-device-fails
>
> Thank you,
> Marius
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/pull/41#issuecomment-75008971>.
>


-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by remoteur** [comment]
Hi Kirk,

Just a quick update - I also tested it on Fedora 21, paramiko version 1.15.1 and it's working fine.

**Comment by ktbyers** [comment]
allow_agent defaults to True and will try to use the ssh-agent on the local box (which generally won't work with networking devices since it is PKI mechanism).

**Pull request merged**
