### PR TITLE
Adding new vendor (Eltex) and new ansi code (ESC[K) for stripping

### PR DESCRIPTION
**Pull request by ilique**
Hello, Kirk.

I suggest this vendor as it is required by my current project, and i hope to use your library as an important part of it (great work, by the way, many thanks).

This ansi escape code i saw only in the output of Eltex, so maybe it's irrelevant to other vendors.

Regards.

### CODE REVIEW

**Comment by ktbyers** [comment]
@ilique I haven't forgotten about this. Just tied up right now with moving my office.

**Comment by ilique** [comment]
Got it, thanks. Take your time.

23.06.2016, 20:19, "Kirk Byers" <notifications@github.com>:
>  @ilique I haven't forgotten about this. Just tied up right now with moving my office.
>
>  —
>  You are receiving this because you were mentioned.
>  Reply to this email directly, view it on GitHub, or mute the thread.




23.06.2016, 20:19, "Kirk Byers" <notifications@github.com>:
> @ilique I haven't forgotten about this. Just tied up right now with moving my office.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
С уважением,
 Берестенко Илья
 +7 (911) 966-48-38 (СПб)

**Comment by ktbyers** [comment]
@ilique Sorry for big delay on this. Any possibility you can resubmit this Pull Request to the dev_1_1 branch?

**Comment by ilique** [comment]
And now's my turn to feel sorry for the delay ) Must have missed the notification about the comment, sorry. 

Is it still needs to be requested on dev_1_1 ?

**Comment by ktbyers** [comment]
@ilique You can probably leave it here. I can merge it into the dev_1_1 branch directly. If I have questions or concerns I can follow up with you.

**Comment by ilique** [comment]
Ok, thanks.

**Comment by ktbyers** [comment]
@ilique Okay, this was merged into the dev_1_2 branch...sorry for all the delay.

**Pull request closed without merging**
