### PR TITLE
Add SROS enable mode

### PR DESCRIPTION
**Pull request by ktbyers**
See previous PR https://github.com/ktbyers/netmiko/pull/664

### CODE REVIEW

**Comment by ktbyers** [comment]
@ddfrathb I updated your fix per our discussion can you test the `enable` and the `check_enable_mode` methods?

Note, `check_enable_mode` will cause a failed login (if you are not in enable mode).

**Comment by ddfrathb** [comment]
Yes thank you. I was busy with work this week - will check on Sunday. Very much appreciated Kirk!

**Comment by ktbyers** [comment]
@ddfrathb Did you get a chance to test this?

**Comment by ddfrathb** [comment]
Yes I tested it this afternoon - sorry it took so long to get back to you. The only other issue I had was, as mentioned, the SSH_MAPPER_BASE dict will need to be changed as well, as updated SROS is now Nokia, and so the old cmd string does not work for autodetect. 
`nm_auto.SSH_MAPPER_BASE['alcatel_sros']['cmd'] = "show version | match SR"` was my workaround - instead of looking for `ALCATEL`, as it is now `Nokia`, but in support of backwards compatibility/ease of application I just look for `SR`

**Comment by ktbyers** [comment]
@ddfrathb Can you show me the 'show version' output from a rebranded Nokia device?

I am going to close this PR as it should be done now.

**Comment by ddfrathb** [comment]
see https://github.com/ktbyers/netmiko/pull/664 for the comments:

New "show ver" prompt:

```*A:HOSTNAME# show version
TiMOS-B-14.0.R4 both/i386 Nokia 7750 SR Copyright (c) 2000-2016 Nokia.
All rights reserved. All use subject to applicable license agreements.
Built on Thu Jul 28 17:26:53 PDT 2016 by builder in /rel14.0/b1/R4/panos/main
```

Old "show ver" prompt:

```A:HOSTNAME# show version
TiMOS-C-13.0.R10 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2016 Alcatel-Lucent.
All rights reserved. All use subject to applicable license agreements.
Built on Wed Jun 22 20:03:59 PDT 2016 by builder in /rel13.0/b1/R10/panos/main```

**Comment by ktbyers** [comment]
@ddfrathb I assume looking for `TiMOS` will work? 

`SR` is too short i.e. too many false positives.

**Comment by ktbyers** [comment]
Does this work?

```
58     'alcatel_sros': {
 59         "cmd": "show version | match TiMOS",
 60         "search_patterns": ["TiMOS"],
 61         "priority": 99,
 62         "dispatch": "_autodetect_std",
 63     },
```

**Comment by ktbyers** [comment]
FYI, I just submitted a commit on the above change.

**Comment by ddfrathb** [comment]
Yes that will work. SR is too short but I used it temporarily as I needed it for a demo :)

**Comment by ddfrathb** [comment]
Hi Kirk,

I just updated my netmiko package and it broke enable on my SROS boxes, saw this was deleted. Not sure what happened but curious if we can make sure it works/returns in another release.

**Comment by terroirman** [comment]
Hi @ktbyers ,

I know its been a while, but this is still not included in the current release. Documentation also states that enable() is not supported for SROS.

Am I missing something ? Has it been deactivated for some reason ?

**Comment by ktbyers** [comment]
Yes, we revamped the nokia_sros driver and removed that `enable()` method at some point in that process.

Adding @hellt as he is much more familiar on the SR-OS behaviors than I am.

**Comment by hellt** [comment]
Hi @terroirman 
SR OS does not have a notion of _enable_ mode, therefore we disabled it in the netmiko driver.

You needed it in some way?

**Comment by terroirman** [comment]
Thanks @hellt and @ktbyers for your quick responses.

I'm using SROS 15 mainly, and its definitely there. Has it been dropped in newer SROS version ? Does this "enable-admin" only applies to this platform ? 

In the meantime, I "borrowed" some of the previous code in the old  netmiko/alcatel/alcatel_sros_ssh.py  file and it seems to work as expected. It would be best if it was supported natively though.

example:
```
B:hostname# configure port 1/1/20
                               ^
MINOR: CLI Command not allowed for this user.
B:hostname# show version
TiMOS-C-15.0.R13 cpm/hops64 Nokia 7750 SR Copyright (c) 2000-2019 Nokia.
All rights reserved. All use subject to applicable license agreements.
Built on Wed Mar 20 12:23:44 PDT 2019 by builder in /builds/c/150B/R13/panos/main
B:hostname# enable-admin
Password:
B:hostname# configure port 1/2/20
B:hostname>config>port# info
----------------------------------------------
        shutdown
        description "SPARE"
        ethernet
            mode access
            encap-type dot1q
            mtu 9212
            speed 100
            no autonegotiate
        exit
----------------------------------------------
B:hostname>config>port# exit


```

**Comment by hellt** [comment]
@terroirman thanks. It seems that has been overlooked in the driver design =(
I think I need to add a patch for that mode.
Can you please send me a link to the commit with the old functionality that has this mode in place?


PS. In the meantime I guess you can enable the "admin" mode by sending the respectful command if its needed right now. Otherwise lets see how quickly I can patch it

**Comment by ktbyers** [comment]
Previous solution is here:

https://github.com/ktbyers/netmiko/blob/v2.4.2/netmiko/alcatel/alcatel_sros_ssh.py#L29-L58

**Comment by terroirman** [comment]
Yes, those are the lines I implemented manually in my script as a workaround (and it seems to work so far).

**Comment by hellt** [comment]
@terroirman I have created a PR that adds this functionality
Until its merged you can try it out from this branch https://github.com/hellt/netmiko/tree/sros-enable-mode

**Pull request closed without merging**
