### PR TITLE
Add Calix B6 Device Support

### PR DESCRIPTION
**Pull request by rptetzloff**
(netmiko) C:\Users\rtetzloff\Python Projects\netmiko\tests>py.test -v test_netmiko_show.py --test_device calix_b6
============================= test session starts =============================
platform win32 -- Python 3.6.2, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- c:\users\rtetzloff\netmiko\scripts\python.exe
cachedir: ..\.cache
rootdir: C:\Users\rtetzloff\Python Projects\netmiko, inifile:
collected 12 items 

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_expect PASSED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED

========================= 12 passed in 37.99 seconds ==========================

(netmiko) C:\Users\rtetzloff\Python Projects\netmiko\tests>py.test -v test_netmiko_config.py --test_device calix_b6
============================= test session starts =============================
platform win32 -- Python 3.6.2, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- c:\users\rtetzloff\netmiko\scripts\python.exe
cachedir: ..\.cache
rootdir: C:\Users\rtetzloff\Python Projects\netmiko, inifile:
collected 7 items 

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode PASSED
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_command_set PASSED
test_netmiko_config.py::test_commands_from_file PASSED
test_netmiko_config.py::test_disconnect PASSED

========================== 7 passed in 18.48 seconds ==========================

### CODE REVIEW

**Comment by rptetzloff** [comment]
Fixed line break issues

**Comment by ktbyers** [comment]
@rptetzloff Do we need both of these commands `exit` and `end` here:

```
def exit_config_mode(self, exit_config='exit\r\r\nend', pattern=''):
```

If so, why is `\n` sufficient or did you need the `\r\r\n`? If `\n` won't work and you need `\r\n`, why the extra `\r`? Or worded another way, what does Calix B6 view as a valid enter (usually would be one of `\n`, `\r\n`, or `\r`? I ask this as in Netmiko 1.5 I am going to abstract the `enter` and I need to know what is required here for Calix B6.

**Comment by rptetzloff** [comment]
@ktbyers 

Thanks! Nested config mode on Calix B6 devices is inconsistent in exiting with 'end':

```
HOSTNAME(config)#end
HOSTNAME#

HOSTNAME(config)#int dsl 48
HOSTNAME(config-if-dsl)#end
HOSTNAME#

HOSTNAME(config)#int dsl 48
HOSTNAME(config-if-dsl)#service 3
HOSTNAME(config-if-dsl-svc)#end
% Unrecognized command
HOSTNAME(config-if-dsl-svc)#exit
HOSTNAME(config-if-dsl)#end
HOSTNAME#
```

'exit' works at each level to get to previous level, including to exit config mode at top level. 'exit\nend' works, but produces error in verbose output if trying to end after already exited from config mode. Perhaps there would be a better way to deal with this, such as looping and check_config_mode.

I'll do a new pull request and mess around with alternate options.

As for \r\r\n, it looks like just putting \n works. I grabbed verbose output, which showed up as \r\r\n, so I just put that in. \n is fine.

**Comment by ktbyers** [comment]
@rptetzloff Thanks for response.

I made an update to newline behavior here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/calix/calix_b6_ssh.py#L89

I think this should work given what you described but let me know if you can test it.



On the `exit` + `end` solution (we could probably just keep calling `exit` until we are out of config mode. I would get worried that we have situations where more than a single `exit` is required.

**Comment by rptetzloff** [comment]
Tested, and looks good!

**Comment by ktbyers** [comment]
Great thanks @rptetzloff!

**Pull request merged**
