### PR TITLE
Extended Ciena support

### PR DESCRIPTION
**Pull request by georgesnow**
Added more functionality for Ciena

### CODE REVIEW

**Comment by ktbyers** [comment]
Linters are failing on the CI-CD.

**Comment by georgesnow** [comment]
Hmm I will go back and look. I had some issues merging the most recent changes on the main fork. So I broke something I didn’t catch.

**Comment by georgesnow** [comment]
i might need to close this pull request. After pulling the upstream changes in it caused issues with the configuration save function.   I had run the scp and base tests before after they passed, but i missed the save and config tests. I am getting KeyError:


    def test_save_base(net_connect, commands, expected_responses):
        """
        Test save config with no options.
        """
>       save_verify = expected_responses["save_config"]
E       KeyError: 'save_config'

test_netmiko_save.py:10: KeyError

**Comment by ktbyers** [comment]
That sounds like it is probably just a testing issue by that I mean you need to define the following two items into responses.yml:

```
responses.yml:  save_config: 'OK'
responses.yml:  save_config_response: ''
```

`save_config` is what the Ciena device outputs when you type `config save`

`save_config_response` would just be a null-string for the Ciena device (this is an interactive response like `Y` if you needed to confirm in some way you wanted to do this).

**Comment by georgesnow** [comment]
so i fixed the other errors, but its still complaining about the tests.py file. i tried removing it and re-adding, but its still complaining about it being reformatted...  🤷‍♂️

**Comment by georgesnow** [comment]
ok, so i it seems i am still getting some py.tests errors, which i though i had resolved. so i am going to have to figure those out.

rootdir: /usr/local/lib/python3.6/dist-packages/netmiko/tests
collected 12 items

test_netmiko_scp.py::test_scp_put PASSED                                         [  8%]
test_netmiko_scp.py::test_remote_space_available PASSED                          [ 16%]
test_netmiko_scp.py::test_local_space_available PASSED                           [ 25%]
test_netmiko_scp.py::test_verify_space_available_put PASSED                      [ 33%]
test_netmiko_scp.py::test_remote_file_size PASSED                                [ 41%]
test_netmiko_scp.py::test_md5_methods PASSED                                     [ 50%]
test_netmiko_scp.py::test_disconnect PASSED                                      [ 58%]
test_netmiko_scp.py::test_verify_space_available_get PASSED                      [ 66%]
test_netmiko_scp.py::test_scp_get PASSED                                         [ 75%]
test_netmiko_scp.py::test_md5_methods_get PASSED                                 [ 83%]
test_netmiko_scp.py::test_disconnect_get PASSED                                  [ 91%]
test_netmiko_scp.py::test_file_transfer PASSED                                   [100%]

----


platform linux -- Python 3.6.8, pytest-5.1.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3
rootdir: /usr/local/lib/python3.6/dist-packages/netmiko/tests
collected 14 items

test_netmiko_show.py::test_disable_paging PASSED                                 [  7%]
test_netmiko_show.py::test_ssh_connect PASSED                                    [ 14%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                 [ 21%]
test_netmiko_show.py::test_send_command_timing PASSED                            [ 28%]
test_netmiko_show.py::test_send_command PASSED                                   [ 35%]
test_netmiko_show.py::test_send_command_textfsm FAILED                           [ 42%]
test_netmiko_show.py::test_send_command_genie FAILED                             [ 50%]
test_netmiko_show.py::test_base_prompt PASSED                                    [ 57%]
test_netmiko_show.py::test_strip_prompt PASSED                                   [ 64%]
test_netmiko_show.py::test_strip_command PASSED                                  [ 71%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                            [ 78%]
test_netmiko_show.py::test_clear_buffer PASSED                                   [ 85%]
test_netmiko_show.py::test_enable_mode PASSED                                    [ 92%]
test_netmiko_show.py::test_disconnect PASSED                                     [100%]


----



platform linux -- Python 3.6.8, pytest-5.1.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3
rootdir: /usr/local/lib/python3.6/dist-packages/netmiko/tests
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                  [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                  [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                  [ 42%]
test_netmiko_config.py::test_exit_config_mode FAILED                             [ 57%]
test_netmiko_config.py::test_command_set FAILED                                  [ 71%]
test_netmiko_config.py::test_commands_from_file FAILED                           [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                   [100%]

**Comment by ktbyers** [comment]
I wouldn't worry about these two errors--they are fine:

```
test_netmiko_show.py::test_send_command_textfsm FAILED [ 42%]
test_netmiko_show.py::test_send_command_genie FAILED [ 50%]
```

These two errors, on the other hand/probably need looked into and fixed:

```
test_netmiko_config.py::test_exit_config_mode FAILED [ 57%]
test_netmiko_config.py::test_command_set FAILED [ 71%]
test_netmiko_config.py::test_commands_from_file FAILED [ 85%]
```


Regards, Kirk

**Comment by georgesnow** [comment]
I am going to taking another look at these next week. I have decent idea why they are failing.

**Comment by ktbyers** [comment]
Using PR https://github.com/ktbyers/netmiko/pull/1384 for Ciena support so closing as duplicate.

**Pull request closed without merging**
