### PR TITLE
Nokia sros telnet

### PR DESCRIPTION
**Pull request by kielpi**
Telnet support for Nokia SR OS

### CODE REVIEW

**Comment by kielpi** [comment]
Hi any chance on this to be incorporated ?

**Comment by ktbyers** [comment]
Yeah, I just haven't got to it. Probably won't be an issue getting it merged.

**Comment by kielpi** [comment]
thank in advance

**Comment by pszulczewski** [comment]
Dear Kirk,

Just a friendly reminder. ;-)

/cc @hellt

**Comment by ktbyers** [comment]
Can someone run and post the Netmiko test results for this (for both MD-CLI and Classical CLI).

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by kielpi** [comment]
Here you are:
`./test_sros.sh
Starting tests...good luck: (SR-OS CLI)
SR-OS CLI
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 22 items                                                                                                                                                                          

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_terminal_width PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_timing_no_cmd_verify PASSED
test_netmiko_show.py::test_send_command PASSED
test_netmiko_show.py::test_send_command_no_cmd_verify PASSED
test_netmiko_show.py::test_cmd_verify_decorator PASSED
test_netmiko_show.py::test_send_command_global_cmd_verify PASSED
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED
test_netmiko_show.py::test_send_command_textfsm SKIPPED (TextFSM/ntc-templates not supported on this platform)
test_netmiko_show.py::test_send_command_ttp SKIPPED (TTP template not existing for this platform)
test_netmiko_show.py::test_send_command_genie SKIPPED (Genie not supported on this platform)
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED
test_netmiko_show.py::test_disconnect_no_enable PASSED

================================================================================== short test summary info ==================================================================================
SKIPPED [1] test_netmiko_show.py:156: Skipped
SKIPPED [1] test_netmiko_show.py:184: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] test_netmiko_show.py:206: TTP template not existing for this platform
SKIPPED [1] test_netmiko_show.py:243: Genie not supported on this platform
============================================================================== 18 passed, 4 skipped in 45.04s ===============================================================================
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 9 items                                                                                                                                                                           

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode SKIPPED (Platform doesn't support config mode.)
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_config_set PASSED
test_netmiko_config.py::test_config_set_longcommand PASSED
test_netmiko_config.py::test_config_hostname PASSED
test_netmiko_config.py::test_config_from_file PASSED
test_netmiko_config.py::test_disconnect PASSED

================================================================================== short test summary info ==================================================================================
SKIPPED [1] test_netmiko_config.py:35: Platform doesn't support config mode.
=============================================================================== 8 passed, 1 skipped in 18.08s ===============================================================================
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 12 items                                                                                                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods SKIPPED (MD5 not supported on this platform)
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get SKIPPED (MD5 not supported on this platform)
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

================================================================================== short test summary info ==================================================================================
SKIPPED [1] test_netmiko_scp.py:46: MD5 not supported on this platform
SKIPPED [1] test_netmiko_scp.py:85: MD5 not supported on this platform
============================================================================== 10 passed, 2 skipped in 51.24s ===============================================================================
SR-OS MD
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 22 items                                                                                                                                                                          

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_terminal_width PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_timing_no_cmd_verify PASSED
test_netmiko_show.py::test_send_command PASSED
test_netmiko_show.py::test_send_command_no_cmd_verify PASSED
test_netmiko_show.py::test_cmd_verify_decorator PASSED
test_netmiko_show.py::test_send_command_global_cmd_verify PASSED
test_netmiko_show.py::test_complete_on_space_disabled PASSED
test_netmiko_show.py::test_send_command_textfsm SKIPPED (TextFSM/ntc-templates not supported on this platform)
test_netmiko_show.py::test_send_command_ttp SKIPPED (TTP template not existing for this platform)
test_netmiko_show.py::test_send_command_genie SKIPPED (Genie not supported on this platform)
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED
test_netmiko_show.py::test_disconnect_no_enable PASSED

================================================================================== short test summary info ==================================================================================
SKIPPED [1] test_netmiko_show.py:184: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] test_netmiko_show.py:206: TTP template not existing for this platform
SKIPPED [1] test_netmiko_show.py:243: Genie not supported on this platform
============================================================================== 19 passed, 3 skipped in 50.52s ===============================================================================
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 9 items                                                                                                                                                                           

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode PASSED
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_config_set PASSED
test_netmiko_config.py::test_config_set_longcommand PASSED
test_netmiko_config.py::test_config_hostname PASSED
test_netmiko_config.py::test_config_from_file PASSED
test_netmiko_config.py::test_disconnect PASSED

==================================================================================== 9 passed in 20.25s =====================================================================================
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 12 items                                                                                                                                                                          

test_netmiko_scp.py::test_scp_put PASSED
test_netmiko_scp.py::test_remote_space_available PASSED
test_netmiko_scp.py::test_local_space_available PASSED
test_netmiko_scp.py::test_verify_space_available_put PASSED
test_netmiko_scp.py::test_remote_file_size PASSED
test_netmiko_scp.py::test_md5_methods SKIPPED (MD5 not supported on this platform)
test_netmiko_scp.py::test_disconnect PASSED
test_netmiko_scp.py::test_verify_space_available_get PASSED
test_netmiko_scp.py::test_scp_get PASSED
test_netmiko_scp.py::test_md5_methods_get SKIPPED (MD5 not supported on this platform)
test_netmiko_scp.py::test_disconnect_get PASSED
test_netmiko_scp.py::test_file_transfer PASSED

================================================================================== short test summary info ==================================================================================
SKIPPED [1] test_netmiko_scp.py:46: MD5 not supported on this platform
SKIPPED [1] test_netmiko_scp.py:85: MD5 not supported on this platform
============================================================================== 10 passed, 2 skipped in 54.70s ===============================================================================
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.10, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3.7
cachedir: .pytest_cache
rootdir: /root/netmiko, configfile: setup.cfg
collected 15 items                                                                                                                                                                          

test_netmiko_commit.py::test_ssh_connect PASSED
test_netmiko_commit.py::test_config_mode PASSED
test_netmiko_commit.py::test_commit_base PASSED
test_netmiko_commit.py::test_commit_confirm SKIPPED
test_netmiko_commit.py::test_confirm_delay SKIPPED
test_netmiko_commit.py::test_no_confirm SKIPPED
test_netmiko_commit.py::test_clear_msg PASSED
test_netmiko_commit.py::test_commit_check SKIPPED
test_netmiko_commit.py::test_commit_comment SKIPPED
test_netmiko_commit.py::test_commit_andquit SKIPPED
test_netmiko_commit.py::test_commit_label PASSED
test_netmiko_commit.py::test_commit_label_comment SKIPPED
test_netmiko_commit.py::test_commit_label_confirm SKIPPED
test_netmiko_commit.py::test_exit_config_mode PASSED
test_netmiko_commit.py::test_disconnect PASSED

================================================================================== short test summary info ==================================================================================
SKIPPED [1] test_netmiko_commit.py:125: Skipped
SKIPPED [1] test_netmiko_commit.py:152: Skipped
SKIPPED [1] test_netmiko_commit.py:179: Skipped
SKIPPED [1] test_netmiko_commit.py:231: Skipped
SKIPPED [1] test_netmiko_commit.py:262: Skipped
SKIPPED [1] test_netmiko_commit.py:290: Skipped
SKIPPED [1] test_netmiko_commit.py:340: Skipped
SKIPPED [1] test_netmiko_commit.py:373: Skipped
=============================================================================== 7 passed, 8 skipped in 16.46s ===============================================================================
`

**Comment by kielpi** [comment]
Dear Kirk,

Is that ok to have this merged or still something to do ?

**Comment by ktbyers** [comment]
No it is waiting on me...let me see if I can finish the review of it.

**Comment by pszulczewski** [comment]
#2063 also concerns SROS.
We would be grateful if they can be merged both.

Thanks

**Pull request merged**
