### PR TITLE
Add example of using concurrent connections

### PR DESCRIPTION
**Pull request by YAPNie**
Example of using Multithreading (concurrent, class based) connections.
Please, pay attention that I'm a newbie in programming (Python, Git, etc.) and just adapted the example from the Article: https://developer.ibm.com/articles/au-threadingpython/
I used Python v3.6.8.

### CODE REVIEW

**Comment by BSpendlove** [comment]
Why use threading when you can just use concurrent.futures? I think it'd be much cleaner and more friendly to those looking to using threads (or processes with [ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor)

**Comment by ktbyers** [comment]
Agreed...any example should use concurrent.futures.

Here is a pretty simple example:

https://github.com/ktbyers/pyplus_course/blob/master/class10/collateral/ssh_threads_simple.py

**Comment by YAPNie** [comment]
> https://github.com/ktbyers/pyplus_course/blob/master/class10/collateral/ssh_threads_simple.py
Hmm, I did not see it before. I tried to find the example inside the project's documentation and examples but did not find it.
My fail, sorry.

**Comment by ktbyers** [comment]
@YAPNie No worries at all...it is not very easy to find.

**Pull request closed without merging**
