### PR TITLE
Nokia SRL updates (to fix some commit/contributor history issues)

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@sebastien-guay Can you regression test this to make sure I didn't break anything.

I am pretty sure I got everything, but we should sanity check it with the tests.

These were the changes on top of your original PR.

**Comment by ktbyers** [comment]
I might have misunderstood your Contributor comment from earlier. Is that issue fixed now?

Do you have a timeframe on when you need the next Netmiko release?

@sebastien-guay

**Comment by sebastien-guay** [comment]
> 

Maybe it is me that misunderstood the 'Contributor' list. Since you created a new PR and cancelled mine I will not be part of the Contributors list and there will be no traces of my contribution to the project.. I was more wondering if being part of the 'Contributor' would had some permissions on the project.

**Comment by sebastien-guay** [comment]
> 

All the test passed.

**Comment by sebastien-guay** [comment]
> @sebastien-guay Can you regression test this to make sure I didn't break anything.
> 
> I am pretty sure I got everything, but we should sanity check it with the tests.
> 
> These were the changes on top of your original PR.

All the test passed.

**Comment by ktbyers** [comment]
```
Maybe it is me that misunderstood the 'Contributor' list. Since you created a new PR and cancelled mine I will not be part of the Contributors list and there will be no traces of my contribution to the project.
```

Okay, I think that should all be fixed. 

I think the loss of "Contributor" status happened because of the following two things:
1. I created the new PR and then made some additional commits to files.
2. I squashed all of the commits to a single commit (to keep the Git history cleaner).

The single commit was thus co-authored (which you could clearly see in certain places), but on the Contributors section of Netmiko it must have allocated them to me (which is a bad choice on GitHubs parts since they should have been able to see that the line changes were mostly you).

Anyways the above is all fixed...which I fixed by undoing the PR merge and then merging your original PR (and then separately merging my changes after that--in a separate PR).

Note, being a Contributor though won't give you any access to modify the files (i.e. it just an allocation of credit, but doesn't change anything with access rights to the repository).

**Comment by sebastien-guay** [comment]
> ```
> Maybe it is me that misunderstood the 'Contributor' list. Since you created a new PR and cancelled mine I will not be part of the Contributors list and there will be no traces of my contribution to the project.
> ```
> 
> Okay, I think that should all be fixed.
> 
> I think the loss of "Contributor" status happened because of the following two things:
> 
> 1. I created the new PR and then made some additional commits to files.
> 2. I squashed all of the commits to a single commit (to keep the Git history cleaner).
> 
> The single commit was thus co-authored (which you could clearly see in certain places), but on the Contributors section of Netmiko it must have allocated them to me (which is a bad choice on GitHubs parts since they should have been able to see that the line changes were mostly you).
> 
> Anyways the above is all fixed...which I fixed by undoing the PR merge and then merging your original PR (and then separately merging my changes after that--in a separate PR).
> 
> Note, being a Contributor though won't give you any access to modify the files (i.e. it just an allocation of credit, but doesn't change anything with access rights to the repository).

Thanks for your reply @ktbyers and I really appreciated working on your project. For the timeframe I would say by next week if possible. Just tell me if it is possible.

**Comment by ktbyers** [comment]
@sebastien-guay I will try to get a new Netmiko release out by the middle of next week. Just nag me if I forget.

**Comment by ktbyers** [comment]
@sebastien-guay Netmiko Version 4.1.1 has been released to pypi.

https://github.com/ktbyers/netmiko/releases/tag/v4.1.1

**Comment by sebastien-guay** [comment]
> @sebastien-guay Netmiko Version 4.1.1 has been released to pypi.
> 
> https://github.com/ktbyers/netmiko/releases/tag/v4.1.1

Thanks a lot @ktbyers !

**Pull request merged**
