### PR TITLE
Support for HP Comware + HP + Cisco Prompt Check

### PR DESCRIPTION
**Pull request by ravenblue12**
Hi Kirk,

I found your SSH NetDev lib and I like it!
I added support for HP Comware switches and made some prompt checks and I also have tested it against:
Cisco C3750 (IOS)
Cisco Nexus 5596UP (NXOS)
HP 2920, HP 8206zl (Procurve)
HP 870 LSW (Comware 5)

I hope that you like it!

Chears Rene Plattner

### CODE REVIEW

**Comment by ktbyers** [comment]
Rene,

I am going to merge this. I am probably going to back out some/quite a few of the changes that you made to base classes and to the Cisco classes. I am happy to provide explanation of why--I am also open to discussions on which way is better.

Basically, I want the code to be good and have an open process on why certain things were chosen.

**Comment by ravenblue12** [comment]
Great!

**Comment by ktbyers** [comment]
Rene,

I tried to significantly reduce the amount of duplicated code.
Consequently, I made some significant updates to the Comware class.

Can you re-test it against Comware and make sure I didn't break anything.


Regards,

Kirk Byers
ktbyersx@gmail.com



On Thu, Jan 29, 2015 at 10:52 AM, Rene Plattner <notifications@github.com>
wrote:

> Great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/pull/28#issuecomment-72081447>.
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by ravenblue12** [comment]
Ok, I will check it.

Am Freitag, 30. Januar 2015 schrieb Kirk Byers :

**Pull request merged**
