### PR TITLE
F5 disable paging cli command depends on version

### PR DESCRIPTION
**Pull request by zhecho**
Hello all,

I think that session_preparation() should send various "disable paging CLI commands" depends on the F5 firmware version 
I couldn't find command "set length 0" as previous cli command was set... but as we spoke I decided to leave it as well , so for version 11,12,13 it'll execute "modify cli preference pager disabled". I think that this command will work on ver.10.x.x as well but I couldn't find working v.10 for test it 

Best Regards!

### CODE REVIEW

**Comment by zhecho** [comment]
I'll rewrite it with PEP8 requirements

**Comment by johnarnold** [comment]
Related problem -- TMSH can give you really long prompts that the find_prompt function butchers:

h.connection.find_prompt()
read_channel: 
write_channel: b'\n'
read_channel: 
mos)# 
read_channel: 
'mos)#' 

you can fix it by setting the tty width:

h.connection.send_command("run /util bash -c \"stty cols 255\"")
...
h.connection.find_prompt()
read_channel: 
write_channel: b'\n'
read_channel: 
netscript1_rw@(cys01-f72-ucgmc-1a)(cfg-sync Changes Pending)(Standby)(/Common)(tmos)# 
read_channel: 
'netscript1_rw@(cys01-f72-ucgmc-1a)(cfg-sync Changes Pending)(Standby)(/Common)(tmos)#' 

Do you want to add "run /util bash -c \"stty cols 255\""  to session_preparation, so that nobody else hits this?

**Comment by ktbyers** [comment]
@zhecho Why did you remove the entering into `tmsh` mode (line 18)?

**Comment by ktbyers** [comment]
@zhecho @johnarnold I made this change here for the two issues (output paging and terminal width):

https://github.com/ktbyers/netmiko/commit/ac4d676c66f037a850efc452bfd8d6562ae64947

Can one of you test it?

It would be good if we could run the set of Netmiko unit tests against this: 

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md


@zhecho I didn't really want to do the F5 version detection...if you think we really need to do this, let me know. I am a bit out of the loop on F5 LTM, but it sounds like that paging command should go back quite a ways (as far as F5 OS version).

Also, @zhecho just submit a separate PR for your HP change.

**Pull request closed without merging**
