### PR TITLE
Add support for SSH disabled_algorithms parameter introduced in Paramiko 2.6.0

### PR DESCRIPTION
**Pull request by jonglezb**

### CODE REVIEW

**Comment by ktbyers** [comment]
Tests are failing due to a linting issue:

```
Run pylama .
netmiko/base_connection.py:21[8](https://github.com/ktbyers/netmiko/runs/5219807544?check_suite_focus=true#step:6:8):101: E501 line too long (101 > 100 characters) [pep8]
Error: Process completed with exit code 1.
```

Can you fix this?

**Comment by jonglezb** [comment]
Sure! I've force-pushed a fix.

**Comment by ktbyers** [comment]
Okay, one more issue. This time type hints. I think if you change this line:

```python
        disabled_algorithms: Optional[dict] = None,
```

To

```python
        disabled_algorithms: Optional[Dict[str, Any] = None,
```

That should fix that.

**Comment by ktbyers** [comment]
Superseded by:

https://github.com/ktbyers/netmiko/pull/2648

Updated PR fixes the test failures.

**Comment by ktbyers** [comment]
@jonglezb My guess is that you are using the wrong version of mypy.

Netmiko requires mypy:

```
mypy==0.902
mypy-extensions==0.4.3
```

```
$ mypy netmiko
Success: no issues found in 170 source files
```

**Comment by jonglezb** [comment]
Thanks!

**Pull request closed without merging**
