### PR TITLE
Huawei telnet

### PR DESCRIPTION
**Pull request by cuong-nguyenduy**
This PR change the ```telnet_login()``` to use ```read_until_pattern()``` method from the base  class. The improvement handles below scenarios:

1. It takes long time for router to display the ```"Username:"``` prompt. This often leads to the failure of login as the script tries to send ```TELNET_RETURN```, which router interprets as wrong username.

2. It takes router longer time to show the change_password prompt

Tested in the network.

### CODE REVIEW

**Comment by ktbyers** [comment]
Unit tests are failing and linting/black is failing.

**Comment by ktbyers** [comment]
@cuong-nguyenduy You need any assistance on fixing the lint/black errors?

Regards, Kirk

**Comment by cuong-nguyenduy** [comment]
> 
> 
> @cuong-nguyenduy You need any assistance on fixing the lint/black errors?
> 
> Regards, Kirk

@ktbyers  I managed to reformat the code to pass black/lint requirement. Sorry for the delay.

Cuong

**Comment by ktbyers** [comment]
PR updated here:

https://github.com/ktbyers/netmiko/pull/1568

**Pull request closed without merging**
