### PR TITLE
adding dell-powerconnect5XXX support

### PR DESCRIPTION
**Pull request by rdezavalia**
Experimental Dell PowerConnect 54XX and 55XX support. Tested on both 5548 and 5424 switches. No public key allowed yet, only user and password.

### CODE REVIEW

**Comment by ktbyers** [comment]
@rdezavalia Are the Dell PowerConnect 54XX and 55XX similar to other Dell switches? The general naming convention is vendor_platform

Is dell_pc5000 the logical naming for this (i.e. are the power connect 5xxx a separate category of Dell switches).

Kirk

**Comment by rdezavalia** [comment]
Well, I'm not sure if the power connect 5xxx are a separate category of Dell switches, but they have their own authentication scheme. You have to provide the username after the SSH authentication, so if you use user/passwd authentication, you can't use any of the other modules on netmiko. Once you authenticated, it is similar to other Dell switches.

**Comment by ktbyers** [comment]
@rdezavalia Sorry for slow response on this. I will try to follow up on this, this week.

**Comment by ktbyers** [comment]
@rdezavalia I looked into this a little bit. I will have to look into this more as there was meaningfully more custom code required that I expected.

I am going to put this on hold for a while.

**Comment by rdezavalia** [comment]
@ktbyers go ahead and take a look. The problem is the way PC 5XXX authenticate the ssh session. I'm not working on this right now, as my day job has moved to some other direction, but I will probably continue my work on netmiko and PC 5XXX in a few weeks. Please contact me if in any doubt.

**Comment by ktbyers** [comment]
@rdezavalia Yes, makes sense. I just to review more thoroughly.

**Comment by absolutejam** [comment]
Any chance this is still being looked at? I've just discovered this amazing tool, but unfortunately I'm dealing with mostly PowerConnect switches!

Great work on this regardless!

**Comment by ktbyers** [comment]
@absolutejam There is some amount of Dell support, unfortunately, we have run into some issues, see:

https://github.com/ktbyers/netmiko/issues/128

I still need to look at this PR.  I also probably need a PowerConnect 5xxx device to test against (at least temporarily)

Finally, I need a long-term owner of the PowerConnect code (i.e. someone that is willing to regression test it for new Netmiko releases).

**Comment by absolutejam** [comment]
Might have a spare I can hook up for you to test, or test myself? I tried a couple of different device types for the connection using a password but each errored. If there's something I can do to help out, let me know!

**Comment by ktbyers** [comment]
@absolutejam I missed your response earlier are you still open to looking at this.

**Comment by ktbyers** [comment]
This would rebased and resubmitted again...largely my fault that this didn't get done earlier, but if someone wants to resubmit it we can try again.

**Pull request closed without merging**
