### PR TITLE
Proposed fix for mikrotik issues

### PR DESCRIPTION
**Pull request by ktbyers**
You must have cmd_verify=True which should be the default. Otherwise, I think you will potentially run into issues with Mikrotik devices.

It looks like to me that Mikrotik repaints the line including both the router prompt and the command as part of the command echo process.

This was why we put some initial odd behaviors in for both strip_command and strip_prompt (in the Mikrotik driver). I think these problems go away with newer Netmiko and cmd_verify. So I removed the special strip_command and strip_prompt methods (from the mikrotik driver).

### CODE REVIEW

**Comment by NoifP** [comment]
Thanks @ktbyers - this looks like an improvement;
`output = net_connect.send_command(command)` now works and returns data (just like in 2.4.0) but it has not stripped the prompt.

netmiko 2.4.1 returns this:
```
(' 0  DR name=<l2tp-ppp1-1> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=20m28s encoding=MPPE128 stateless \n'
 ' 1  DR name=<l2tp-ppp1-2> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=20m28s encoding=MPPE128 stateless \n'
 ' 2  DR name=<l2tp-ppp1-3> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=20m28s encoding=MPPE128 stateless \n'
 ' 3  DR name=<l2tp-ppp1-4> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=20m28s encoding=MPPE128 stateless \n'
 ' 4  DR name=<l2tp-ppp1> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=20m28s encoding=MPPE128 stateless \n'
 '\n'
 '\n'
 '\n'
 '\n')
```

netmiko 3.4.0 PR 2362 returns the following:
```
('\n'
 ' 0  DR name=<l2tp-ppp1-1> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=16m8s encoding=MPPE128 stateless \n'
 ' 1  DR name=<l2tp-ppp1-2> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=16m8s encoding=MPPE128 stateless \n'
 ' 2  DR name=<l2tp-ppp1-3> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=16m8s encoding=MPPE128 stateless \n'
 ' 3  DR name=<l2tp-ppp1-4> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=16m8s encoding=MPPE128 stateless \n'
 ' 4  DR name=<l2tp-ppp1> user=ppp1 mtu=1450 mru=1450 '
 'client-address=192.168.1.130 uptime=16m8s encoding=MPPE128 stateless \n'
 '\n'
 '\n'
 '\n'
 '\n'
 '\n'
 '[test@tik3] '
 '>


```

**Comment by ktbyers** [comment]
@NoifP Okay, thanks. I am working on some additional updates/improvements to these changes.

**Comment by NoifP** [comment]
@kbirkeland I'm not sure if this is relevant (it could just be down to connection options?) but the text coming back appears to be wrapped. Compare output above to ssh (OpenSSH_7.6p1).
```
ssh test@192.168.1.130 /interface l2tp-server print terse without-paging
test@192.168.1.130's password:
 0  DR name=<l2tp-ppp1-1> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=9m53s encoding=MPPE128 stateless
 1  DR name=<l2tp-ppp1-2> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=9m53s encoding=MPPE128 stateless
 2  DR name=<l2tp-ppp1-3> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=9m53s encoding=MPPE128 stateless
 3  DR name=<l2tp-ppp1-4> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=9m53s encoding=MPPE128 stateless
 4  DR name=<l2tp-ppp1> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=9m53s encoding=MPPE128 stateless

```

**Comment by NoifP** [comment]
Sorry, I've just noticed that pprint mangled the output by shortening it... The only problem I can see is that the trailing prompt and line with heaps of spaces doesn't get stripped.
The output without pprint (just printed) is as follows:
```

 0  DR name=<l2tp-ppp1-1> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=24m47s encoding=MPPE128 stateless
 1  DR name=<l2tp-ppp1-2> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=24m47s encoding=MPPE128 stateless
 2  DR name=<l2tp-ppp1-3> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=24m47s encoding=MPPE128 stateless
 3  DR name=<l2tp-ppp1-4> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=24m47s encoding=MPPE128 stateless
 4  DR name=<l2tp-ppp1> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=24m47s encoding=MPPE128 stateless





[test@tik3] >                                                                                                                                                                                                                                                                                                                                                                                                                                         


```

**Comment by antonc42** [comment]
I'm seeing the same thing. The command works, but the prompt and trailing spaces aren't stripped. I built from the 'fix_mikrotik' branch.

```
>>> from netmiko import ConnectHandler
>>> from pprint import pprint
>>> mikrotik = { 'device_type': 'mikrotik_routeros', 'host': 'X.X.X.X', 'username': 'admin', 'password': 'password' }
>>> con = ConnectHandler(**mikrotik)
>>> pprint(con.send_command('/system identity print',cmd_verify=True))
('\n'
 '  name: MikroTik\n'
 '\n'
 '\n'
 '\n'
 '\n'
 '[admin@MikroTik] '
 '>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ')
```

**Comment by ktbyers** [comment]
Okay, more updates...I think this fixes the issues that you mentioned @NoifP and @antonc42

**Comment by antonc42** [comment]
@ktbyers Everything appears to be normal now. Awesome work!

```
>>> from netmiko import ConnectHandler
>>> from pprint import pprint
>>> mikrotik = { 'device_type': 'mikrotik_routeros', 'host': 'X.X.X.X', 'username': 'admin', 'password': 'password' }
>>> con = ConnectHandler(**mikrotik)
>>> pprint(con.send_command('/system identity print',cmd_verify=True))
'name: MikroTik'
>>> pprint(con.send_command('/system resource print',cmd_verify=True))
('uptime: 1w5d3h34m56s\n'
 '                  version: 6.46 (stable)\n'
 '               build-time: Dec/02/2019 11:16:46\n'
 '         factory-software: 6.36.1\n'
 '              free-memory: 212.5MiB\n'
 '             total-memory: 256.0MiB\n'
 '                      cpu: MIPS 1004Kc V2.15\n'
 '                cpu-count: 4\n'
 '            cpu-frequency: 880MHz\n'
 '                 cpu-load: 0%\n'
 '           free-hdd-space: 3472.0KiB\n'
 '          total-hdd-space: 16.3MiB\n'
 '  write-sect-since-reboot: 1684\n'
 '         write-sect-total: 3481\n'
 '               bad-blocks: 0%\n'
 '        architecture-name: mmips\n'
 '               board-name: hEX\n'
 '                 platform: MikroTik')

```

**Comment by ktbyers** [comment]
@antonc42 FYI, cmd_verify should already default to True so you shouldn't need to explicitly set it.

**Comment by ktbyers** [comment]
I am still running into a few edge case failures...so working on trying to fix those.

**Comment by antonc42** [comment]
@ktbyers Understood about cmd_verify. I just wanted to make sure it was explicit. Let me know when it's ready to test again.

**Comment by NoifP** [comment]
Thanks @ktbyers it is looking much better now (tested c436154a). No trailing lines, prompt is being stripped, no excessive spaces. The only tiny detail I can see is that a single leading space on the first line of the response is being stripped as well but this is easy to live with because ttp can take care of that 👍 
```
0  DR name=<l2tp-ppp1-1> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=4m5s encoding=MPPE128 stateless
 1  DR name=<l2tp-ppp1-2> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=4m5s encoding=MPPE128 stateless
 2  DR name=<l2tp-ppp1-3> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=4m5s encoding=MPPE128 stateless
 3  DR name=<l2tp-ppp1-4> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=4m5s encoding=MPPE128 stateless
 4  DR name=<l2tp-ppp1> user=ppp1 mtu=1450 mru=1450 client-address=192.168.1.130 uptime=4m5s encoding=MPPE128 stateless
```

Mikrotik is a bit "fun" with leading spaces on stuff too. For example - list items 0-9 get a leading space. Note that I've snipped the list down (indicated by ... ). The first number on each line is the item ID number.
```
 0  DR name=<l2tp-username01> user=username01 mtu=1596 mru=1600 client-address=10.0.0.165 uptime=18h25m47s encoding="" 
 1  DR name=<l2tp-username02> user=username02 mtu=1596 mru=1600 client-address=10.0.0.168 uptime=18h22m10s encoding="" 
 2  DR name=<l2tp-username03> user=username03 mtu=1596 mru=1600 client-address=10.0.0.69 uptime=18h24m21s encoding="" 
...
 9  DR name=<l2tp-username04> user=username04 mtu=1596 mru=1600 client-address=10.0.0.196 uptime=18h25m31s encoding="" 
10  DR name=<l2tp-username05> user=username05 mtu=1596 mru=1600 client-address=10.0.0.192 uptime=18h21m7s encoding="" 
11  DR name=<l2tp-username06> user=username06 mtu=1596 mru=1600 client-address=10.0.0.223 uptime=18h22m52s encoding="" 
...
98  DR name=<l2tp-username07> user=username07 mtu=1596 mru=1600 client-address=10.0.0.96 uptime=18h23m41s encoding="" 
99  DR name=<l2tp-username08> user=username08 mtu=1596 mru=1600 client-address=10.0.0.179 uptime=18h23m39s encoding="" 
100  DR name=<l2tp-username09> user=username09 mtu=1596 mru=1600 client-address=10.0.0.141 uptime=18h23m39s encoding="" 
101  DR name=<l2tp-username010> user=username010 mtu=1596 mru=1600 client-address=10.0.0.50 uptime=18h21m21s encoding="" 
```

**Comment by ktbyers** [comment]
Okay, I think this is the final version with the needed fixes:

```
test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_terminal_width PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_timing_no_cmd_verify SKIPPED
test_netmiko_show.py::test_send_command PASSED
test_netmiko_show.py::test_send_command_no_cmd_verify SKIPPED
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED
test_netmiko_show.py::test_send_command_textfsm SKIPPED
test_netmiko_show.py::test_send_command_ttp SKIPPED
test_netmiko_show.py::test_send_command_genie SKIPPED
test_netmiko_show.py::test_send_multiline_timing SKIPPED
test_netmiko_show.py::test_send_multiline SKIPPED
test_netmiko_show.py::test_send_multiline_prompt SKIPPED
test_netmiko_show.py::test_send_multiline_simple SKIPPED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED
test_netmiko_show.py::test_disconnect_no_enable PASSED
```

Let me know if you see any other issues.

**Comment by mallikarjunbiradar79** [comment]
@ktbyers I am also facing this issue, where I am unable to see output of my RouterOS (Mikrotik) command, log file attached. I am new to this, would like to get the fix installed locally to my machine, can you please help with the procedure?

[test.log](https://github.com/ktbyers/netmiko/files/7197618/test.log)

**Comment by ktbyers** [comment]
Basically, the procedure is to install the `develop` branch of Netmiko which you should be able to do via `pip` and then test with that.

You should be able to look up online how to install a specific commit from GitHub using pip.


Regards, Kirk

**Comment by ignatievia** [comment]
@ktbyers when can we expect this fix to be applied in the Netmiko Plugins for Nornir?
As I can see the latest `nornir-netmiko` version is incompatible with `develop` version of Netmiko
`nornir-netmiko 0.1.2 requires netmiko<4.0.0,>=3.4.0, but you'll have netmiko 4.0.0a2 which is incompatible.`

**Comment by ktbyers** [comment]
@ignatievia It will probably be a month or two as I have to retrofit a set of things to support Netmiko 4.X (after I release it). 

You can workaround it yourself i.e. just `git clone` nornir-netmiko and edit the pyproject.toml file (no guarantee it works with Netmiko 4.x, however, as I haven't tested it or done any work on integrating Netmiko 4.x into Nornir (and I have a set of other libraries that I have to do Netmiko 4.x integration work on as well).

**Pull request merged**
