### PR TITLE
Ansi insert line for ProCurve and Aruba

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@brasswood I updated this PR here.

Would you be able to re-test this updated fix solves the underlying issue?

I tried to test it on my ProCurve, but I couldn't reproduce the behavior.

**Comment by ktbyers** [comment]
Note, there was another minor issue I discovered related to `code_erase_display` that I also fixed here.

**Comment by ktbyers** [comment]
I am going to go ahead and merge this as from the unit tests I am pretty sure it is working. If you still see issues, just let me know.

**Comment by brasswood** [comment]
Unit tests are working for me. Ran a nornir playbook and that worked too. All is well!

If you weren't planning on it already, will you take a look at #1810?

**Pull request merged**
