### PR TITLE
Added initial support for TP-Link JetStream

### PR DESCRIPTION
**Pull request by piterpunk**
This PR adds a new driver to support TP-Link JetStream switches, accepting connections through SSH or Telnet. It borrows the dsa code sample from #1250 and builds over the "unable to find prompt" discussion there.

The driver was tested in a TP-Link JetStream T1500G-10PS 2.0 both using tplink_jetstream device, connected by SSH, and tplink_jetstream_telnet device, connected by Telnet. It sucessfully login, enter in enable and configure mode, sends commands, saves the configuration, exit enable and configure mode, etc.

This PR closes issue #1911

### CODE REVIEW

**Comment by ktbyers** [comment]
@piterpunk Looks like it is failing the linter/black.

Can you run `black .` on the code (to fix the black issues)?

Also, can you run the standard Netmiko `show` and `config` tests on this driver and post the output in this PR. More details can be found here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

Thanks, Kirk

**Comment by piterpunk** [comment]
I already ran `black` in the new driver and now it's Ok here, in my local repo. But the running `black .` tries to change some code unrelated to this PR:
```
black --check .
would reformat /home/punk/Desktop/Projects/Software/External/netmiko/netmiko/cisco_base_connection.py
would reformat /home/punk/Desktop/Projects/Software/External/netmiko/netmiko/_textfsm/_clitable.py
would reformat /home/punk/Desktop/Projects/Software/External/netmiko/tests/conftest.py
would reformat /home/punk/Desktop/Projects/Software/External/netmiko/netmiko/_textfsm/_texttable.py
Oh no! 💥 💔 💥
4 files would be reformatted, 208 files would be left unchanged.
```
Should I change those files, too?

Also, I did the tests and these is the output form them:
```
Starting tests...good luck:
======================================================= test session starts ========================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
tempdir: /tmp/tests
rootdir: /home/punk/Desktop/Projects/Software/External/netmiko, inifile: setup.cfg
plugins: tempdir-2019.10.12, helpers-namespace-2019.1.8, salt-2020.1.27, pylama-7.7.1
collected 21 items                                                                                                                 

test_netmiko_show.py::test_disable_paging PASSED                                                                             [  4%]
test_netmiko_show.py::test_terminal_width PASSED                                                                             [  9%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                [ 14%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                             [ 19%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                        [ 23%]
test_netmiko_show.py::test_send_command_timing_no_cmd_verify PASSED                                                          [ 28%]
test_netmiko_show.py::test_send_command PASSED                                                                               [ 33%]
test_netmiko_show.py::test_send_command_no_cmd_verify PASSED                                                                 [ 38%]
test_netmiko_show.py::test_cmd_verify_decorator PASSED                                                                       [ 42%]
test_netmiko_show.py::test_send_command_global_cmd_verify PASSED                                                             [ 47%]
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED                                                                [ 52%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED                                                                      [ 57%]
test_netmiko_show.py::test_send_command_genie SKIPPED                                                                        [ 61%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                [ 66%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                               [ 71%]
test_netmiko_show.py::test_strip_command PASSED                                                                              [ 76%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                        [ 80%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                               [ 85%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                [ 90%]
test_netmiko_show.py::test_disconnect PASSED                                                                                 [ 95%]
test_netmiko_show.py::test_disconnect_no_enable PASSED                                                                       [100%]

===================================================== short test summary info ======================================================
SKIPPED [1] /home/punk/Desktop/Projects/Software/External/netmiko/tests/test_netmiko_show.py:157: <Skipped instance>
SKIPPED [1] /home/punk/Desktop/Projects/Software/External/netmiko/tests/test_netmiko_show.py:178: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /home/punk/Desktop/Projects/Software/External/netmiko/tests/test_netmiko_show.py:203: Genie not supported on this platform
============================================= 18 passed, 3 skipped in 73.17s (0:01:13) =============================================
======================================================= test session starts ========================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
tempdir: /tmp/tests
rootdir: /home/punk/Desktop/Projects/Software/External/netmiko, inifile: setup.cfg
plugins: tempdir-2019.10.12, helpers-namespace-2019.1.8, salt-2020.1.27, pylama-7.7.1
collected 9 items                                                                                                                  

test_netmiko_config.py::test_ssh_connect PASSED                                                                              [ 11%]
test_netmiko_config.py::test_enable_mode PASSED                                                                              [ 22%]
test_netmiko_config.py::test_config_mode PASSED                                                                              [ 33%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                         [ 44%]
test_netmiko_config.py::test_config_set PASSED                                                                               [ 55%]
test_netmiko_config.py::test_config_set_longcommand PASSED                                                                   [ 66%]
test_netmiko_config.py::test_config_hostname PASSED                                                                          [ 77%]
test_netmiko_config.py::test_config_from_file PASSED                                                                         [ 88%]
test_netmiko_config.py::test_disconnect PASSED                                                                               [100%]

======================================================== 9 passed in 17.24s ========================================================
```

**Comment by piterpunk** [comment]
well, it seems that fixing only `netmiko/tplink/tplink_jetstream.py` were enough.

**Comment by ktbyers** [comment]
Superceded by:

https://github.com/ktbyers/netmiko/pull/1920

**Pull request closed without merging**
