### PR TITLE
extend cisco_nxos device type to accomodate for cisco ucs

### PR DESCRIPTION
**Pull request by jonesbra**
Cisco UCS will output similar to the following to show version command: 
```

Firmware Version     
-------------------- 
2.0(6d)            

```

@ktbyers  - Show version output.

### CODE REVIEW

**Comment by ktbyers** [comment]
@jonesbra "Firmware Version" is too generic. If there is something more specific that we can match on that, then that might work.

**Comment by ktbyers** [comment]
If you output the "show version" we can see if there is a string in the output that might work.

**Comment by ktbyers** [comment]
Can you post the "show version" here?

That isn't going to be sufficient i.e. it is too generic of a pattern to search on.


Regards, Kirk

**Comment by jonesbra** [comment]
The original comment has been updated with the show version output.

**Comment by ktbyers** [comment]
You can try something other command that would uniquely identify it, but that is not going to work.

It is too general and would likely cause false matches.

**Pull request closed without merging**
