### PR TITLE
nokia_sros: Add support for md-cli only mode

### PR DESCRIPTION
**Pull request by lub-dub**
Currently copying files fails, if the system does not allow switching to classic CLI. This change will allow copying files even in MD-CLI only.

### CODE REVIEW

**Comment by ktbyers** [comment]
@lub-dub Do you have example output for the following cases (from a MD-CLI device)?

```
file list cf3:
file list cf3:/somefile.txt
```

In the "somefile.txt" case both when this file exists and when it doesn't exist?

**Comment by lub-dub** [comment]
Ommitted some files for privacy reasons:
```
A:admin@md-cli# file list cf3:

Volume in drive cf3 on slot A is TIMOS-CPMA.

Volume in drive cf3 on slot A is formatted as FAT32

Directory of cf3:\

08/19/2024  10:24a      <DIR>          .commit-history/
...
09/05/2023  02:46p      <DIR>          EFI/
05/08/2023  02:36p      <DIR>          MIBs/
09/09/2024  12:37p      <DIR>          TiMOS-SR-23.10.R6/
07/19/2024  08:42a      <DIR>          TiMOS-SR-24.7.R1/
08/19/2024  10:16a                1038 bof.cfg
08/19/2024  09:56a                1176 bof.cfg.1
07/25/2024  03:27p                1048 bof.cfg.2
07/19/2024  05:50p                1043 bof.cfg.3
07/19/2024  08:55a                 772 bof.cfg.4
07/09/2024  04:15p                 777 bof.cfg.5
07/09/2024  04:11p                 729 bof.cfg.6
09/16/2022  03:40p                 211 bof.ztp.cfg
08/16/2024  08:41p             8011840 boot.ldr
08/19/2024  10:24a                4824 bootlog.txt
08/19/2024  10:14a                4953 bootlog_prev.txt
08/19/2024  10:06a              111230 config.cfg
08/01/2024  03:10p              111511 config.cfg.1
07/22/2024  01:06p              111190 config.cfg.2
07/22/2024  01:04p              111536 config.cfg.3
07/19/2024  08:56a              111484 config.cfg.4
07/18/2024  09:21a              116152 config.cfg.5
....
05/08/2023  02:49p      <DIR>          ssh/
05/08/2023  02:36p      <DIR>          support/
              35 File(s)               21876352 bytes.
               7 Dir(s)               552095744 bytes free.
```

```
A:admin@md-cli# file list cf3:/somefile.txt

Volume in drive cf3 on slot A is TIMOS-CPMA.

Volume in drive cf3 on slot A is formatted as FAT32

Directory of cf3:

MINOR: MGMT_AGENT #2005: Invalid element value - open directory "cf3:\somefile.txt"
```

```
A:admin@md-cli# file list cf3:/somefile.txt

Volume in drive cf3 on slot A is TIMOS-CPMA.

Volume in drive cf3 on slot A is formatted as FAT32

Directory of cf3:

09/16/2024  09:03a                   2 somefile.txt
               1 File(s)                      2 bytes.
               0 Dir(s)               552091648 bytes free.

```

**Comment by ktbyers** [comment]
@lub-dub Thanks...I will try to look at the outputs you provided tomorrow.

**Review by ktbyers — APPROVED** [review]
LGTM

**Pull request merged**
