### PR TITLE
fixed double newline in ICX output

### PR DESCRIPTION
**Pull request by LindsayHill**
Not sure if this is the 'right' way to do this or not. But it addresses this problem:
```
>>> config_commands = ['logging console',
...                    'no logging console']
>>> output = net_connect.send_config_set(config_commands)
>>> print(output)
config term

SSH@ICX7250-24P Router(config)#logging console

SSH@ICX7250-24P Router(config)#no logging console

SSH@ICX7250-24P Router(config)#end

SSH@ICX7250-24P Router#
>>> print (repr(output))
u'config term\n\nSSH@ICX7250-24P Router(config)#logging console\n\nSSH@ICX7250-24P Router(config)#no logging console\n\nSSH@ICX7250-24P Router(config)#end\n\nSSH@ICX7250-24P Router#'
>>>
```
After making this change, the output looks like this:
```
>>> config_commands = ['logging console',
...                    'no logging console']
>>> output = net_connect.send_config_set(config_commands)
>>> print(output)
config term
SSH@ICX7250-24P Router(config)#logging console
SSH@ICX7250-24P Router(config)#no logging console
SSH@ICX7250-24P Router(config)#end
SSH@ICX7250-24P Router#
>>>
```

### CODE REVIEW

**Comment by LindsayHill** [comment]
That gives me this:
```
>>> config_commands = ['logging console',
...                    'no logging console']
>>> output = net_connect.send_config_set(config_commands)
>>> print(output)
config term

SSH@ICX7250-24P Router(config)#logging console

SSH@ICX7250-24P Router(config)#no logging console

SSH@ICX7250-24P Router(config)#end

SSH@ICX7250-24P Router#
>>> print(repr(output))
u'config term\r\n\r\nSSH@ICX7250-24P Router(config)#logging console\r\n\r\nSSH@ICX7250-24P Router(config)#no logging console\r\n\r\nSSH@ICX7250-24P Router(config)#end\r\n\r\nSSH@ICX7250-24P Router#'
>>>
```

**Comment by LindsayHill** [comment]
OK, I think this is a better fix. I first used the same pattern as used for the F5 adapter (https://github.com/ktbyers/netmiko/blob/master/netmiko/f5/f5_ltm_ssh.py#L31) but that didn't work. It looks like the problem is the order of matching. It matches the first `\r\n` rather than the full `\r\n\r\n`.

**Comment by ktbyers** [comment]
@LindsayHill So this latest fix gives you the output that you would expect when you test it.


Kirk

**Comment by LindsayHill** [comment]
Yep. Seems to behave itself with the latest fix.

**Pull request merged**
