### PR TITLE
Initial docs framework build-out

### PR DESCRIPTION
**Pull request by ebeahan**
Initial build out of proposed documentation framework as discussed in https://github.com/ktbyers/netmiko/issues/285

### CODE REVIEW

**Comment by ktbyers** [comment]
@ebeahan Okay, nice. Let me check it out.

**Comment by ktbyers** [comment]
@ebeahan I think I am going to do the following (relevant to your context manager PR also).

1. Release Netmiko 1.1 to pypi.
2. Create a new dev_1_2 branch and merge/test those there.

**Comment by ebeahan** [comment]
@ktbyers Ok sounds good. Let me know when the dev_1_2 branch is created and I'll update my PRs appropriately.

**Comment by ktbyers** [comment]
@ebeahan Okay, netmiko-1.1.0 has been released, dev_1_2 branch has been created (if you want to update your PRs).

**Pull request merged**
