### PR TITLE
Fix issue with Nokia SROS MD-CLI having square bracket data being stripped

### PR DESCRIPTION
**Pull request by ktbyers**
…ipped in send_command

### CODE REVIEW

**Comment by ktbyers** [comment]
@svautour

I am going to go ahead and merge this, but it would be great if you could verify that this fixes the original problem.

**Comment by svautour** [comment]
Sure, I can test. Can I just run "pip install netmiko --upgrade" to get the
new version?

Serge

**Comment by ktbyers** [comment]
You will need to `pip install` the Netmiko develop branch. This should be documented/detailed online.

I would probably first:

`pip uninstall netmiko`

To force it be re-installed (on your subsequent pip command).

**Comment by svautour** [comment]
Per google, I ended up doing:

pip3 install git+https://github.com/ktbyers/netmiko.git

Successfully installed netmiko-4.0.1a1 pyyaml-6.0

Now when I run the same script:

print (repr(NokiaCMDOutput))

           router-id 10.1.0.15
            system-id 0100.0100.0015
            traffic-engineering true
            area-address [49.0000]
            segment-routing {

print (NokiaCMDOutput)

            system-id 0100.0100.0015
            traffic-engineering true
            area-address [49.0000]
            segment-routing {

When I run on a different device with more square brackets in the config:

            traffic-engineering true
            export-policy ["RP_ISIS_EXPORT"]
            area-address [49.0000 49.0001]
            segment-routing {

Looks good to me. Thanks!

Serge

**Comment by ktbyers** [comment]
@svautour Okay, great. Thanks for reporting the issue and for testing it.


Kirk

**Pull request merged**
