### PR TITLE
added support for VERSA Networks FlexVNF

### PR DESCRIPTION
**Pull request by fherbet**
Hi @ktbyers , i've initiated onboarding of Versa Networks FlexVNF support (used for SDWAN setups)

Their OS is juniper-like, some characters are swapped like % # when in config mode and so on.
i have basically used juniper_ssh lib to start building this.
i've tested all methods in my venv,  so far so good...

i've currently learning PYTHON / GIT / GITHUB so please forgive me whether you find inconsistencies in python code or github process! would be pleased to get some guidance or hints regarding missed parts..

thanks in advance!

### CODE REVIEW

**Comment by ktbyers** [comment]
@fherbet You have some linter issues that need fixed (that is why Travis-CI is failing):

```
$ pylama .
netmiko/flexvnf/flexvnf_ssh.py:5:1: W0611 'os' imported but unused [pyflakes]
netmiko/flexvnf/flexvnf_ssh.py:8:1: W0611 'netmiko.scp_handler.BaseFileTransfer' imported but unused [pyflakes]
netmiko/flexvnf/flexvnf_ssh.py:150:9: E303 too many blank lines (2) [pep8]
```

**Comment by ktbyers** [comment]
Nope, still failing (see the above Travis-CI tests).

You can run 'pylama .' from the base of the Netmiko repository (the same directory as the setup.py file) to run the linter yourself.

Kirk

**Comment by fherbet** [comment]
@ktbyers looks good now ! can you please check? cheers!

**Comment by jesse-mcgraw** [comment]
Is this still being worked on?  It would be a very useful addition

**Comment by ktbyers** [comment]
Yes, we will try to look at it review, but unfortunately I have had a big backlog on some of these PRs (i.e. haven't been able to get to them for a long time).

**Comment by jesse-mcgraw** [comment]
I was needing to work with FlexVNF devices today which is what led me to this PR.  

FWIW, I manually added the new files and ssh_dispatcher changes to my local installation and they are working, at least superficially

**Comment by ktbyers** [comment]
Updated here:

https://github.com/ktbyers/netmiko/pull/1173

**Pull request closed without merging**
