### PR TITLE
Fixed delay issue in Cisco devices and enable password prompt handling 

### PR DESCRIPTION
**Pull request by viholla**
https://github.com/ktbyers/netmiko/issues/2987

### CODE REVIEW

**Comment by viholla** [comment]
@ktbyers Please help me here. My team is waiting for this fix.

**Comment by ktbyers** [comment]
@viholla You can incorporate any fix you want in your code. In other words, you already have the Netmiko code and your fix (so you can incorporate or not incorporate, but it doesn't depend on me approving it).

Can you explain to me the underlying issue you are trying to fix? If you are trying to fix an initial configuration problem that requires accessing the device via a console/terminal server, then this is probably not the location to fix the issue.

**Comment by viholla** [comment]
@ktbyers So cisco devices have implemented a new rule where configuring enable secret is mandatory for any new device bring up, we can't leave it empty. Once configured, it can be saved or discarded and return to the prompt. To handle this ,I have introduced this new fix. If there is any other way to handle the prompt, please let me know.

**Comment by ktbyers** [comment]
I am just going to close this as this doesn't look like the right place for this fix. Though if you have more information on the output and situation where it happens, then I can possibly see how you could potentially handle it.

**Pull request closed without merging**
