### PR TITLE
add support for Cisco TelePresence endpoints (TC and CE software)

### PR DESCRIPTION
**Pull request by ahmadbarrin**
Hello,

Sorry for the late update. This PR follow the old PR#345.

For this class I redefine send_command method to add "prompt_search_last_depth" variable. Prompt  on Cisco Telepresence ("OK" most of the case) is not in the current line (cursor) but the line just before do I set "prompt_search_last_depth=-2" to search prompt on the line just before.

@Kirk, I look on your link for Netmiko Unit test but I didn't know how to configure it for Cisco Telepresence. Especially on command.yml and response.yml, I don't understand what to put in each tag "basic", "extended_output", "version_banner", "multiple_line_output"... most of them doesn't exist for Cisco Telepresence has shell is really basic, completely different than Cisco IOS. Can you contact me for some help on unit tests ?

Thanks,
Ahmad BARRIN

### CODE REVIEW

**Comment by ahmadbarrin** [comment]
Kirk,

I've done some python research and if you're okay with that, I'll cancel the other part (ie : Windows SSH). I've found python library "winrm" (https://github.com/diyan/pywinrm) more appropriate for windows server. it connects using powershell and this is native on OS windows since windows7/windows2008R2, better than installing a third-party SSH server on it.

Regards,
Ahmad BARRIN

**Comment by ktbyers** [comment]
@ahmadbarrin Can you explain why you need to overwrite the existing send_command()

In other words, what about the Telepresence devices CLI requires this?

Also can you explain which Telepresence devices this supports (I am out of the loop on Telepresence devices).

Finally, you will need to run the 'show' and 'config' unit tests against your driver. See here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md


Let me know if you need assistance on this.

**Comment by ahmadbarrin** [comment]
Hi @ktbyers,

Thanks for your reply.
I was force to overwrite send_command() because in this Cisco device, prompt is not on cursor line but on line just before (or line before last depend of the situation). See file "CiscoTCCE_shell_format_example.png".
To make it recognize prompt in a previous line I add a paramater "prompt_search_last_depth" and my custom send_command() use it to search for from curssor position up to prompt_search_last_depth value (self.prompt_search_last_depth = -2).

This class support all Cisco Collaboration endpoints in TC/CE sofwtare release. This include many device models : MX200, MX200 G2, MX300, MX300G2, MX700, MX800, SX10, SX20, SX80, DX70, DX80, EX90

most of them are include in this product overview document (from page 2 to 7) :
(http://www.cisco.com/c/dam/en/us/solutions/collateral/business-video/business-video/endpoint-product-matrix.pdf)

I didn't use py.test before. and I didn't understand how to use it even after reading TESTING.md. I'd ike some help on this.
Also another concern is this device are quite expensive I don't have any lab one to give you a complete configuration output. I've tested this class in one of production device on the customer I'm working with, but he will refuse give you his device configuration.

Regards,
Ahmad

ciscotcce_xconfig show run equivalent sample
ciscotcce_shell_format_example

**Comment by ktbyers** [comment]
From looking at this...we should be able to just use `OK` or `ERROR` to indicate command completion. I will probably merge this in, but then make some modifications to it.

We will then need to work out a way to test the modifications.

**Comment by ktbyers** [comment]
@ahmadbarrin I put quite a few changes in...see here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_tp_tcce.py


Can you test this updated driver and see if still works (at least as well as what you implemented previously)?

**Comment by ahmadbarrin** [comment]
Hello,

@ktbyers 
unfortunately using my test script some command works with your updated version but other not.

- all wrong command (example "whoaami") that return "Command not recognized." failed. it cause script to be stuck on a loop.
- I cannot show you because this command contain many critical info, but "xstatus" command '(large output command) finish before expected. With your version I just got the first 388 lines instead of the complete output (515 lines, and working on my version). In output I've noticed in line 328  text is "_*s Video Input Connector 1 SignalState: OK_". May be the "OK" at the end is mistaken with "OK" prompt ? Also search a very generic text like "OK" in the whole content is really risky I think. It's probably safer to search on last two returned lines only.

Here is attached the example script I use to connect on my Cisco Telepresence device and associated output with develop branch version and my version.

[test_netmiko_visio1.zip](https://github.com/ktbyers/netmiko/files/778502/test_netmiko_visio1.zip)

It's a pleasure to work on this interesting topics with you. Don't hesitate to contact me if you need more info or need to do more test with my device.

See you,
Ahmad

**Comment by ktbyers** [comment]
@ahmadbarrin So what does it look like in the CLI when you run the invalid command `whoaami`. Can you show what this looks like directly from the CLI?

**Comment by ahmadbarrin** [comment]
@ktbyers 
Yes of course. Here it is:
image

**Comment by ahmadbarrin** [comment]
@ktbyers 
Thanks for posting in master1.2.8 my class you've modified.
I've just noticed in my previous attachement, I've put output text file as .py instead of .txt so you may have miss them. I attach them again in ".txt" format this time.

As a reminder, here is the two error we have with your updated class : 
- manage incorrect commands (need to reconized shell prompt pattern "Command not recognized.")
- xstatus command output : ignore "OK" pattern if it's not at the begining of the line, this is command output and not prompt.  Example taken from "xstatus" command output :  "*s Video Input Connector 1 SignalState: OK"

Compare with my oiginal class version may help to fix as it's working fine for both scenario.

Don't hesitate to contact me if needed.

Ahmad BARRIN
[test_netmiko_visio1 output (develop version).txt](https://github.com/ktbyers/netmiko/files/793682/test_netmiko_visio1.output.develop.version.txt)
[test_netmiko_visio1 output (my version).txt](https://github.com/ktbyers/netmiko/files/793683/test_netmiko_visio1.output.my.version.txt)
[test_netmiko_visio1 output (putty log equivalent).txt](https://github.com/ktbyers/netmiko/files/793681/test_netmiko_visio1.output.putty.log.equivalent.txt)

**Comment by ahmadbarrin** [comment]
Hi
@ktbyers I've done some troubleshooting and make your version works perfectly for both cases and other different commands by just replacing :  
cisco_tp_tcce.py line 68 : "expect_string = r'^(OK|ERROR|Command not recognized\.)$'"

by : 
expect_string = r'^\n(OK|ERROR|Command not recognized\.)'
kwargs.setdefault('expect_string', expect_string)


I preprend regex pattern with "\n" to solve xstatus command, so only "OK" in a single line will be matched, and not also OK along with other text in the same line.

Thanks,
Ahmad

**Comment by ahmadbarrin** [comment]
@ktbyers 

I've uploaded lastest "cisco_tp_tcce" class on my branch : [https://github.com/ahmadbarrin/netmiko/blob/develop/netmiko/cisco/cisco_tp_tcce.py](https://github.com/ahmadbarrin/netmiko/blob/develop/netmiko/cisco/cisco_tp_tcce.py)

It's based on your last optimization.
I've just surrounded string expect_string with '\n\r' to get more occurate prompt parsing (`expect_string = r'\r\n(OK|ERROR|Command not recognized\.)\r\n')`
I've tested it on Cisco Telepresence Device SX10 with many different commands and it's working fine. This class works also for Cisco Expressway product, because it's the same shell format. This is easier to test with Cisco Expressway because it's a Cisco Virtual Machine, and SSH works without licence. You can download OVA image from here :  [https://software.cisco.com/download/release.html?mdfid=286255326&flowid=77866&softwareid=280886992&release=X8.9.1&relind=AVAILABLE&rellifecycle=&reltype=latest](https://software.cisco.com/download/release.html?mdfid=286255326&flowid=77866&softwareid=280886992&release=X8.9.1&relind=AVAILABLE&rellifecycle=&reltype=latest)

May you merge it for your next release ?

Regards,
Ahmad BARRIN

**Comment by ktbyers** [comment]
@ahmadbarrin Please submit a new pull request if you want to update the driver.

**Comment by pushamaku** [comment]
@ktbyers, @ahmadbarrin, 

Thank you both for your efforts with the Cisco TelePresence driver. I am currently trying to use it, however there is no output when I try to run a particular command: 

For example when I ran the command below with debug enabled:

```
net_connect.send_command('xPreferences outputmode xml')
```

gives:

```
...
Cisco Codec Release TC7.3.2.14ad7cc
SW Release Date: 2015-03-10
*r Login successful

OK


DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: xpreferences outputmode xml

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: xpreferences outputmode xml

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:

```
I have confirmed that running this command does't output OK via direct SSH, while running the command to set output mode to terminal works fine.

```
Cisco Codec Release TC7.3.2.14ad7cc
SW Release Date: 2015-03-10
*r Login successful

OK

help
         - User Commands -

help            xcommand        xconfiguration  xevent          xfeedback
xgetxml         xdocument       xhistory        xpreferences    xstatus
bye             echo            log             systemtools
OK
xpreferences outputmode xml
xpreferences outputmode terminal

OK
```
I know this is a device level issue, but can you suggest a workaround for the 'expect_string' in the driver?

Thank you

**Comment by ahmadbarrin** [comment]
@pushamaku 
Thanks for using our new drivers. Personally I never used this command before. I've read related Cisco documentation and it seems it will convert output from normal mode to XML. But my question is on subsequent commands, will "OK" will still appear after XML output ? I'm afraid this command will change all output on subsequent commands and make our driver fail. that's why I'm asking.
I don't have a test Telepresence endpoint at the moment and for a few weeks probably so I cannot test.
May  you please give me a longer Manual SSH log file ? In need this log with some commands before and and the same command after "xpreferences outputmode xml" so we can compare how this command affect next commands output ?

Thanks
Ahmad

**Comment by pushamaku** [comment]
Hi @ahmadbarrin 

Yes, my use case is to gather stats across a many endpoints, so parsing the data with XML is much easier.

Please see below for more manual commands:

```
Cisco Codec Release TC7.3.2.14ad7cc
SW Release Date: 2015-03-10
*r Login successful

OK

xpreferences outputmode xml
xpreferences outputmode xml
xpreferences outputmode xml
xpreferences outputmode terminal

OK
xpreferences outputmode
xpreferences usage:
 xpreferences outputmode <terminal/xml>

OK
help
         - User Commands -

help            xcommand        xconfiguration  xevent          xfeedback
xgetxml         xdocument       xhistory        xpreferences    xstatus
bye             echo            log             systemtools
OK
xpreferences outputmode xml
xstatus peripherals
<XmlDoc resultId="">
<Status>
  <Peripherals item="1">
    <ConnectedDevice item="1002">
      <HardwareInfo item="1">102310-1</HardwareInfo>
      <ID item="1">88:43:e1:c6:75:01</ID>
      <Name item="1">Cisco TelePresence Touch</Name>
      <SoftwareInfo item="1">TI7.3.2.14ad7cc</SoftwareInfo>
      <Status item="1">Connected</Status>
      <Type item="1">TouchPanel</Type>
      <UpgradeStatus item="1">None</UpgradeStatus>
    </ConnectedDevice>
  </Peripherals>
</Status>
</XmlDoc>
xpreferences outputmode terminal

OK
xstatus peripherals
*s Peripherals ConnectedDevice 1002 HardwareInfo: "102310-1"
*s Peripherals ConnectedDevice 1002 ID: "88:43:e1:c6:75:01"
*s Peripherals ConnectedDevice 1002 Name: "Cisco TelePresence Touch"
*s Peripherals ConnectedDevice 1002 SoftwareInfo: "TI7.3.2.14ad7cc"
*s Peripherals ConnectedDevice 1002 Status: Connected
*s Peripherals ConnectedDevice 1002 Type: TouchPanel
*s Peripherals ConnectedDevice 1002 UpgradeStatus: None
** end

OK

```

It seems that the endpoint will not terminate with OK, when XML mode is used. 

Thanks again!

**Comment by ahmadbarrin** [comment]
Hi @pushamaku 

before 
`kwargs.setdefault('expect_string', expect_string)`

```
command_string = kwargs.get('command_string')
if command_string == 'xpreferences outputmode xml':
expect_string = r'\r\n(OK|ERROR|Command not recognized\.|)'
```

or if it doesn't work, lower max_loops so it will raise a exception faster, you can just ignore exception and continue sending more commands :
```
command_string = kwargs.get('command_string')
if command_string == 'xpreferences outputmode xml':
kwargs.setdefault('max_loops', 10)
```


Alternatively for my opinion parsing in normal mode should not be so difficult. It's better to do it this way because if you want to change config (xcommand) input must be normal mode and XML won't be reconized. A single parsing function can support all possible command output. To parse in normal mode, the idea is to use nested disctionary (see http://stackoverflow.com/a/16333441 as a example).

- first loop : read line one by one (lines = re.split("\n", output))
- parse each line with regex pattern "^(.*:) (.*)$", matches=re.search(r"^(.*:) (.*)$", line);
- matches.group(0) will be path, and matches.group(1) will be value 
- split path using space, remove first item ("*s" in your example)
- second loop : create empty dict, for each key, if key not in dict exist create it, use loop on key to create nested dict, when all key as been reached, put value in this location

Regards,
Ahmad

**Comment by ktbyers** [comment]
@pushamaku 

You might be able to do something like this:

```
net_connect.send_command_timing("xpreferences outputmode xml")
output = net_connect.send_command_timing("xstatus peripherals")
net_connect.send_command_timing("xpreferences outputmode terminal")
```

Since the XML mode messes up the trailing character we are looking for...it might be easier to do entirely based on response timing.

**Comment by pushamaku** [comment]
@ahmadbarrin 

Thank you for the tips, and all worthy of consideration, but to save time I opted for @ktbyers suggestion and it worked nicely without any modifications to the driver:

```
Cisco Codec Release TC7.3.2.14ad7cc
SW Release Date: 2015-03-10
*r Login successful

OK


DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: xpreferences outputmode xml

DEBUG:netmiko:read_channel: xpreferences outputmode xml

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: xStatus Peripherals

DEBUG:netmiko:read_channel: xStatus Peripherals
<XmlDoc resultId="">
<Status>
  <Peripherals item="1">
    <ConnectedDevice item="1002">
      <HardwareInfo item="1">102310-1</HardwareInfo>
      <ID item="1">88:43:e1:c6:79:0b</ID>
      <Name item="1">Cisco TelePresence Touch</Name>
      <SoftwareInfo item="1">TI7.3.2.14ad7cc</SoftwareInfo>
      <Status item="1">Connected</Status>
      <Type item="1">TouchPanel</Type>
      <UpgradeStatus item="1">None</UpgradeStatus>
    </ConnectedDevice>
  </Peripherals>
</Status>
</XmlDoc>

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: xpreferences outputmode terminal

DEBUG:netmiko:read_channel: xpreferences outputmode terminal

OK

DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:
output: <XmlDoc resultId="">
<Status>
  <Peripherals item="1">
    <ConnectedDevice item="1002">
      <HardwareInfo item="1">102310-1</HardwareInfo>
      <ID item="1">88:43:e1:c6:79:0b</ID>
      <Name item="1">Cisco TelePresence Touch</Name>
      <SoftwareInfo item="1">TI7.3.2.14ad7cc</SoftwareInfo>
      <Status item="1">Connected</Status>
      <Type item="1">TouchPanel</Type>
      <UpgradeStatus item="1">None</UpgradeStatus>
    </ConnectedDevice>
  </Peripherals>
</Status>
</XmlDoc>




DEBUG:paramiko.transport:EOF in transport thread

```

Thanks guys! netmiko is great! 👍

**Comment by ahmadbarrin** [comment]
@pushamaku 
Good news problem is solved ! I'm pleased we've received usage feedback from you on our new driver. Good luck on your project.

**Pull request merged**
