### PR TITLE
Issue with HP Comware Switches

### PR DESCRIPTION
**Pull request by lamiskin**
Start of the prompt in my tested starts with "<".

Included test for this - as it was failing previously.

Also formats were referencing non existing variables.

### CODE REVIEW

**Comment by ktbyers** [comment]
Can you send me the SSH output of what you are referring to on "<".

**Comment by lamiskin** [comment]
After logging in I get the following prompt before entering any commands:
"<ste1-as01>"

"ste1-as01" is of course the host name.

I am not sure if this is expected or not - I don't often deal with HP switches.

**Comment by lamiskin** [comment]
Forgot to mention the software version number of the HP Switch:
H3C Comware Platform Software
Comware Software, Version 5.20, Release 1211

**Comment by ktbyers** [comment]
I think GitHub markdown might have hid the prompt name above? Can you you re-post and escape the '>' and '<' characters?

**Comment by lamiskin** [comment]
`<ste1-as01>`

**Comment by ktbyers** [comment]
Okay, I see the issue and manually fixed. I fixed it in a slightly different way.

**Pull request closed without merging**
