### PR TITLE
Pica8 Driver

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
FYI @packetshooter (I just fixed the Python black issue here).

**Comment by ktbyers** [comment]
@packetshooter Is this good to go from your perspective?

**Comment by packetshooter** [comment]
I have not had time to circle back to this in the last 3 weeks, I have found issues when using the send_command I only get the the first x amount of lines before netmiko thinks the output is done. I have attempted to add global delay multiplier with send_command which has been mostly successful.

**Comment by ktbyers** [comment]
Okay, I will leave it here pending fixing the pending issues with send_command.

**Comment by packetshooter** [comment]
The commit function is working cleanly now, i'll start running the tests tomorrow and see how it does.

**Comment by packetshooter** [comment]
Update:
Show and config unit tests are 100%, but I am still working through the commit unit tests

```
<omitted>$ pytest -q test_netmiko_show.py --test_device pica8
.....sss......                                                                                                                                       [100%]
================================================================= short test summary info ==================================================================
SKIPPED [1] /Users/<omitted>/code/netmiko/netmiko/tests/test_netmiko_show.py:75: <Skipped instance>
SKIPPED [1] /Users/<omitted>/code/netmiko/netmiko/tests/test_netmiko_show.py:97: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /Users/<omitted>/code/netmiko/netmiko/tests/test_netmiko_show.py:123: Genie not supported on this platform
11 passed, 3 skipped in 40.10 seconds

<omitted>$ pytest -q test_netmiko_config.py --test_device pica8
......                                                                                                                                               [100%]
6 passed in 42.48 seconds

```

**Comment by ktbyers** [comment]
Okay, just let me know when the PR is ready for review.

**Comment by packetshooter** [comment]
Automated test
`096la-hungt210:tests ericvilleneuve$ pytest -q test_netmiko_commit.py --test_device pica8
...FFF..s......                                                                                                                                      [100%]
========================================================================= FAILURES =========================================================================
___________________________________________________________________ test_commit_confirm ____________________________________________________________________

net_connect = <netmiko.pica8.pica8.pica8SSH object at 0x10e91c1d0>
commands = {'basic': 'show vlan-interface brief', 'commit_verification': 'commit check', 'config': ['set system hostname "test-sw"'], 'config_verification': 'show | display set | match test-sw', ...}
expected_responses = {'base_prompt': 'imcservice@108-SW-Core', 'commit_comment': 'Commit OK.', 'enable_prompt': 'imcservice@108-SW-Core#', 'interface_ip': '10.96.255.1', ...}

    def test_commit_confirm(net_connect, commands, expected_responses):
        """
        Test confirm with confirm
        """
        # Setup the initial config state
        config_commands, support_commit, config_verify = setup_initial_state(
            net_connect, commands, expected_responses
        )
    
        # Perform commit-confirm test
        net_connect.send_config_set(config_commands)
        if net_connect.device_type == "cisco_xr":
            net_connect.commit(confirm=True, confirm_delay=60)
        else:
>           net_connect.commit(confirm=True)

test_netmiko_commit.py:130: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <netmiko.pica8.pica8.pica8SSH object at 0x10e91c1d0>, confirm = True, confirm_delay = None, check = False, comment = '', and_quit = False
delay_factor = 1

    def commit(self, confirm=False, confirm_delay=None, check=False, comment='',
               and_quit=False, delay_factor=1):
        """
        Commit the candidate configuration.
    
        Commit the entered configuration. Raise an error and return the failure
        if the commit fails.
    
        Automatically enters configuration mode
    
        default:
            command_string = commit
        check and (confirm or confirm_dely or comment):
            Exception
        confirm_delay and no confirm:
            Exception
        confirm:
            confirm_delay option
            comment option
            command_string = commit confirmed or commit confirmed <confirm_delay>
        check:
            command_string = commit check
    
        """
        delay_factor = self.select_delay_factor(delay_factor)
    
        if check and (confirm or confirm_delay or comment):
            raise ValueError("Invalid arguments supplied with commit check")
    
        if confirm_delay and not confirm:
            raise ValueError("Invalid arguments supplied to commit method both confirm and check")
    
        # Select proper command string based on arguments provided
        command_string = 'commit'
        commit_marker = 'Commit OK.'
        if check:
            command_string = 'commit check'
            commit_marker = 'Commit check OK'
        elif confirm == True:
            if confirm_delay:
                command_string = 'commit confirmed ' + str(confirm_delay)
            else:
                command_string = 'commit confirmed'
            commit_marker = 'Will be automatically rolled back in'
    
    
        # Enter config mode (if necessary)
        output = self.config_mode()
        # and_quit will get out of config mode on commit
        if and_quit:
            prompt = self.base_prompt
            output += self.send_command_expect(command_string, expect_string=prompt,
                                               strip_prompt=False,
                                               strip_command=False, delay_factor=delay_factor)
        else:
            output += self.send_command_expect(command_string, strip_prompt=False,
                                               strip_command=False, delay_factor=delay_factor)
    
        # Commit checking is odd due to Pica8 having new line and prompt echo'ed back before commit ok statement
        print('**********')
        pprint(output)
        print('**********')
        commit_check_pica8 = False
        for x in output.split('\n'):
            if commit_marker in x:
                commit_check_pica8 = True
        if commit_check_pica8 != True:
>               raise ValueError(f"Commit failed with the following errors:\n\n{output}")
E               ValueError: Commit failed with the following errors:
E               
E               
E               imcservice@test-sw# commit confirmed
E               Commit OK.

../netmiko/pica8/pica8.py:161: ValueError
------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------
**********
'\nimcservice@test-sw# commit\nCommit OK.\n'
**********
**********
'\nimcservice@test-sw# commit confirmed\nCommit OK.\n'
**********
____________________________________________________________________ test_confirm_delay ____________________________________________________________________

net_connect = <netmiko.pica8.pica8.pica8SSH object at 0x10e91c1d0>
commands = {'basic': 'show vlan-interface brief', 'commit_verification': 'commit check', 'config': ['set system hostname "test-sw"'], 'config_verification': 'show | display set | match test-sw', ...}
expected_responses = {'base_prompt': 'imcservice@108-SW-Core', 'commit_comment': 'Commit OK.', 'enable_prompt': 'imcservice@108-SW-Core#', 'interface_ip': '10.96.255.1', ...}

    def test_confirm_delay(net_connect, commands, expected_responses):
        """
        Test commit with confirm and non-default delay
        """
        # Setup the initial config state
        config_commands, support_commit, config_verify = setup_initial_state(
            net_connect, commands, expected_responses
        )
    
        # Perform commit-confirm test
        net_connect.send_config_set(config_commands)
        if net_connect.device_type in ["cisco_xr", "pica8"]:
>           net_connect.commit(confirm=True, confirm_delay=60)

test_netmiko_commit.py:152: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <netmiko.pica8.pica8.pica8SSH object at 0x10e91c1d0>, confirm = True, confirm_delay = 60, check = False, comment = '', and_quit = False
delay_factor = 1

    def commit(self, confirm=False, confirm_delay=None, check=False, comment='',
               and_quit=False, delay_factor=1):
        """
        Commit the candidate configuration.
    
        Commit the entered configuration. Raise an error and return the failure
        if the commit fails.
    
        Automatically enters configuration mode
    
        default:
            command_string = commit
        check and (confirm or confirm_dely or comment):
            Exception
        confirm_delay and no confirm:
            Exception
        confirm:
            confirm_delay option
            comment option
            command_string = commit confirmed or commit confirmed <confirm_delay>
        check:
            command_string = commit check
    
        """
        delay_factor = self.select_delay_factor(delay_factor)
    
        if check and (confirm or confirm_delay or comment):
            raise ValueError("Invalid arguments supplied with commit check")
    
        if confirm_delay and not confirm:
            raise ValueError("Invalid arguments supplied to commit method both confirm and check")
    
        # Select proper command string based on arguments provided
        command_string = 'commit'
        commit_marker = 'Commit OK.'
        if check:
            command_string = 'commit check'
            commit_marker = 'Commit check OK'
        elif confirm == True:
            if confirm_delay:
                command_string = 'commit confirmed ' + str(confirm_delay)
            else:
                command_string = 'commit confirmed'
            commit_marker = 'Will be automatically rolled back in'
    
    
        # Enter config mode (if necessary)
        output = self.config_mode()
        # and_quit will get out of config mode on commit
        if and_quit:
            prompt = self.base_prompt
            output += self.send_command_expect(command_string, expect_string=prompt,
                                               strip_prompt=False,
                                               strip_command=False, delay_factor=delay_factor)
        else:
            output += self.send_command_expect(command_string, strip_prompt=False,
                                               strip_command=False, delay_factor=delay_factor)
    
        # Commit checking is odd due to Pica8 having new line and prompt echo'ed back before commit ok statement
        print('**********')
        pprint(output)
        print('**********')
        commit_check_pica8 = False
        for x in output.split('\n'):
            if commit_marker in x:
                commit_check_pica8 = True
        if commit_check_pica8 != True:
>               raise ValueError(f"Commit failed with the following errors:\n\n{output}")
E               ValueError: Commit failed with the following errors:
E               
E               
E               imcservice@test-sw# commit confirmed 60
E               Commit OK.

../netmiko/pica8/pica8.py:161: ValueError
------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------
**********
'\nimcservice@test-sw# commit\nCommit OK.\nimcservice@test-sw# '
**********
**********
'\nimcservice@test-sw# commit confirmed 60\nCommit OK.\n'
**********
_____________________________________________________________________ test_no_confirm ______________________________________________________________________

net_connect = <netmiko.pica8.pica8.pica8SSH object at 0x10e91c1d0>
commands = {'basic': 'show vlan-interface brief', 'commit_verification': 'commit check', 'config': ['set system hostname "test-sw"'], 'config_verification': 'show | display set | match test-sw', ...}
expected_responses = {'base_prompt': 'imcservice@108-SW-Core', 'commit_comment': 'Commit OK.', 'enable_prompt': 'imcservice@108-SW-Core#', 'interface_ip': '10.96.255.1', ...}

    def test_no_confirm(net_connect, commands, expected_responses):
        """
        Perform commit-confirm, but don't confirm (verify rollback)
        """
        # Setup the initial config state
        config_commands, support_commit, config_verify = setup_initial_state(
            net_connect, commands, expected_responses
        )
    
        # Perform commit-confirm test
        net_connect.send_config_set(config_commands)
        if net_connect.device_type in ["cisco_xr","pica8"]:
>           net_connect.commit(confirm=True, confirm_delay=30)

test_netmiko_commit.py:176: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <netmiko.pica8.pica8.pica8SSH object at 0x10e91c1d0>, confirm = True, confirm_delay = 30, check = False, comment = '', and_quit = False
delay_factor = 1

    def commit(self, confirm=False, confirm_delay=None, check=False, comment='',
               and_quit=False, delay_factor=1):
        """
        Commit the candidate configuration.
    
        Commit the entered configuration. Raise an error and return the failure
        if the commit fails.
    
        Automatically enters configuration mode
    
        default:
            command_string = commit
        check and (confirm or confirm_dely or comment):
            Exception
        confirm_delay and no confirm:
            Exception
        confirm:
            confirm_delay option
            comment option
            command_string = commit confirmed or commit confirmed <confirm_delay>
        check:
            command_string = commit check
    
        """
        delay_factor = self.select_delay_factor(delay_factor)
    
        if check and (confirm or confirm_delay or comment):
            raise ValueError("Invalid arguments supplied with commit check")
    
        if confirm_delay and not confirm:
            raise ValueError("Invalid arguments supplied to commit method both confirm and check")
    
        # Select proper command string based on arguments provided
        command_string = 'commit'
        commit_marker = 'Commit OK.'
        if check:
            command_string = 'commit check'
            commit_marker = 'Commit check OK'
        elif confirm == True:
            if confirm_delay:
                command_string = 'commit confirmed ' + str(confirm_delay)
            else:
                command_string = 'commit confirmed'
            commit_marker = 'Will be automatically rolled back in'
    
    
        # Enter config mode (if necessary)
        output = self.config_mode()
        # and_quit will get out of config mode on commit
        if and_quit:
            prompt = self.base_prompt
            output += self.send_command_expect(command_string, expect_string=prompt,
                                               strip_prompt=False,
                                               strip_command=False, delay_factor=delay_factor)
        else:
            output += self.send_command_expect(command_string, strip_prompt=False,
                                               strip_command=False, delay_factor=delay_factor)
    
        # Commit checking is odd due to Pica8 having new line and prompt echo'ed back before commit ok statement
        print('**********')
        pprint(output)
        print('**********')
        commit_check_pica8 = False
        for x in output.split('\n'):
            if commit_marker in x:
                commit_check_pica8 = True
        if commit_check_pica8 != True:
>               raise ValueError(f"Commit failed with the following errors:\n\n{output}")
E               ValueError: Commit failed with the following errors:
E               
E               
E               imcservice@test-sw# commit confirmed 30
E               Commit OK.

../netmiko/pica8/pica8.py:161: ValueError
------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------
**********
'\nimcservice@test-sw# commit\nCommit OK.\nimcservice@test-sw# '
**********
**********
'\nimcservice@test-sw# commit confirmed 30\nCommit OK.\n'
**********
================================================================= short test summary info ==================================================================
SKIPPED [1] /Users/ericvilleneuve/code/netmiko/netmiko/tests/test_netmiko_commit.py:259: Commit with comment not supported on this platform
3 failed, 11 passed, 1 skipped in 88.74 seconds`

Via manual ssh
`evilleneuve@test-sw# commit confirmed
Will be automatically rolled back in 600 seconds unless confirmed by new commit.
Commit OK.`

**Comment by ktbyers** [comment]
I am going to close this as it looks like it was never fully implemented. If someone wants to resume working on this just let me know.

**Pull request closed without merging**
