### PR TITLE
Add FastIron to SSH Autodetect #1076

### PR DESCRIPTION
**Pull request by ipv6freely**
Adding another option to the SSH Autodetect. Unfortunately there's not much to go on for the old FastIron platform we have. Matching on "FGS" will get this particular model but there seemed to be nothing else I could find that would differentiate this from any other router.

### CODE REVIEW

**Comment by ipv6freely** [comment]
Here's the show version output:
```
SSH@SMPK232040-4#show ver
  SW: Version 04.3.01bT7e1 Copyright (c) 1996-2008 Foundry Networks, Inc.
      Compiled on Feb 14 2009 at 01:33:16 labeled as FGS04301b
      (2925256 bytes) from Primary FGS04301b.bin
      BootROM: Version 05.0.00T7e5 (FEv2)
  HW: Stackable FGS648P-POE
==========================================================================
STACKID 0: SL 1: FGS-48G 48-port Management Module + PoE
      Serial  #: CY42075077
      P-ASIC  0: type D804, rev 01
      P-ASIC  1: type D804, rev 01
==========================================================================
STACKID 0: SL 2: FGS-2XG 2-port 10G Module (2-XFP)
==========================================================================
  400 MHz Power PC processor 8245 (version 129/1014) 66 MHz bus
  512 KB boot flash memory
 8192 KB code flash memory
  128 MB DRAM
The system uptime is 653 days 23 hours 22 minutes 3 seconds
The system started at 13:33:45 Pacific Fri Apr 21 2017

The system : started=warm start   reloaded=by "reload"
```

I also tried show chassis and a few other things hoping to find something better, but this was the best I could find for this platform.

**Comment by ktbyers** [comment]
Okay, I think we need to have "Foundry" + "FGS" (in the search pattern, but might need to add Brocade and Extreme also given ownership changes).

I think FGS by itself is too generic and too short (i.e. might get false positives from it).

Adding @LindsayHill

**Comment by ipv6freely** [comment]
You guys need a diagram or flowchart or something. haha

Did FastIron ever have anything other than "Foundry" in their copyright line?

**Comment by LindsayHill** [comment]
> Did FastIron ever have anything other than "Foundry" in their copyright line?

Almost 100% certain that they have Brocade in more recent code, and Arris in the latest code. That FGS there is pretty ancient, running code compiled in 2009.

**Comment by ipv6freely** [comment]
Yea definitely ancient. Well, it would make sense to include "Foundry" + "FGS" for this, and if other people can come up with other things to match they can always submit a patch :)

**Comment by ipv6freely** [comment]
Here's another FastIron:
```SSH@SMPK232048-4#show ver

==========================================================================
Active Management CPU [Slot-9]:
  SW: Version 04.2.00cT3e1 Copyright (c) 1996-2008 Foundry Networks, Inc.
      Compiled on Jan 08 2009 at 18:22:55 labeled as SXS04200c
      (2934779 bytes) from Primary SXS04200c.bin
      BootROM: Version 04.0.00T3e5 (FEv2)
  HW: Chassis FastIron SX 800
      Serial  #: SA37075048
==========================================================================
Standby Management CPU [Slot-10]:
  SW: Version 04.2.00cT3e1 Copyright (c) 1996-2008 Foundry Networks, Inc.
      Compiled on Jan 08 2009 at 18:22:55 labeled as SXS04200c
      BootROM: Version 04.0.00T3e5 (FEv2)
==========================================================================
SL 1: SX-FI424C 24-port Gig Copper + PoE
      Serial  #: CY42073393
      P-ASIC  0: type 00D1, rev D2  subrev 00
      P-ASIC  1: type 00D1, rev D2  subrev 00
==========================================================================
SL 2: SX-FI424C 24-port Gig Copper + PoE
      Serial  #: CY43075902
      P-ASIC  2: type 00D1, rev D2  subrev 00
      P-ASIC  3: type 00D1, rev D2  subrev 00
==========================================================================
SL 3: SX-FI424C 24-port Gig Copper + PoE
      Serial  #: CY43075957
      P-ASIC  4: type 00D1, rev D2  subrev 00
      P-ASIC  5: type 00D1, rev D2  subrev 00
==========================================================================
SL 4: SX-FI424C 24-port Gig Copper + PoE
      Serial  #: CY42073361
      P-ASIC  6: type 00D1, rev D2  subrev 00
      P-ASIC  7: type 00D1, rev D2  subrev 00
==========================================================================
SL 5: SX-FI424C 24-port Gig Copper + PoE
      Serial  #: CY42073352
      P-ASIC  8: type 00D1, rev D2  subrev 00
      P-ASIC  9: type 00D1, rev D2  subrev 00
==========================================================================
SL 6: SX-FI424C 24-port Gig Copper + PoE
      Serial  #: CY42074321
      P-ASIC 10: type 00D1, rev D2  subrev 00
      P-ASIC 11: type 00D1, rev D2  subrev 00
==========================================================================
SL 7: SX-FI424F 24-port Gig Fiber
      Serial  #: CH35070589
      P-ASIC 12: type 00D1, rev D2  subrev 00
      P-ASIC 13: type 00D1, rev D2  subrev 00
==========================================================================
SL 8: SX-FI424F 24-port Gig Fiber
      Serial  #: CH33071107
      P-ASIC 14: type 00D1, rev D2  subrev 00
      P-ASIC 15: type 00D1, rev D2  subrev 00
==========================================================================
SL 9: SX-FI2XGMR4 2-port Management
      Serial  #: CH42071153
      P-ASIC 16: type 01D1, rev 00  subrev 00
      P-ASIC 17: type 01D1, rev 00  subrev 00
==========================================================================
SL 10: SX-FI2XGMR4 2-port Management
      Serial  #: CH42071177
      P-ASIC 18: type 01D1, rev 00  subrev 00
      P-ASIC 19: type 01D1, rev 00  subrev 00
==========================================================================
Active Management Module:
  660 MHz Power PC processor 8541 (version 32/0020) 66 MHz bus
  512 KB boot flash memory
16384 KB code flash memory
  512 MB DRAM
Standby Management Module:
  660 MHz Power PC processor 8541 (version 32/0020) 66 MHz bus
  512 KB boot flash memory
16384 KB code flash memory
  512 MB DRAM
The system uptime is 533 days 19 hours 3 minutes 0 seconds
The system started at 19:37:03 Pacific Sat Aug 19 2017

The system : started=cold start```

This one is significantly easier :)

**Comment by LindsayHill** [comment]
EoL GS & SX gear, all running code from 2009? You're doing a real archaeological dig there, huh? Still, looks like those things have got solid hardware under them to still be chugging along

**Comment by ipv6freely** [comment]
> EoL GS & SX gear, all running code from 2009? You're doing a real archaeological dig there, huh? Still, looks like those things have got solid hardware under them to still be chugging along

They want a full inventory of everything in our datacenter before we throw it all away. Makes no sense but that's the directive.

**Comment by ktbyers** [comment]
PR updated here:

https://github.com/ktbyers/netmiko/pull/1460

**Pull request closed without merging**
