### PR TITLE
Microtik driver

### PR DESCRIPTION
**Pull request by dBitech**
First run @ microtik driver,

```$ py.test -vvv test_netmiko_show.py --test_device mt
============================================================ test session starts =============================================================
platform freebsd12 -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0 -- /usr/local/bin/python3.6
cachedir: .pytest_cache
rootdir: ~/src/netmiko, inifile:
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                                                                       [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                          [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                       [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                  [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                  [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                          [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                         [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                        [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                  [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                         [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                          [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                           [100%]

========================================================= 12 passed in 22.72 seconds =========================================================```

### CODE REVIEW

**Comment by ktbyers** [comment]
@dBitech Can you also execute the config tests and post the output here?

```
py.test -v test_netmiko_config.py --test_device my_device
```

**Comment by dBitech** [comment]
```$ py.test -vvv test_netmiko_config.py --test_device mt
============================================================ test session starts =============================================================
platform freebsd12 -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0 -- /usr/local/bin/python3.6
cachedir: .pytest_cache
rootdir: /usr/home/darcy/src/netmiko-dbitech, inifile:
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                        [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                        [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                        [ 42%]
test_netmiko_config.py::test_exit_config_mode FAILED                                                                                   [ 57%]
test_netmiko_config.py::test_command_set FAILED                                                                                        [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                 [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                         [100%]

================================================================== FAILURES ==================================================================
___________________________________________________________ test_exit_config_mode ____________________________________________________________

net_connect = <netmiko.microtik.routeros_ssh.routerosSSH object at 0x8033a15f8>
commands = {'basic': '/ip address print', 'config': ['/system package unschedule ipv6'], 'config_verification': '/system package print where name="ipv6"', 'extended_output': '/interface print oid', ...}
expected_responses = {'base_prompt': '[admin@KLWNBC12RB01] ', 'config_prompt': '[admin@KLWNBC12RB01] >', 'enable_prompt': '[admin@KLWNBC12RB01] >', 'interface_ip': '0 D ', ...}

    def test_exit_config_mode(net_connect, commands, expected_responses):
        """
        Test exit config mode
        """
        net_connect.exit_config_mode()
>       assert net_connect.check_config_mode() == False
E       assert True == False
E         -True
E         +False

test_netmiko_config.py:41: AssertionError
______________________________________________________________ test_command_set ______________________________________________________________

net_connect = <netmiko.microtik.routeros_ssh.routerosSSH object at 0x8033a15f8>
commands = {'basic': '/ip address print', 'config': ['/system package unschedule ipv6'], 'config_verification': '/system package print where name="ipv6"', 'extended_output': '/interface print oid', ...}
expected_responses = {'base_prompt': '[admin@KLWNBC12RB01] ', 'config_prompt': '[admin@KLWNBC12RB01] >', 'enable_prompt': '[admin@KLWNBC12RB01] >', 'interface_ip': '0 D ', ...}

    def test_command_set(net_connect, commands, expected_responses):
        """Test sending configuration commands."""
        config_commands = commands["config"]
        support_commit = commands.get("support_commit")
        config_verify = commands["config_verification"]

        # Set to initial value and testing sending command as a string
        net_connect.send_config_set(config_commands[0])
        if support_commit:
            net_connect.commit()

        cmd_response = expected_responses.get("cmd_response_init")
        config_commands_output = net_connect.send_command(config_verify)
        print(config_verify)
        print(config_commands_output)
        if cmd_response:
            assert cmd_response in config_commands_output
        else:
>           assert config_commands[0] in config_commands_output
E           AssertionError: assert '/system package unschedule ipv6' in 'Flags: X - disabled \n #   NAME                    VERSION                    SCHEDULED              \n 0 X ipv6                    6.42.3                                            \n\n\n\n'

test_netmiko_config.py:62: AssertionError
------------------------------------------------------------ Captured stdout call ------------------------------------------------------------
Flags: X - disabled
 #   NAME                    VERSION                    SCHEDULED
 0 X ipv6                    6.42.3




[admin@KLWNBC12RB01] >
[admin@KLWNBC12RB01] >
/system package print where name="ipv6"
Flags: X - disabled
 #   NAME                    VERSION                    SCHEDULED
 0 X ipv6                    6.42.3




===================================================== 2 failed, 5 passed in 9.63 seconds =====================================================
[darcy@quad ~/src/netmiko-dbitech/tests]$ py.test -v test_netmiko_config.py --test_device mt
============================================================ test session starts =============================================================
platform freebsd12 -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0 -- /usr/local/bin/python3.6
cachedir: .pytest_cache
rootdir: /usr/home/darcy/src/netmiko-dbitech, inifile:
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                        [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                        [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                        [ 42%]
test_netmiko_config.py::test_exit_config_mode FAILED                                                                                   [ 57%]
test_netmiko_config.py::test_command_set FAILED                                                                                        [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                 [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                         [100%]

================================================================== FAILURES ==================================================================
___________________________________________________________ test_exit_config_mode ____________________________________________________________

net_connect = <netmiko.microtik.routeros_ssh.routerosSSH object at 0x8033a69b0>
commands = {'basic': '/ip address print', 'config': ['/system package unschedule ipv6'], 'config_verification': '/system package print where name="ipv6"', 'extended_output': '/interface print oid', ...}
expected_responses = {'base_prompt': '[admin@KLWNBC12RB01] ', 'config_prompt': '[admin@KLWNBC12RB01] >', 'enable_prompt': '[admin@KLWNBC12RB01] >', 'interface_ip': '0 D ', ...}

    def test_exit_config_mode(net_connect, commands, expected_responses):
        """
        Test exit config mode
        """
        net_connect.exit_config_mode()
>       assert net_connect.check_config_mode() == False
E       assert True == False
E         -True
E         +False

test_netmiko_config.py:41: AssertionError
______________________________________________________________ test_command_set ______________________________________________________________

net_connect = <netmiko.microtik.routeros_ssh.routerosSSH object at 0x8033a69b0>
commands = {'basic': '/ip address print', 'config': ['/system package unschedule ipv6'], 'config_verification': '/system package print where name="ipv6"', 'extended_output': '/interface print oid', ...}
expected_responses = {'base_prompt': '[admin@KLWNBC12RB01] ', 'config_prompt': '[admin@KLWNBC12RB01] >', 'enable_prompt': '[admin@KLWNBC12RB01] >', 'interface_ip': '0 D ', ...}

    def test_command_set(net_connect, commands, expected_responses):
        """Test sending configuration commands."""
        config_commands = commands["config"]
        support_commit = commands.get("support_commit")
        config_verify = commands["config_verification"]

        # Set to initial value and testing sending command as a string
        net_connect.send_config_set(config_commands[0])
        if support_commit:
            net_connect.commit()

        cmd_response = expected_responses.get("cmd_response_init")
        config_commands_output = net_connect.send_command(config_verify)
        print(config_verify)
        print(config_commands_output)
        if cmd_response:
            assert cmd_response in config_commands_output
        else:
>           assert config_commands[0] in config_commands_output
E           AssertionError: assert '/system package unschedule ipv6' in 'Flags: X - disabled \n #   NAME                    VERSION                    SCHEDULED              \n 0 X ipv6                    6.42.3                                            \n\n\n\n'

test_netmiko_config.py:62: AssertionError
------------------------------------------------------------ Captured stdout call ------------------------------------------------------------
Flags: X - disabled
 #   NAME                    VERSION                    SCHEDULED
 0 X ipv6                    6.42.3




[admin@KLWNBC12RB01] >
[admin@KLWNBC12RB01] >
/system package print where name="ipv6"
Flags: X - disabled
 #   NAME                    VERSION                    SCHEDULED
 0 X ipv6                    6.42.3




===================================================== 2 failed, 5 passed in 9.52 seconds =====================================================```

**Comment by dBitech** [comment]
Tests now all pass clean;

```
============================================================ test session starts =============================================================
platform freebsd12 -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0 -- /usr/local/bin/python3.6
cachedir: .pytest_cache
rootdir: /usr/home/darcy/src/netmiko-dbitech, inifile:
plugins: pylama-7.7.1
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                                                                       [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                          [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                       [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                  [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                  [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                          [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                         [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                        [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                  [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                         [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                          [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                           [100%]

========================================================= 12 passed in 23.02 seconds =========================================================
============================================================ test session starts =============================================================
platform freebsd12 -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0 -- /usr/local/bin/python3.6
cachedir: .pytest_cache
rootdir: /usr/home/darcy/src/netmiko-dbitech, inifile:
plugins: pylama-7.7.1
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                        [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                        [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                        [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                   [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                        [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                 [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                         [100%]

========================================================== 7 passed in 8.11 seconds ==========================================================
```

**Comment by carlniger** [comment]
Closing. See #1203 

Thank you @dBitech !

**Pull request closed without merging**
