### PR TITLE
substitute ESC[(\d)L with return characters for Aruba/ProCurve switches

### PR DESCRIPTION
**Pull request by brasswood**
Aruba and HP ProCurve switches appear to use this control sequence to print newlines.
This allows netmiko to handle it properly.

This is somewhat hacky because without a real VT100 emulator, we don't know where the
cursor is positioned and consequently where the newline should actually go. So this may or may
not cause issues on other switches using VT100 codes.

I changed the variable name code_form_feed to code_insert_line.
See https://www.xfree86.org/current/ctlseqs.html#VT100%20Mode

### CODE REVIEW

**Comment by brasswood** [comment]
#1699

**Comment by ktbyers** [comment]
@brasswood Can you expand on the reasoning in your PR? In almost all cases ProCurve's have a normal <enter>, why do they only rarely do this?

**Comment by brasswood** [comment]
@ktbyers When just pressing enter at the command prompt, our Aruba 2930s and 3810s consistently do not print newline characters or `ESC E`. Here is the unfiltered result from the switch from just pressing enter three times at the prompt:
```
\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;16H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HCOMP-ES-2E-01# \x1b[1000;1H\x1b[232;16H\x1b[1000;1H\x1b[?25h\x1b[1000;16H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;16H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HCOMP-ES-2E-01# \x1b[1000;1H\x1b[232;16H\x1b[1000;1H\x1b[?25h\x1b[1000;16H\x1b[1;0H\x1b[1M\x1b[232;1H\x1b[1L\x1b[1000;16H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[1;232r\x1b[1000;1H\x1b[232;1H\x1b[2K\x1b[1000;1H\x1b[?25h\x1b[1000;1H\x1b[232;1HCOMP-ES-2E-01# \x1b[1000;1H\x1b[232;16H\x1b[1000;1H\x1b[?25h\x1b[1000;16H
```
No `\n`, `\r`, or `ESC E`. Instead, it is using the control sequences to clear the line at the top of the screen, then insert a new line at the bottom of the screen (using `ESC[1M` and `ESC[1L` respectively).

While I don't have a ProCurve switch, I assume that they all behave this way too. Firstly, the fact that the `HPProcurveBase` class works almost perfectly on ArubaOS Switch (the code in that base class precisely expresses the behavior of our Aruba switches), combined with the fact that HPE has acquired Aruba Networks makes me believe that ArubaOS Switch is based on the ProCurve operating system (see #1810). 

Secondly, the @sliddjur at #1699 had this error:
>```
>OSError: Search pattern never detected in send_command_expect: 65432p\-swi004\-new\-office\-2etg\#\ 65432p\-swi004\-new\-office\-2etg\#
>```

His switch's raw output:
>```
>DEBUG:netmiko:repr = '\x1b[1;0H\x1b[1M\x1b[24;1H\x1b[1L\x1b[24;32H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1H65432p-swi004-new-office-2etg# \x1b[24;1H\x1b[24;32H\x1b[24;1H\x1b[?25h\x1b[24;32H\x1b[1;0H\x1b[1M\x1b[24;1H\x1b[1L\x1b[24;32H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1H65432p-swi004-new-office-2etg# \x1b[24;1H\x1b[24;32H\x1b[24;1H\x1b[?25h\x1b[24;32H'
>```
Notice that this is also using `ESC[1M` and `ESC[1L` to create the newline on the terminal.

This is the exact issue that I was having, and telling netmiko to interpret `ESC[<n>L` as n newlines fixed it for me.

**Comment by ktbyers** [comment]
Yeah, I have a ProCurve in my lab and there has been a ProCurve driver in Netmiko for around 6 years and it doesn't behave this way in general (or else the entire ProCurve driver would break).

Also even in the referenced issue #1699 there are other newlines in the output and Netmiko would break much earlier so that isn't a sufficient explanation for 1699. By that I mean, there would be the question of why does it normally output <enters> and then in this one rare circumstance not?

Anyways let me look at it some more...

**Comment by ktbyers** [comment]
Okay, looking at it some more...I understand it a bit better. Let me research it some more.

**Comment by brasswood** [comment]
>Netmiko would break much earlier
As long as `find_prompt()` loops only once, the switch only prints one prompt, and there are no issues. This is usually the case.

Sometimes we don't receive the data until the second or third loop of `find_prompt()`, and the switch gives us 2 or 3 prompts. This is when problems arise, as netmiko sees no newlines to split the string around, so it thinks that the three prompts are one.

@ktbyers does your ProCurve behave similarly just when pressing enter at the command prompt? I am aware that in some contexts these switches also print newlines.

**Comment by ktbyers** [comment]
```
As long as find_prompt() loops only once, the switch only prints one prompt, and there are no issues. This is usually the case.
```

Assuming that is true, then you could also fix the issue by using `global_delay_factor`. Of course, you would potentially have an undesirable variability here when it sometimes fails.

It is a bit weird they would do this behavior in the hitting enter at a blank prompt, but not in a bunch of other contexts. But the ProCurves are weird devices so it wouldn't surprise me.

I generally run my test suite against my lab ProCurve on a reasonably regular behavior and haven't ever ran into the issue (as far as I am aware). But yeah, I could test it some more and see if I can reproduce this (I am not sure I will or whether I will just implement a variation of your fix).

I will probably implement some variation of your fix above as it doesn't really hurt things and is not all that different from the below which we are already doing here.

```
return re.sub(code_next_line, self.RETURN, output)
```


Thanks for all your research/work here...I was a bit skeptical this was a real thing, but now I understand it better and it makes sense.

**Comment by ktbyers** [comment]
Replacing with updated PR

**Pull request closed without merging**
