### PR TITLE
Fixes for issues #375 and #376. Telnet connection improvement.  EdgeCore switch support.

### PR DESCRIPTION
**Pull request by shamanu4**
Telnet connection improvement:

- login/password detection case insensitive, banners ignored (multiline)
- fix for switches that does not produce output for the first telnet connection read attempt

Fixes for issues #375 and #376 :

- replaced `check_string in output` with `output.endswith(check_string)` - check_string can be present in prompt and checks will always return True.
- replaced cehck_string for check_config_mode for cisco from `)#` to `config)#` - same reason as above.

EdgeCore support:

- Telnet connection class for EdgeCore ES series switches. (Maybe not only ES series)

### CODE REVIEW

**Comment by shamanu4** [comment]
Tests runs with no errors.
py.test -v test_netmiko_show.py --test_device cisco_ios
py.test -v test_netmiko_config.py --test_device cisco_ios
py.test -v test_netmiko_show.py --test_device cisco_telnet
py.test -v test_netmiko_config.py --test_device cisco_telnet
py.test -v test_netmiko_show.py --test_device edge_core_telnet
py.test -v test_netmiko_config.py --test_device edge_core_telnet

**Comment by ktbyers** [comment]
@shamanu4 First of all thanks for your contribution.

In general, you need to move almost all of these changes to the EdgeCore driver and not make changes in base_connection.py or in cisco_base_connection.py

1. I am pretty unlikely to accept new arguments to __init__ (i.e. protocol). Netmiko already has a way of determining protocol from device type. So I am not going to accept the add of `protocol`.

2. Don't change the telnet_login method in base_connection. If telnet_login doesn't work for EdgeCore than just overwrite the method in the EdgeCore driver.

3. Don't change the `check_config_mode` in cisco_base_connection. Cisco devices will do things like `config-if)#` so your change won't work (for Cisco devices).

4. Don't change names in ssh_dispatcher. I am very unlikely to accept them. Obviously, you need to add your new driver here, but minimize your changes just to what is needed to do this.

**Comment by shamanu4** [comment]
OK. I'll drop all not mandatory code for EdgeCore and will make new pull request. Packing several features in single pull request was a bad idea.

**Comment by shamanu4** [comment]
@ktbyers 
OK. I'll drop all not mandatory code for EdgeCore and will make new pull request. Packing several features in single pull request was a bad idea.

**Comment by shamanu4** [comment]
@ktbyers
OK. I'll drop all not mandatory code for EdgeCore and will make a new pull request. Packing several features in single pull request was a bad idea.

**Comment by ktbyers** [comment]
@shamanu4 No problem at all...obviously a lot of the code in `base_connection.py` and `cisco_base_connection.py` has been worked on and tested extensively so I am cautious about making significant changes to it.

**Pull request closed without merging**
