### PR TITLE
Invoke /bin/ls instead of ls to avoid custom alias or command path is…

### PR DESCRIPTION
**Pull request by jafingerhut**
…sues

### CODE REVIEW

**Comment by jafingerhut** [comment]
Thanks for developing and publishing netmiko.  Very handy open source tool similar to Cisco's pyATS.

I was trying it out to connect to and control some Linux systems via SSH, and found that because my .bashrc defined some aliases for the 'ls' command that used additional command line options that I like to have during interactive CLI use, this was interfering with netmiko's ability to parse the output of these 'ls' commands.  As a temporary local workaround, I have issued an 'unalias ls' command just after connecting in my test scripts, but it seems like the changes proposed in this PR, or something similar, would help make netmiko more robust to other developers who might do similar customizations to their 'ls' command.

**Comment by BenjaminHoegh** [comment]
Please make this customizable so you can change this after need, sometimes you will not have permission to use `/bin/ls` but can still use the `ls` command. This is currently giving me trouble and is quite annoying to have to change netmikos files directly

**Comment by ktbyers** [comment]
@BenjaminHoegh Can you provide a bit more detail on why `/bin/ls` doesn't work and your use-case/situation that is failing?

**Comment by BenjaminHoegh** [comment]
> @BenjaminHoegh Can you provide a bit more detail on why `/bin/ls` doesn't work and your use-case/situation that is failing?

Thanks for the quick response ❤️ 

Its the permissions settings on the target server I try there only allow me to use the `$ ls` command but not as `$ /bin/ls` this is someting I can't change as I do not have access to change the permissions on the server to my need.

**Comment by ktbyers** [comment]
What netmiko device_type are you using? I am assuming `linux`?

**Comment by BenjaminHoegh** [comment]
> What netmiko device_type are you using? I am assuming `linux`?

Linux yes :)

**Pull request merged**
