### PR TITLE
Save config tests

### PR DESCRIPTION
**Pull request by jcrotts**
Added tests for the save_config method in test_netmiko_config.py and added commands to the examples.
https://github.com/ktbyers/netmiko/pull/697

### CODE REVIEW

**Comment by ktbyers** [comment]
@jcrotts Nice...let me review.

**Comment by jcrotts** [comment]
@ktbyers 
Anything I need to change for this?

**Comment by ktbyers** [comment]
I still need to review it...just haven't got to it (so it is on me at this point).



Kirk

**Comment by jcrotts** [comment]
No worries!

**Comment by ktbyers** [comment]
@jcrotts I am going to remove the HP ProCurve changes from this. If you want these, please submit a separate PR for them.

**Pull request merged**
