### PR TITLE
Improve commit behavior on Nokia SR-OS

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@jtishey How about this PR? Does this fix your issue?

**Comment by jtishey** [comment]
@ktbyers   I think the `@` would always be in output since it's in the prompt where we send the commit cmd though, no?   It may not be necessary if you can just set `global_cmd_verify = False`.  I'll test it out in the morning and let you know for sure.

**Comment by ktbyers** [comment]
@jtishey Do you mean the prompt prior to commit?

I believe the output Netmiko reads should look like this (the prompt before the `commit` should already have been read by Netmiko:

```
commit
.
.(ex)[]
.A:admin@VSR#
```

**Comment by ktbyers** [comment]
Yeah, I have a pretty strong bias to not disabling cmd_verify so that wouldn't be a fix I would want to implement (unless there are no other options).

**Comment by jtishey** [comment]
I'm guessing global_cmd_verify isn't defined yet?   It works as long as i set dev.global_cmd_verify = True first.  Otherwise it returns nothing for the commit and then I can't exit_config_mode()

#### vSR Virtual Box
```
>>> dev.send_config_set(['configure port 1/1/c10 description "TEST121"'])                                                     
'edit-config exclusive\nINFO: CLI #2060: Entering exclusive configuration mode\nINFO: CLI #2061: Uncommitted changes are discarded on configuration mode exit\n\n(ex)[]\nA:user@vSR1# configure port 1/1/c10 description "TEST121"\n\n*(ex)[]\nA:user@vSR1# '
>>> 
>>> dev.commit()
''
>>> dev.exit_config_mode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/netmiko/netmiko/nokia/nokia_sros_ssh.py", line 95, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode
>>> dev.disconnect()
>>> 
```

  
 If I manually set the global_cmd_verify first - All Good


```
>>> dev.global_cmd_verify = True
>>> dev.send_config_set(['configure port 1/1/c10 description "TEST123"'])                            
'edit-config exclusive\nINFO: CLI #2060: Entering exclusive configuration mode\nINFO: CLI #2061: Uncommitted changes are discarded on configuration mode exit\n\n(ex)[]\nA:user@vSR1# configure port 1/1/c10 description "TEST123"\n\n*(ex)[]\nA:user@vSR1# '
>>> 
>>> 
>>> dev.commit()
'exit all\r\n\r\n*(ex)[]\r\nA:user@vSR1# commit\r\n\r\n(ex)[]\r\nA:user@vSR1# '
>>> dev.exit_config_mode()
'exit all\r\n\r\n(ex)[]\r\nA:user@vSR1# quit-config\r\nINFO: CLI #2064: Exiting exclusive configuration mode\r\n\r\n[]\r\nA:user@vSR1# '
>>> dev.disconnect()
>>> 
```


Now I do get the same results on a physical chassis as well

#### 7750 SR7s 
```
>>> dev.send_config_set(['configure port 1/1/c22 description "RESERVED:null:pe01.nwhr01-us:xe-1/1/10:10GE:[WIN test231]"']) 
'edit-config exclusive\nINFO: CLI #2060: Entering exclusive configuration mode\nINFO: CLI #2061: Uncommitted changes are discarded on configuration mode exit\n\nFRI 17 APR 2020 13:30:12 UTC\n(ex)[]\nA:user@7750-SR7s# configure port 1/1/c22 description "RESERVED:null:pe01.nwhr01-us:xe-1/1/10:10GE:[WIN test231]"\n\nFRI 17 APR 2020 13:30:12 UTC\n*(ex)[]\nA:user@7750-SR7s# '
>>> 
>>> dev.commit()
''
>>> dev.exit_config_mode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/netmiko/netmiko/nokia/nokia_sros_ssh.py", line 95, in exit_config_mode
    raise ValueError("Failed to exit configuration mode")
ValueError: Failed to exit configuration mode
>>> dev.disconnect()
```


Again, if I manually set the global_cmd_verify first - All Good
```
>>> dev.global_cmd_verify = True
>>> dev.send_config_set(['configure port 1/1/c22 description "TESTING"']) 
'edit-config exclusive\nINFO: CLI #2060: Entering exclusive configuration mode\nINFO: CLI #2061: Uncommitted changes are discarded on configuration mode exit\n\nFRI 17 APR 2020 13:31:42 UTC\n(ex)[]\nA:user@7750-SR7s# configure port 1/1/c22 description "TESTING"\n\nFRI 17 APR 2020 13:31:42 UTC\n*(ex)[]\nA:user@7750-SR7s# '
>>> 
>>> dev.commit()
'exit all\r\n\r\nFRI 17 APR 2020 13:31:50 UTC\r\n*(ex)[]\r\nA:user@7750-SR7s# commit\r\n'
>>> dev.exit_config_mode()
'...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08...\x08\x08\x08   \x08\x08\x08.\x08 \x08\r\nFRI 17 APR 2020 13:32:04 UTC\r\n(ex)[]\r\nA:user@7750-SR7s# exit all\r\n\r\nFRI 17 APR 2020 13:32:04 UTC\r\n(ex)[]\r\nA:user@7750-SR7s# quit-config\r\nINFO: CLI #2064: Exiting exclusive configuration mode\r\n\r\nFRI 17 APR 2020 13:32:04 UTC\r\n[]\r\nA:user@7750-SR7s# '
```

**Comment by ktbyers** [comment]
@jtishey Okay, I made updates to hopefully fix the bug you were seeing with global_cmd_verify being set to None. 

Can you test it again?

**Comment by jtishey** [comment]
@ktbyers   the nokia_commit branch is now working as expected for SROS MD-CLI commits on the VM and physical router.  Thanks!

**Comment by ktbyers** [comment]
Whew... :-)

**Comment by hellt** [comment]
@jtishey @ktbyers 
what was the original issue? I thought we tested the commit in the original PR for MD-CLI and classic support

**Comment by jtishey** [comment]
@hellt #1663  fast commits on vSR returned the prompt in the first read_until_pattern call, so the second one would timeout

**Pull request merged**
