### PR TITLE
Updates on FTD driver

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@aSauerwein I made some updates here to make things more consistent with some Netmiko patterns. It would be good if you could regression test the test-suite against the updated code.

The *args, **kwargs change was so that there wouldn't be an error if someone passed in arguments to these methods (and so I wouldn't need to update the child class if there are new arguments at some point).

For `enable` I didn't want an exception here as some frameworks/libraries like Nornir and NAPALM might always call `enable` so it is better if that just silently passes as opposed to raising an exception.

**Comment by ktbyers** [comment]
I am going to go ahead and merge this and we can correct if necessary.

**Comment by aSauerwein** [comment]
everything except "send_command_timing" works. 
`====================================================== FAILURES ======================================================
______________________________________________ test_send_command_timing ______________________________________________

net_connect = <netmiko.cisco.cisco_ftd_ssh.CiscoFtdSSH object at 0x7f45c7cd32b0>
commands = {'basic': 'show interface ip brief', 'extended_output': 'show version', 'version': 'show version', 'wide_command': 'show access-list myverybiglongaccesslistthatdoesntexistandwherethisexceeds80characterssolinewrappingoccurs'}
expected_responses = {'base_prompt': '', 'enable_prompt': '>', 'interface_ip': '10.255.10.253', 'multiple_line_output': 'VDB version', ...}

    def test_send_command_timing(net_connect, commands, expected_responses):
        """Verify a command can be sent down the channel successfully."""
        time.sleep(1)
        net_connect.clear_buffer()
        # Force verification of command echo
        show_ip = net_connect.send_command_timing(commands["basic"], cmd_verify=True)
>       assert expected_responses["interface_ip"] in show_ip
E       AssertionError: assert '10.255.10.253' in ''`

**Comment by aSauerwein** [comment]
it looks like netmiko isn't executing the whole "show interface ip brief" command and that's probably because of a strange FTD behavior. 

When typing "show interface ip brief" the firewall blocks the input for aprox. 1s between "interface" and "ip" and "brief". 

was there a change on the send_command_timing method ?

**Comment by aSauerwein** [comment]
sorry, my bad. I just saw that you enabled fast_cli on default for ftd. Everything works fine when setting "fast_cli=False"
```
================================================ test session starts =================================================
platform linux -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/asauerwein/.virtualenvs/netmiko/bin/python
cachedir: .pytest_cache
rootdir: /home/asauerwein/Code/netmiko, configfile: setup.cfg
plugins: pylama-7.7.1
collected 21 items                                                                                                   

test_netmiko_show.py::test_disable_paging PASSED                                                               [  4%]
test_netmiko_show.py::test_terminal_width PASSED                                                               [  9%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                  [ 14%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                               [ 19%]
test_netmiko_show.py::test_send_command_timing PASSED                                                          [ 23%]
test_netmiko_show.py::test_send_command_timing_no_cmd_verify PASSED                                            [ 28%]
test_netmiko_show.py::test_send_command PASSED                                                                 [ 33%]
test_netmiko_show.py::test_send_command_no_cmd_verify PASSED                                                   [ 38%]
test_netmiko_show.py::test_cmd_verify_decorator PASSED                                                         [ 42%]
test_netmiko_show.py::test_send_command_global_cmd_verify PASSED                                               [ 47%]
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED                                                  [ 52%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED                                                        [ 57%]
test_netmiko_show.py::test_send_command_genie SKIPPED                                                          [ 61%]
test_netmiko_show.py::test_base_prompt PASSED                                                                  [ 66%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                 [ 71%]
test_netmiko_show.py::test_strip_command PASSED                                                                [ 76%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                          [ 80%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                 [ 85%]
test_netmiko_show.py::test_enable_mode PASSED                                                                  [ 90%]
test_netmiko_show.py::test_disconnect PASSED                                                                   [ 95%]
test_netmiko_show.py::test_disconnect_no_enable PASSED                                                         [100%]

============================================== short test summary info ===============================================
SKIPPED [1] test_netmiko_show.py:162: <Skipped instance>
SKIPPED [1] test_netmiko_show.py:183: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] test_netmiko_show.py:208: Genie not supported on this platform
====================================== 18 passed, 3 skipped in 86.60s (0:01:26) ======================================
```

**Comment by ktbyers** [comment]
Okay, let me set fast_cli back. I want to start moving to higher-performance settings, but it looks like the FTD didn't like that.

**Comment by ktbyers** [comment]
@aSauerwein Okay, fixed that send_command_timing issue here:

https://github.com/ktbyers/netmiko/pull/1919

**Pull request merged**
