### PR TITLE
Updated Yamaha Driver

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@Tachashi Any possibility you can re-test this updated PR? I made some updates to the PR.

**Comment by Tachashi** [comment]
@ktbyers Sorry for the late reply. I'll test the updated code.

**Comment by ktbyers** [comment]
@Tachashi Thanks...no worries at all.


Kirk

**Comment by ktbyers** [comment]
Just let me know if I broke anything here (with my changes). It definitely is possible. I made it such that it was most consistent with how Netmiko generally operations.

Kirk

**Comment by Tachashi** [comment]
@ktbyers 
I re-tested the updated code. Some functions didn't work so modified like below:

- set_base_prompt()
Yamaha routers have prompt like `>` or `#` by default. By configuring "console prompt [prompt]", the prompt becomes like `yamaha>` or `yamaha#`, so I deleted this function.

- exit_enable_mode()
When any changes have been made, the prompt `Save new configuration ? (Y/N)` appears before exiting the administrator mode. To be consistent with the other Netmiko behavior, ignore this by entering `N`. (instead, save config by save_config()).

```
yamaha1# ip route 10.1.4.0/24 gateway 10.1.1.1
yamaha1# exit
Save new configuration ? (Y/N)N
```
yamaha.py
```python
from netmiko.base_connection import BaseConnection
import time


class YamahaBase(BaseConnection):
    def session_preparation(self):
        """Prepare the session after the connection has been established."""
        self._test_channel_read(pattern=r"[>#]")
        self.set_base_prompt()
        self.disable_paging(command="console lines infinity")
        time.sleep(0.3 * self.global_delay_factor)
        self.clear_buffer()

    def check_enable_mode(self, check_string="#"):
        return super().check_enable_mode(check_string=check_string)

    def enable(self, cmd="administrator", pattern=r"Password", **kwargs):
        return super().enable(cmd=cmd, pattern=pattern, **kwargs)

    def exit_enable_mode(self, exit_command="exit"):
        """
        When any changes have been made, the prompt "Save new configuration ? (Y/N)" 
        appears before exiting. Ignore this by entering "N".
        """
        output = ""
        if self.check_enable_mode():
            self.write_channel(self.normalize_cmd(exit_command))
            time.sleep(1)
            output = self.read_channel()
            if "(Y/N)" in output:
                self.write_channel("N")
            output += self.read_until_prompt()
            if self.check_enable_mode():
                raise ValueError("Failed to exit enable mode.")
        return output

    def check_config_mode(self, check_string="#", pattern=""):
        """Checks if the device is in administrator mode or not."""
        return super().check_config_mode(check_string=check_string, pattern=pattern)

    def config_mode(self, config_command="administrator", pattern="ssword"):
        """Enter into administrator mode and configure device."""
        return self.enable()

    def exit_config_mode(self, exit_config="exit", pattern=">"):
        """
        No action taken. Call 'exit_enable_mode()' to explicitly exit Administration
        Level.
        """
        return ""

    def save_config(self, cmd="save", confirm=False, confirm_response=""):
        """Saves Config."""
        if confirm is True:
            raise ValueError("Yamaha does not support save_config confirmation.")
        self.enable()
        # Some devices are slow so match on trailing-prompt if you can
        return self.send_command(command_string=cmd)


class YamahaSSH(YamahaBase):
    """Yamaha SSH driver."""

    pass


class YamahaTelnet(YamahaBase):
    """Yamaha Telnet driver."""

    pass
```

Also, I reconsidered the autodetection method. As `show environment` doesn't include `Yamaha`, I choose `show copyright` instead (below).

ssh_autodetect.py
```python
    "yamaha": {
        "cmd": "show copyright",
        "search_patterns": [r"Yamaha Corporation"],
        "priority": 99,
        "dispatch": "_autodetect_std",
    },
```

```
yamaha1# show copyright
  Copyright (c) 1994-2018 Yamaha Corporation. All Rights Reserved.
  Copyright (c) 1995-2004 Jean-loup Gailly and Mark Adler.
  Copyright (c) 1998-2000 Tokyo Institute of Technology.
  Copyright (c) 2000 Japan Advanced Institute of Science and Technology, HOKURI
KU.
  Copyright (c) 2002 RSA Security Inc. All rights reserved.
  Copyright (c) 1997-2010 University of Cambridge. All rights reserved.
  Copyright (C) 1997 - 2002, Makoto Matsumoto and Takuji Nishimura, All rights
reserved.
  Copyright (c) 1995 Tatu Ylonen , Espoo, Finland All rights reserved.
  Copyright (c) 1998-2004 The OpenSSL Project.  All rights reserved.
  Copyright (C) 1995-1998 Eric Young (eay@cryptsoft.com) All rights reserved.
  Copyright (C) 1994-2012 Lua.org, PUC-Rio.
  Copyright (c) 1988-1992 Carnegie Mellon University All Rights Reserved.
  Copyright (C) 2004-2007 Diego Nehab. All rights reserved.
  Copyright (c) 2000-2007 Niels Provos <provos@citi.umich.edu>
  Copyright (c) 2007-2012 Niels Provos and Nick Mathewson
  Copyright (c) 2000 Dug Song <dugsong@monkey.org>
  Copyright (c) 1993 The Regents of the University of California.
  Copyright (c) 2002 Christopher Clark
  Copyright (c) 2006 Maxim Yegorushkin <maxim.yegorushkin@gmail.com>
  Copyright (c) 1996, David Mazieres <dm@uun.org>
  Copyright (c) 2008, Damien Miller <djm@openbsd.org>
  Copyright (C) 1999, 2000, 2002 Aladdin Enterprises.  All rights reserved.
```

**Comment by ktbyers** [comment]
@Tachashi Let me review...sorry, got side-tracked.

**Comment by ktbyers** [comment]
@Tachashi I updated the PR here to reflect the items you had above:

https://github.com/ktbyers/netmiko/pull/1778

Can you re-test that new PR?

**Comment by ktbyers** [comment]
This PR is superseded by:

https://github.com/ktbyers/netmiko/pull/1778

**Pull request closed without merging**
