### PR TITLE
introduces `raise_on_parsing_error` parameter to `send_command`

### PR DESCRIPTION
**Pull request by Kircheneer**
Allow exceptions from structured data parsers to bubble up to the callers of `send_command` and `send_command_timing`. This is useful for example in conjunction with `nornir_netmiko`, which currently can't fail tasks based on failed parsing, leading to successful tasks with garbage data.

### CODE REVIEW

**Comment by Kircheneer** [comment]
As discussed on Slack I have renamed the parameter and added an initial set of tests.

**Comment by Kircheneer** [comment]
Please approve CI workflow whenever possible. Thanks!

**Comment by tom0010** [comment]
Looks to fix https://github.com/ktbyers/netmiko/issues/3479

**Comment by ktbyers** [comment]
Superseded by https://github.com/ktbyers/netmiko/pull/3494

**Pull request closed without merging**
