### PR TITLE
New, promptless mode to collect device output

### PR DESCRIPTION
**Pull request by dmulyalin**
Would like to discuss promptless mode to read data for show commands output. 

# Why?

Existing methods have issues that proved to be solved using promptless mode, in particular:

- Read till pattern based on prompt not always reliable and Netmiko fails with `Search pattern never detected in send_command:` error, increasing timeouts usually makes problem less intense but does not solves it completely and might lead to increased execution time
- Using read timing mode seems prone to problems with either waiting for too long or finishing waiting too early, both resulting in behavior that would be good to avoid

# What?

Promptless mode allows to detect end of output from device without relying on timers or correct prompt matching (hence the name - promptless). This mode still uses pattern to decide if device finished emitting data, but that pattern is not Dependant on device's prompt.

# How?

promptless_mode_v0 1

Each reading cycle, data from device read as fast as possible until device either finishes or pose to prepare more data. Latter case detected and handled using read timeout timer and checking if new data received. To detect when device finishes producing output, algorithm sends two space character to device and checks in next read cycle if last line contains two additional spaces, concluding that end of output detected if so and continue cycling otherwise.

Overall its similar to how Humans interact with device prompt to verify that its still operational - try hitting space or type something in terminal to see if its appears on the screen.

Do not think I am the first one to came up with similar idea, however, this pull request includes code that was successfully tested with a number of drivers.

# Testing done

So far tested show commands output gathering for drivers:

- Cisco IOS
- Cisco NXOS
- Cisco IOSXR
- Juniper Junos
- Linux 

Was having aforementioned issues with Cisco NXOS driver - failing to detect pattern using `send_command` or skipping some output using `send_command_timing` methods, problem gone away once switched to promptless mode. Left it running in my lab for several days,  `send_command_ps` collected 198240 show commands outputs with no errors detected thus far.

As a result, decided to share my findings and discuss if promptless mode could be of the benefit to wider community.

Obviously, more testing required, but new mode could be introduced in codebase in a backward compatible way as it does not changes any other code, same could be true for removing it in the future in case it deemed useless.

Interesting byproduct of promptless mode is that device prompt can change while commands executed with end of output properly detected, i.e. this works fine in prompless mode:

```
from netmiko import ConnectHandler

cisco = { 
'device_type': 'cisco_ios', 
'host': '192.168.217.10', 
'username': 'cisco', 
'password': 'cisco', 
}  

net_connect_cisco = ConnectHandler(**cisco)

promptless_mode_output = net_connect_cisco.send_command_ps("""
show ip int brief
conf t
interface loopback 100
ip address 1.1.1.100 255.255.255.255
end
show ip int brief
wr
""")
 
print(promptless_mode_output)

# prints:
# lab-rt1#show ip int brief
# Interface                  IP-Address      OK? Method Status                Protoc
# Ethernet0/0.2000           192.168.217.10  YES NVRAM  up                    up
# lab-rt1#conf t
# Enter configuration commands, one per line.  End with CNTL/Z.
# lab-rt1(config)#interface loopback 100
# lab-rt1(config-if)#ip address 1.1.1.100 255.255.255.255
# lab-rt1(config-if)#end
# lab-rt1#show ip int brief
# Interface                  IP-Address      OK? Method Status                Protocol
# Ethernet0/0.2000           192.168.217.10  YES NVRAM  up                    up
# Loopback100                1.1.1.100       YES manual up                    up
# lab-rt1#wr
# Building configuration...
# [OK]
```

Another byproduct, is the fact that majority of devices use space char for pagination, as a result even with pagination turned on, promptless mode will collect full output from such devices.

### CODE REVIEW

**Comment by dmulyalin** [comment]
To anticipate concerns raised in https://github.com/ktbyers/netmiko/issues/1830:
- How would multi-line prompting work? I.E. things like confirm [y/n]? - multiline string could be sent `reboot\nY`
- how reliably I could count on cntl-a and cntl-k to work across 70+ - `send_command_ps` uses spaces to detect end of output, nothing special, nonetheless, found issue with Juniper  echoed `\x07` back instead of space - this can be handled as edge-cases, hence the emphasis that more test data required
- Why would it make it any faster at detecting the prompt compared to a regex pattern? - it would not, it makes it more reliable as per testing done for Cisco NXOS, without sacrificing any speed though
-  need to strip out all the prompttest messages and ANSI codes and backspaces from the output - not the case here, `send_prompt_ps` calls `self.clear_buffer()` to clean up previously sent spaces, so that they would not be collected by following command output

Also, would be good to see if `send_command_ps` helps with:
https://github.com/ktbyers/netmiko/issues/1852, https://github.com/ktbyers/netmiko/issues/1959, https://github.com/ktbyers/netmiko/issues/2021

Issue https://github.com/ktbyers/netmiko/issues/1996 addressed in `send_command_ps` as well by `read_timeout` timer

**Comment by ktbyers** [comment]
@dmulyalin I will need to spend some more time reviewing/looking at this.


Regards, Kirk

**Comment by dmulyalin** [comment]
Confirmed promptless mode working with cisco_ios_telnet driver, will keep updating if more testing results come through.

**Comment by dmulyalin** [comment]
Had to pull long output from IOS-XR devices, some of them happened to be relatively slow, used Netmiko normal mode, but it was producing `Search pattern never detected in send_command` errors for some devices. That issue gone after switching to prompt-less mode, however, noticed that not all output was collected, as end of output was mistakenly detected by ps mode probably due to IOS-XR buffer line was overflown with space characters sent to device for end of output detection, once that overflow happens, IO XR sends `^@` characters back, and in next cycle if no reply from device incoming, ps mode falsefully detects end of output. Fixed that issue by adding another edge-case handling.

Also, added initial sleep timer, as it seems to be useful in some cases like dealing with slow devices, e.g. if it takes about a second or two before device starts producing output data and we aware of that, we can set initial sleep to 2 seconds, to wait for 2 seconds after sending command before starting to collect output, that can help to save some cpu cycles and improve stability.

**Comment by ktbyers** [comment]
@dmulyalin Sorry for delayed response on this. I will try to respond on this in the next couple of weeks.


Regards, Kirk

**Comment by ktbyers** [comment]
@dmulyalin Sorry for delayed response on this.

I am pretty sure that I don't want to do this. My reasons being:
1. I am pretty sure from past experience that we would run into issues trying to use this solution. Devices end up doing a bunch of weird things to make the output more human readable.
2. I don't think I would want to do this just for the multiline prompting reason i.e. I view the embedding of "\n into a string as anti-pattern (so I would not want to encourage this).
3. This area is so core to Netmiko that is really hard to test and it has very big impact to Netmiko users. So I would never want to change the primary method `send_command` over to this pattern.

I am open to more discussions, however, on whether we should add this as an experimental method into Netmiko.



Regards,

Kirk

**Comment by dmulyalin** [comment]
@ktbyers thank you for looking at it.

Let me elaborate on the items you raised.

1. Agree - that is why more testing required, not even sure that it will work for all platforms, quiet sure it will need more edge cases handling. However, to my experience it proved working for major platforms such as Cisco IOS, XR, NXOS, Juniper and Linux.
2. Agree - multiline handling using "\n" is rather a by-product and not the core feature of this method, main functionality ps mode brings to the table is capability to gather (usually very long) output from devices where normal send_command and timing methods tend to fail from time to time, in other words, main feature is increased reliability
3. Agree - plan was to introduce promptless mode as additional, experimental method, it is not positioned to replace or modify any of existing methods of base connection class

Hope above helped to clarify some aspects of this pull request, what do you think?

**Comment by ktbyers** [comment]
Thanks for contributing this, but I definitely am against adding this. Consequently, I am going to go ahead and close it.

Regards, Kirk

**Comment by dmulyalin** [comment]
No worries, thank you @ktbyers for looking at it, appreciate your time and efforts.

For those who might be interested to use promptless mode, it was tested, implemented as a Netmiko based plugin for Nornir framework and distributed as part of Nornir-Salt package - [netmiko_send_commands_ps task](https://nornir-salt.readthedocs.io/en/latest/Tasks/netmiko_send_command_ps.html#netmiko-send-command-ps), in addition SaltStack Nornir based proxy minion can invoke promptless mode using `use_ps=True` argument with [nr.cli](https://salt-nornir.readthedocs.io/en/latest/Nornir%20Execution%20Module.html#nr-cli) execution module  function.

All the best to you all.

**Pull request closed without merging**
