### PR TITLE
Add pluribus vendor

### PR DESCRIPTION
**Pull request by mirceaulinic**

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Although pyPluribus will continue to exist and use netmiko (https://github.com/mirceaulinic/pypluribus/pull/17), napalm-pluribus will no longer need that third-party package and we'll switch everything to netmiko.

**Comment by ktbyers** [comment]
@mirceaulinic You will also need to add the new package to the `setup.py` file.

Does Pluribus software have a name? In general, the Netmiko naming convention is `vendor_platform_transport` where transport is almost always SSH (and rarely telnet).

Example, platforms for Cisco are `ios`, `nxos`, `iosrx`. Is there any similar Platform name for Pluribus?

**Comment by mirceaulinic** [comment]
Yeah, I see the direction. Unfortunately I'm not sure if Pluribus has any platform dependencies and how they are structured. Let me read more about that, but as far as I'm aware, they are the same on all their switches.

**Comment by ktbyers** [comment]
If there is no logical platform we can just leave it as pluribus.

**Comment by ktbyers** [comment]
One other thing we need to do here is also make sure it passes all of the relevant unit tests in:

```
test_netmiko_show.py
test_netmiko_config.py
```

See this document here:

```
https://github.com/ktbyers/netmiko/blob/develop/TESTING.md
```

Let me know if you need any assistance on this.

**Comment by mirceaulinic** [comment]
@ktbyers hrm.. I tried to understand something from the docs, but it is not obvious if their platforms are consistent or not. I have also asked around and I've been told they are all the same, so I think we can leave if as `pluribus`.

**Comment by mirceaulinic** [comment]
I have added the necessary config under the YAML files (https://github.com/ktbyers/netmiko/pull/408/commits/8b4d0bf0cd59a8965e540658f28b61568a71964d), here's the output:


```
$ py.test -v test_netmiko_show.py --test_device pluribus
============================================================================================================================ test session starts =============================================================================================================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /home/mircea/napalm/bin/python2
cachedir: ../.cache
rootdir: /home/mircea/netmiko, inifile:
plugins: pylama-7.3.3
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_expect PASSED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED

========================================================================================================================= 12 passed in 42.92 seconds =========================================================================================================================
```

and

```
$ py.test -v test_netmiko_show.py --test_device pluribus
============================================================================================================================ test session starts =============================================================================================================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /home/mircea/napalm/bin/python2
cachedir: ../.cache
rootdir: /home/mircea/netmiko, inifile:
plugins: pylama-7.3.3
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_expect PASSED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED

========================================================================================================================= 12 passed in 42.93 seconds =========================================================================================================================
```

**Comment by mirceaulinic** [comment]
Ooops I paste the wrong output above:

```
$ py.test -v test_netmiko_config.py --test_device pluribus
============================================================================================================================ test session starts =============================================================================================================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0 -- /home/mircea/napalm/bin/python2
cachedir: ../.cache
rootdir: /home/mircea/netmiko, inifile:
plugins: pylama-7.3.3
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode PASSED
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_command_set PASSED
test_netmiko_config.py::test_commands_from_file PASSED
test_netmiko_config.py::test_disconnect PASSED

========================================================================================================================= 7 passed in 29.19 seconds ==========================================================================================================================
```

**Comment by mirceaulinic** [comment]
Thanks to the tests, I pushed https://github.com/ktbyers/netmiko/pull/408/commits/1cacb11dbbd95a5c2df9bf14b97e9a0fbeb49cb5 and https://github.com/ktbyers/netmiko/pull/408/commits/2edd250072d57b28e4df436745604919a30c4199

**Pull request merged**
