### PR TITLE
support extreme WiNG

### PR DESCRIPTION
**Pull request by tknv**
Please check it when you have time and like it.
Thanks./

### CODE REVIEW

**Comment by tknv** [comment]
It was hard to commit delete trailing whitespace only, so tried to find some that not much effect code.

**Comment by ktbyers** [comment]
Thanks...yes, linters can be pretty pedantic. Will try to review shortly.

**Comment by ktbyers** [comment]
@tknv This looks fine.

Can you run the standard unit test suite against a WiNG device?

See this document:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by tknv** [comment]
Of course I shall try it. But maybe May 1-2 week.

**Comment by ktbyers** [comment]
Sounds good.

**Comment by tknv** [comment]
I done and pass all test(show/config). Then need to tune value(delay_factor=2 at self.set_base_prompt). I committed it. Please verify it.
And here with test code:
commands.yml:
```
extreme_wing:
  version: "show version"
  basic: "show ip interface brief"
  extended_output: "show running-config"   # requires paging to be disabled
  config:
    - "self"
    - ".."
    - "logging console debugging"
  config_verification: "show logging on WING01AP | grep Console"
```

responses.yml:
```
extreme_wing:
  base_prompt: WING01AP
  router_prompt : WING01AP>
  enable_prompt: WING01AP#
  interface_ip: 10.1.254.200
  version_banner: "AP8222 version 5.8.6.0-011R"
  multiple_line_output: "hostname WING01AP"
  cmd_response_init: 'Console logging: level debugging'
  cmd_response_final: 'Console logging: level debugging'
```

test_devices.yml:
```
extreme_wing:
  device_type: extreme_wing
  ip: 10.1.254.200
  username: admin
  password: extreme
```

**Pull request merged**
