### PR TITLE
Add Enable mode support to SROS.

### PR DESCRIPTION
**Pull request by ddfrathb**
Add the functionality to enter/exit enable mode using the SSH connection.

### CODE REVIEW

**Comment by ktbyers** [comment]
@ddfrathb Can you show me in the CLI what using `enable` and `disable` looks like?

Also is `enable` the `enable-admin` command? I was having trouble finding just `enable` in the SROS CLI guide?

**Comment by ddfrathb** [comment]
Yes, the enable-admin command is enable - sorry I actually forgot about this alias. it auto completes the command.  I realized later that the check_enable will actually fail on this and I was actually being authenticated as an escalated user - so I wasn't seeing the "Already enabled" error message. The disable also was my mistake.. apologies for the confusion as again it was checking admin state and "succeeding" as prompts are the same. I believe you would have to run "enable" and look for "Already enabled" in order to check, rather than relying on a prompt.

Fail:
*A:HOSTNAME# enable
Password:
MINOR: CLI Invalid password.
*A:HOSTNAME# 

Success:
*A:HOSTNAME# enable
Password:
*A:HOSTNAME# 

Already enabled:
*A:HOSTNAME# enable
MINOR: CLI Already in admin mode.

**Comment by ktbyers** [comment]
@ddfrathb Okay, do you want to update this PR, to reflect the correct behavior (for the `enable` method)?

Is there anything like a `show privilege` command that would tell us if we were in `enable` without having to check the `CLI Already in admin mode`.

**Comment by ktbyers** [comment]
Re-implemented in PR #681

**Pull request closed without merging**
