### PR TITLE
add netapp device support

### PR DESCRIPTION
**Pull request by koumiyata**
Adding support for NetApp Device
Tested with Version Ontap9.0

■config test
(venv)[tests]$ py.test -v test_netmiko_config.py --test_device  netapp_cdot
========================================================================= test session starts ==========================================================================
platform linux2 -- Python 2.7.12, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/koumiyata/netmiko-netapp/venv/bin/python2.7
cachedir: ../.cache
rootdir: /home/koumiyata/git/netmiko-maker/netmiko, inifile:
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode PASSED
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_command_set PASSED
test_netmiko_config.py::test_commands_from_file PASSED
test_netmiko_config.py::test_disconnect PASSED

======================================================================= 7 passed in 9.48 seconds =======================================================================

■show test
(venv)[tests]$ py.test -v test_netmiko_show.py --test_device  netapp_cdot
========================================================================= test session starts ==========================================================================
platform linux2 -- Python 2.7.12, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/koumiyata/netmiko-netapp/venv/bin/python2.7
cachedir: ../.cache
rootdir: /home/koumiyata/git/netmiko-maker/netmiko, inifile:
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_expect PASSED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED

====================================================================== 12 passed in 21.26 seconds ======================================================================

### CODE REVIEW

**Comment by ktbyers** [comment]
@koumiyata Can you show me what a configuration change from the CLI would look like for this device?

**Comment by ktbyers** [comment]
@koumiyata Can you show me what a configuration change from the CLI would look like for this device?

Also why do you need to go into diagnostics privilege? `set -privilege diagnostic -confirmations off`

**Comment by koumiyata** [comment]
@ktbyers 
Thank you for getting back to me.
NetApp has 3 privilege modes.(admin, advanced, diagnostic)
The diagnostic mode has the highest privilege.
For example, use diagnostic mode when changing settings related to the core of equipment.
In normal operation, it is scarcely used, but it was defined as netmiko's configure mode assuming special setting change.
Below is an example of CLI execution.
-------------------------------------------------------------------------------------------------------------------
(default privilege is admin)
cluster1::>  cluster identity modify -name cluster2

cluster2::> network port modify -node simulator -port e0b -up-admin false

Error: invalid argument "-up-admin"
cluster2::> set diagnostic -confirmations off

cluster2::*> network port modify -node simulator -port e0b -up-admin false

cluster2::*> set admin -confirmations off

cluster2::>

-------------------------------------------------------------------------------------------------------------------
Thank you.

**Comment by ktbyers** [comment]
@koumiyata thanks for response. I might not get to this until this weekend. But let me read through your response.

Kirk

**Comment by koumiyata** [comment]
NP! thanks for netmiko

**Comment by ktbyers** [comment]
@koumiyata This looks good. Will merge in (hopefully tonight).

**Comment by koumiyata** [comment]
@ktbyers Thanks for your reply. I'm looking forward to it!!

**Pull request merged**
