### PR TITLE
Rptetzloff calix b6 telnet

### PR DESCRIPTION
**Pull request by ktbyers**
.

### CODE REVIEW

**Comment by ktbyers** [comment]
@rptetzloff I made a few changes to what you did:

On the exit config mode

```
     def exit_config_mode(self, exit_config=None, pattern=''):
         """Exit from configuration mode."""
         if exit_config is None:
            exit_config = 'exit{}{}end'.format(self.RETURN, self.RETURN)
         return super(CalixB6SSH, self).exit_config_mode(exit_config=exit_config, pattern=pattern)
```

Is it sufficient to just type `end` to exit config mode or do you need to type `exit` also?

**Comment by ktbyers** [comment]
I also re-added the time.sleep to special_login_handler, these are generally needed.

Did you run the unit tests against a device using telnet? Can you post the test results here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by rptetzloff** [comment]
Hi Kirk,

Apologies. I should have clarified. The exit_config_mode override seems to be unnecessary. The default works just fine. In general, just 'end' should be sufficient, though there are cases in which an exit is necessary in advance. For example, in the following:

```
interface ethernet 42
 eps access subscriber
 mtu 1600
 ingress unknown-unicast rate limit 10
 ingress multicast rate limit 0
 ingress broadcast rate limit 10
 info info-1 x
 info info-2 y
 info info-3 z
 service 1
  access profile profile1
  override profile mac limit 3
  match vlan 4
  no shutdown
 exit
 service 2
  access profile profile2
  override profile mac limit 3
  match vlan 85
  no shutdown
 exit
 service 3
  access profile profile3
  override profile mac limit 16
  match vlan 6
  no shutdown
 exit
 no shutdown
exit
```

When configuring the interface level (or any other top or secondary level of config mode), end is sufficient, but when configuring a tertiary (or higher) level item, exiting to the secondary level is necessary... In other words it won't let you exit config mode until you exit the service configuration specifically.

**Comment by rptetzloff** [comment]
It worked without those time.sleep functions and seemed to speed up the login process a bit, but I suppose better to leave them in..

Test results for telnet and ssh:

`(netmiko) Raymonds-MacBook-Pro:tests rtetzloff$ py.test -v test_netmiko_show.py --test_device calix_b6_telnet
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0 -- /Users/rtetzloff/Python/Env/netmiko/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /Users/rtetzloff/Python/netmiko, inifile:
collected 12 items                                                                                                                                                                              

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                                          [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                             [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                          [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                     [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                                                                     [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                             [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                            [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                                           [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                     [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                            [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                             [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                                              [100%]

================================================================================== 12 passed in 46.28 seconds ===================================================================================
(netmiko) Raymonds-MacBook-Pro:tests rtetzloff$ py.test -v test_netmiko_config.py --test_device calix_b6_telnet
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0 -- /Users/rtetzloff/Python/Env/netmiko/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /Users/rtetzloff/Python/netmiko, inifile:
collected 7 items                                                                                                                                                                               

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                                           [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                                           [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                                           [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                                      [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                                                                           [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                                                                    [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                                            [100%]

=================================================================================== 7 passed in 56.79 seconds ===================================================================================
(netmiko) Raymonds-MacBook-Pro:tests rtetzloff$ py.test -v test_netmiko_show.py --test_device calix_b6_ssh
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0 -- /Users/rtetzloff/Python/Env/netmiko/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /Users/rtetzloff/Python/netmiko, inifile:
collected 12 items                                                                                                                                                                              

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                                          [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                             [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                          [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                     [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                                                                     [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                             [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                            [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                                           [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                     [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                            [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                             [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                                              [100%]

================================================================================== 12 passed in 42.41 seconds ===================================================================================
(netmiko) Raymonds-MacBook-Pro:tests rtetzloff$ py.test -v test_netmiko_config.py --test_device calix_b6_ssh
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0 -- /Users/rtetzloff/Python/Env/netmiko/bin/python3.5
cachedir: ../.pytest_cache
rootdir: /Users/rtetzloff/Python/netmiko, inifile:
collected 7 items                                                                                                                                                                               

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                                           [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                                           [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                                           [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                                      [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                                                                           [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                                                                    [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                                            [100%]

=================================================================================== 7 passed in 54.34 seconds ===================================================================================`

**Comment by ktbyers** [comment]
Okay, sounds good. Will remove the `exit_config_mode`.

Yes, the sleep makes sense because it just tried to read a few moments earlier and the needed data wasn't there. We can probably make the sleep smaller, but it usually makes sense to have some sleep there (so it doesn't just continually try to read when no data is present).

**Comment by rptetzloff** [comment]
Sure, makes sense. I think whatever is standardish should be fine then...

Thanks much!

**Pull request merged**
