### PR TITLE
Centec fixes

### PR DESCRIPTION
**Pull request by ktbyers**
Minor fixes to the Centec driver.

### CODE REVIEW

**Comment by ktbyers** [comment]
@feng891005 I made a couple of minor modifications here.

Can you test if `terminal width 511` works on these Centec devices? I couldn't really determine this from looking online.

The other change was the `config_mode` call now looked unnecessary as it now was identical to the parent class (note, I made a change to the parent class yesterday to use the canonical command of `configure terminal` instead of an abbreviated command).

**Comment by feng891005** [comment]
> @feng891005 I made a couple of minor modifications here.
> 
> Can you test if `terminal width 511` works on these Centec devices? I couldn't really determine this from looking online.
> 
> The other change was the `config_mode` call now looked unnecessary as it now was identical to the parent class (note, I made a change to the parent class yesterday to use the canonical command of `configure terminal` instead of an abbreviated command).

Hello ktbyers,
The Centec switch does not support the "terminal width" command，but the default terminal width is set to the maximum. So I deleted this command，

Sorry, I didn't pay attention to the changes to the "configure terminal" command. If you have already changed, then my changes are unnecessary

**Comment by feng891005** [comment]
@ktbyers 
I have updated the centec_os.py file and deleted the config_mode function

**Comment by ktbyers** [comment]
Okay, I will just go ahead and delete that `set_terminal_width` method and then we should be good to go.

Regards, Kirk

**Pull request merged**
