### PR TITLE
Adding new vendor Xirrus as Experimental.

### PR DESCRIPTION
**Pull request by skriptmonkey**
Still some work needed but I can access APs and run simple commands (`show uptime`).

### CODE REVIEW

**Comment by ktbyers** [comment]
@skriptmonkey Can you resubmit this PR to the dev_1_2 branch?

**Comment by ktbyers** [comment]
@skriptmonkey Also did you get the unit tests to pass? See more details here on the unit tests here:

https://github.com/ktbyers/netmiko/blob/master/TESTING.md


It should pass both the 'show' and 'config' tests. Here is an example of running the tests for a platform.

```
py.test -v test_netmiko_show.py --test_device arista_sw4
py.test -v test_netmiko_config.py --test_device arista_sw4
```

**Comment by skriptmonkey** [comment]
I will work on unit tests, then re-submit to the dev_1_2 branch. Thanks.

**Comment by ktbyers** [comment]
Sounds good.

**Comment by ktbyers** [comment]
@skriptmonkey What is the status of this PR? Do you want me to close it and then you re-submit it?

Did you get the unit tests working?

**Comment by skriptmonkey** [comment]
I have been traveling for work and haven't had a change to finish working on this. There are still a few errors coming up with the config test. I'll close this PR and resubmit once the tests pass.

**Comment by ktbyers** [comment]
Sounds good.

**Pull request closed without merging**
