### PR TITLE
New vendor added (6WIND)

### PR DESCRIPTION
**Pull request by paunadeu**
New vendor added, tests succeed:

 ✘ paunadeurabat@kettle  ~/PycharmProjects/netmiko/tests   develop ●✚  sh test_sixwind.sh
Starting tests...good luck... 6WIND:
============================================================================================== test session starts ===============================================================================================
platform darwin -- Python 3.8.1, pytest-5.1.2, py-1.8.1, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
cachedir: .pytest_cache
rootdir: /Users/paunadeurabat/PycharmProjects/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 19 items                                                                                                                                                                                               

test_netmiko_show.py::test_disable_paging SKIPPED                                                                                                                                                          [  5%]
test_netmiko_show.py::test_terminal_width PASSED                                                                                                                                                           [ 10%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                                              [ 15%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                                           [ 21%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                                      [ 26%]
test_netmiko_show.py::test_send_command PASSED                                                                                                                                                             [ 31%]
test_netmiko_show.py::test_cmd_verify_decorator PASSED                                                                                                                                                     [ 36%]
test_netmiko_show.py::test_send_command_global_cmd_verify PASSED                                                                                                                                           [ 42%]
test_netmiko_show.py::test_send_command_juniper SKIPPED                                                                                                                                                    [ 47%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED                                                                                                                                                    [ 52%]
test_netmiko_show.py::test_send_command_genie SKIPPED                                                                                                                                                      [ 57%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                                              [ 63%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                                             [ 68%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                                                            [ 73%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                                      [ 78%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                                             [ 84%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                                              [ 89%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                                                               [ 94%]
test_netmiko_show.py::test_disconnect_no_enable         PASSED                                                                                                                                                     [100%]

============================================================================================ short test summary info =============================================================================================
SKIPPED [1] /Users/paunadeurabat/PycharmProjects/netmiko/tests/test_netmiko_show.py:38: Disable paging not supported on this platform, append | no-pager at command
SKIPPED [1] /Users/paunadeurabat/PycharmProjects/netmiko/tests/test_netmiko_show.py:137: <Skipped instance>
SKIPPED [1] /Users/paunadeurabat/PycharmProjects/netmiko/tests/test_netmiko_show.py:158: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /Users/paunadeurabat/PycharmProjects/netmiko/tests/test_netmiko_show.py:183: Genie not supported on this platform
========================================================================================= 15 passed, 4 skipped in 41.31s =========================================================================================
============================================================================================== test session starts ===============================================================================================
platform darwin -- Python 3.8.1, pytest-5.1.2, py-1.8.1, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
cachedir: .pytest_cache
rootdir: /Users/paunadeurabat/PycharmProjects/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 8 items                                                                                                                                                                                                

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                                                            [ 12%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                                                            [ 25%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                                                            [ 37%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                                                       [ 50%]
test_netmiko_config.py::test_config_set PASSED                                                                                                                                                             [ 62%]
test_netmiko_config.py::test_config_set_longcommand PASSED                                                                                                                                                 [ 75%]
test_netmiko_config.py::test_config_from_file PASSED                                                                                                                                                       [ 87%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                                                             [100%]

=============================================================================================== 8 passed in 38.85s ===============================================================================================

### CODE REVIEW

**Comment by paunadeu** [comment]
ERROR: InvocationError for command /home/travis/build/ktbyers/netmiko/.tox/black/bin/black --check . (exited with code 1)

Don't know why black fails.

**Comment by paunadeu** [comment]
Finally! :) 
Let me know something, I can provide testing VM. Documentation for TR it's here: https://doc.6wind.com/turbo-router-2.2/user-guide/cli/index.html

**Comment by ktbyers** [comment]
@paunadeu Love the commit history with trying to fix the linting/black issues :-)

**Comment by ktbyers** [comment]
Updated PR here:

https://github.com/ktbyers/netmiko/pull/1749

**Pull request closed without merging**
