### PR TITLE
Added support for Ericsson MINI-LINK (MLTN) 66XX & 63XX (updated)

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@codekuu FYI, I changed the special_login_handler to use read_until_pattern format as experience has shown me this is a more reliable pattern to use. 

Let me know if you see any issues with the changes.

**Comment by ktbyers** [comment]
@codekuu I also added the standard Netmiko no-enable mode behavior. I assume this is correct i.e. these devices do not have any enable mode--correct?

**Comment by ktbyers** [comment]
I am going to merge this. It would be a good idea if you regression tested the changes I made using the Netmiko test suite (if you can).

Thanks for all your work here.

If there are issues, just let me know.

**Comment by codekuu** [comment]
Hi @ktbyers!

I have tested the code and ran it in our dev environment towards real machines, works like a charm.
Can't see any issues.

Thanks for really investing your time to make this project as great as it is!

**Comment by ktbyers** [comment]
Thanks @codekuu

**Pull request merged**
