### PR TITLE
Updated Huawei telnet support PR

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
Replaces:

https://github.com/ktbyers/netmiko/pull/1165

**Comment by ktbyers** [comment]
This PR should be good to go except should be regression tested against a real device.

**Comment by ktbyers** [comment]
@cuongnguyenduy Can you sanity check this telnet support against a real device i.e. that it still works properly (especially the telnet_login) process.

I made some minor modifications to it.

**Comment by cuong-nguyenduy** [comment]
> 
> 
> @cuongnguyenduy Can you sanity check this telnet support against a real device i.e. that it still works properly (especially the telnet_login) process.
> 
> I made some minor modifications to it.

@ktbyers 
Tested with https://github.com/ktbyers/netmiko/commit/f80a5cfc3b4e42587acf0d878f315a23c8ebdab2 on real devices. Logging in and executing commands worked.

However, call to `config_mode()` raised exception:. I guess the **```super()```** method of class **```HuaweiBase```** should refer to **```CiscoBaseConnection```** instead of **```HuaweiSSH```**. 

```
Traceback (most recent call last):
  File "netmiko_test.py", line 17, in <module>
    session.config_mode()
  File "/root/netmiko/venv-dev/lib/python3.6/site-packages/netmiko-2.3.3-py3.6.egg/netmiko/huawei/huawei.py", line 22, in config_mode
TypeError: super(type, obj): obj must be an instance or subtype of type
(venv-dev) root@LAB:~/netmiko# vi /root/netmiko/venv-dev/lib/python3.6/site-packages/netmiko-2.3.3-py3.6.egg/netmiko/huawei/huawei.py
```

**Comment by ktbyers** [comment]
I am going to merge this after fixing the super issue. If you still see problems, just let me know.

**Comment by cuong-nguyenduy** [comment]
Tested on the develop branch. Looks good.

**Pull request merged**
