### PR TITLE
adding extreme telnet class

### PR DESCRIPTION
**Pull request by fooelisa**

### CODE REVIEW

**Comment by ktbyers** [comment]
@fooelisa Will review.

**Comment by ktbyers** [comment]
I restructured some things in a minor way (mainly with file names), here https://github.com/ktbyers/netmiko/commit/6d764bc22008fae393a25680615c0c049f2ca973

and here https://github.com/ktbyers/netmiko/commit/fd46063a81b4efa1752650686e87441cd9112f4c

**Comment by fooelisa** [comment]
Thanks, looks good to me! When's the next netmiko release scheduled, as I'd like to reference the upcoming version as a dependency for this?

**Comment by ktbyers** [comment]
@fooelisa I will try to release a new version the week of February 5. It should be version `2.0.2`


Kirk

**Comment by fooelisa** [comment]
Perfect, thank you!

**Pull request merged**
