### PR TITLE
Add ovs_linux device_type

### PR DESCRIPTION
**Pull request by jumpojoy**
ovs_linux - allows to interact with ovs switch on linux
 via bash commands

### CODE REVIEW

**Comment by ktbyers** [comment]
@jumpojoy 

Sounds good. 

I will try to integrate today/tomorrow.

**Comment by jtdub** [comment]
Am I missing something? The code looks to be just a generic Linux SSH connector. I didn't see anything that was ovs specific.

**Comment by ktbyers** [comment]
@jtdub Yeah, you are right. It is just a generic Linux connector. My error on posting to Twitter earlier (I misinterpreted part of it). I should probably move it to a generic Linux class and then inherit OVS from that.

**Comment by jumpojoy** [comment]
@jtdub: managing openvswitch on linux is performed via bash commands ('ovs-vsctl' in general but other also can be used [0] ). @ktbyers: Should I move all code to generic linux class and inherit ovs from it? 

[0] http://openvswitch.org/support/dist-docs-2.4/

**Comment by ktbyers** [comment]
@jumpojoy Yes, I think we should do that (i.e. have a generic Linux class and then inherit OVS from this). There will probably be other use cases for just Linux and that will let us decouple Linux from OVS.

**Pull request merged**
