### PR TITLE
Fix tests for Dlink

### PR DESCRIPTION
**Pull request by dynax60**
- Skip the config mode tests for dlink_ds in test_config_mode, it's not implemented yet
- Skip first line with the output of the command line itself ("Command: <...>") for dlink_ds in test_strip_command

### CODE REVIEW

**Comment by dynax60** [comment]
This is output:

[ouput_config.txt](https://gist.githubusercontent.com/dynax60/52af7c739fe7abd69bbd319721439757/raw/71eace6078dbf8cac0da1fc3d31bea27db4829bd/ouput_config.txt)
[ouput_show.txt](https://gist.githubusercontent.com/dynax60/56d0c23ec84290e0adbf2156677b5e93/raw/519111397d56822da31e5b1844cfd28889642e6a/ouput_show.txt)

Config files in netmiko/tests/etc/{test_devices,commands,responses}.yml.example

**Comment by Fikirsiz** [comment]
I will test it today.

**Comment by Fikirsiz** [comment]
All tests pass.
[ouput_config.txt](https://github.com/ktbyers/netmiko/files/4356417/ouput_config.txt)
[ouput_show.txt](https://github.com/ktbyers/netmiko/files/4356418/ouput_show.txt)

**Comment by dynax60** [comment]
> All tests pass.
> [ouput_config.txt](https://github.com/ktbyers/netmiko/files/4356417/ouput_config.txt)
> [ouput_show.txt](https://github.com/ktbyers/netmiko/files/4356418/ouput_show.txt)

Could you please show your config files: commands.yml and responses.yml? Thank you. What is devices was used?

**Comment by Fikirsiz** [comment]
I use Dlink DES-1210-28/ME. I have a few other models: DES-1228/ME, DES-3228, DES-3200.
[config.txt](https://github.com/ktbyers/netmiko/files/4356582/config.txt)

**Comment by ktbyers** [comment]
Updated version of this PR was merged here:

https://github.com/ktbyers/netmiko/pull/1629

**Pull request closed without merging**
