### PR TITLE
fortinet _preferred_kex settings interfering with other devices

### PR DESCRIPTION
**Pull request by Noppes**
I have a program that connects to multiple devcies, which include fortinet and aruba_os. The moment I connected to a fortinet device I could no longer connect to aruba_os, with the error `paramiko.ssh_exception.IncompatiblePeer: Incompatible ssh peer (no acceptable kex algorithm)`.

Turns out the fortinet driver is editing the paramiko Transport class. This commit fixes that by using `disabled_algorithms` instead.

### CODE REVIEW

**Comment by ktbyers** [comment]
Need to factor in interaction with this:

https://github.com/ktbyers/netmiko/pull/2979

Which I can probably do.

**Comment by Noppes** [comment]
Any status update?

**Comment by ktbyers** [comment]
I will try to work on this on Friday (alternative, feel free to reconcile the two items i.e. this PR and linked/referenced item).

**Comment by Noppes** [comment]
Like that?

**Comment by ktbyers** [comment]
Superseded by https://github.com/ktbyers/netmiko/pull/3530

**Pull request closed without merging**
