### PR TITLE
Allied Telesis AW+ Driver

### PR DESCRIPTION
**Pull request by Rawrroar**
Addition of Allied Telesis driver, mainly all the SSH works fine just needed support for SCP

[netmiko_config.txt](https://github.com/ktbyers/netmiko/files/3849482/netmiko_config.txt)
[netmiko_show.txt](https://github.com/ktbyers/netmiko/files/3849483/netmiko_show.txt)

### CODE REVIEW

**Comment by Rawrroar** [comment]
Think I finally made black happy

**Comment by ktbyers** [comment]
@Rawrroar Is this PR good/ready for review now from your perspective?

**Comment by Rawrroar** [comment]
@ktbyers I believe so

**Comment by ktbyers** [comment]
So Allied Telesis Platform just works with the "cisco_ios" behavior?

**Comment by Rawrroar** [comment]
Yes, I've been playing around with the send config and send commands and everything so far is working as expected. The cli is very close to cisco.

**Comment by ktbyers** [comment]
This driver was implemented here:

https://github.com/ktbyers/netmiko/pull/2136

**Pull request closed without merging**
