### PR TITLE
Add/fix support Ciena SAOS

### PR DESCRIPTION
**Pull request by daanvdsanden**
Tested agains SAOS6 device. File transfer was successfull. I'm also able to use show commands and push configs.

### CODE REVIEW

**Comment by ktbyers** [comment]
@daanvdsanden I will see if I can look at this next week. Unfortunately, I am going to be really busy this week...

**Comment by daanvdsanden** [comment]
Hereby also the output of the show tests (write will follow a bit later, but before next week)

```
$ py.test -v test_netmiko_show.py --test_device ciena
============================ test session starts =============================
platform linux -- Python 3.6.7, pytest-3.10.0, py-1.7.0, pluggy-0.8.1 -- ~/Code/develop/venv/bin/python3
cachedir: .pytest_cache
rootdir: ~/Code/develop/netmiko, inifile:
plugins: pylama-7.6.6
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                       [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                          [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                       [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                  [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                  [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                          [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                         [ 58%]
test_netmiko_show.py::test_strip_command PASSED                        [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                  [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                         [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                          [ 91%]
test_netmiko_show.py::test_disconnect PASSED                           [100%]
```

**Comment by daanvdsanden** [comment]
The Enable and config tests are failing since there is no enable mode or configure mode on a Ciena SAOS device (maybe I'm defining my answeres/tests wrong). Next up the file transfer tests.
```
$ py.test -v test_netmiko_config.py --test_device ciena
============================ test session starts =============================
platform linux -- Python 3.6.7, pytest-3.10.0, py-1.7.0, pluggy-0.8.1 -- ~/Code/develop/venv/bin/python3
cachedir: .pytest_cache
rootdir: ~/Code/develop/netmiko, inifile:
plugins: pylama-7.6.6
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                       [ 14%]
test_netmiko_config.py::test_enable_mode FAILED                       [ 28%]
test_netmiko_config.py::test_config_mode FAILED                       [ 42%]
test_netmiko_config.py::test_exit_config_mode FAILED                  [ 57%]
test_netmiko_config.py::test_command_set PASSED                       [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                [ 85%]
test_netmiko_config.py::test_disconnect PASSED                        [100%]
```

**Comment by daanvdsanden** [comment]
After updating the function remote_space_available it is now also passing the scp tests:
```
$ py.test -v test_netmiko_scp.py --test_device ciena
============================ test session starts =============================
platform linux -- Python 3.6.7, pytest-3.10.0, py-1.7.0, pluggy-0.8.1 -- ~/Code/develop/venv/bin/python3
cachedir: .pytest_cache
rootdir: ~/Code/develop/netmiko, inifile:
plugins: pylama-7.6.6
collected 12 items

test_netmiko_scp.py::test_scp_put PASSED                                [  8%]
test_netmiko_scp.py::test_remote_space_available PASSED                 [ 16%]
test_netmiko_scp.py::test_local_space_available PASSED                  [ 25%]
test_netmiko_scp.py::test_verify_space_available_put PASSED             [ 33%]
test_netmiko_scp.py::test_remote_file_size PASSED                       [ 41%]
test_netmiko_scp.py::test_md5_methods PASSED                            [ 50%]
test_netmiko_scp.py::test_disconnect PASSED                             [ 58%]
test_netmiko_scp.py::test_verify_space_available_get PASSED             [ 66%]
test_netmiko_scp.py::test_scp_get PASSED                                [ 75%]
test_netmiko_scp.py::test_md5_methods_get PASSED                        [ 83%]
test_netmiko_scp.py::test_disconnect_get PASSED                         [ 91%]
test_netmiko_scp.py::test_file_transfer PASSED                          [100%]
```

**Comment by georgesnow** [comment]
i have extended the ciena support a bit further on  my fork. i have a few tests that are still failing cause i haven't finished determining the proper commands to test with.

**Comment by daanvdsanden** [comment]
> i have extended the ciena support a bit further on my fork. i have a few tests that are still failing cause i haven't finished determining the proper commands to test with.

etc/commands.yml and etc/responses.yml are in .gitignore but I added below snippets shows variables I used:
commands.yml:
```yaml
ciena_saos:
  version: "software show"
  basic: "interface show"
  extended_output: "configuration show"
  config:
    - "system set time-offset 7200" # base command
    - "system set timestamp local"
    - "system set time-offset 3600" # something you can verify has changed
  config_verification: "configuration search running-config string \"set time-offset\""
  config_file: "ciena_saos_commands.txt"
  save_config_cmd: "configuration save"
  save_config_confirm: False
  save_config_response: False
```
and responses.yml:
```yaml
ciena:
  base_prompt: router1
  router_prompt: router1>
  enable_prompt: router1>
  version_banner: saos-
  interface_ip: 192.0.2.1
  multiple_line_output: "NETCONF CONFIG"
  file_check_cmd: "system set time-offset 3600"
  scp_remote_space: 10000
```

**Comment by georgesnow** [comment]
@daanvdsanden so i tried using this against my SAOS device for SCP. i am failing on some of this stuff. I have made some modifications. What version of SAOS you running this against?

**Comment by georgesnow** [comment]
@ktbyers does a augmenting device functionality need to pass on all tests before making a pull request that will get merged?

**Comment by daanvdsanden** [comment]
> @daanvdsanden so i tried using this against my SAOS device for SCP. i am failing on some of this stuff. I have made some modifications. What version of SAOS you running this against?

I Have tested it on SAOS6. If I have time the next week I'll check SAOS8...

**Comment by georgesnow** [comment]
@daanvdsanden SAOS 6.15. part of the fails was i had the wrong function defined fixed that. also i had to make some modifications to your SCP work to get it working on my ciena box. i need to do some more debugging. I pushed part of my changes to my fork.

**Comment by georgesnow** [comment]
[netmiko-cienascp-errors.txt](https://github.com/ktbyers/netmiko/files/3531796/netmiko-cienascp-errors.txt)

**Comment by daanvdsanden** [comment]
```
___________________________ test_verify_space_available_get ____________________________

scp_fixture_get = (<netmiko.ciena.ciena_saos_ssh.CienaSaosSSH object at 0x7f3d03389550>, <netmiko.ciena.ciena_saos_ssh.CienaSaosFileTransfer object at 0x7f3d0339bba8>)

    def test_verify_space_available_get(scp_fixture_get):
        ssh_conn, scp_transfer = scp_fixture_get
        assert scp_transfer.verify_space_available() == True
        # intentional make there not be enough space available
        scp_transfer.file_size = 100000000000
>       assert scp_transfer.verify_space_available() == False
E       assert True == False
E         -True
E         +False
```
Is it possible that you have more than 100GB available on your hard drive? If so update /tests/test_netmiko_scp.py Line 81 to a higher number (make sure it is more than the available disk space).

For the other three failed tests. If you overwrite the method get_file to do nothing, than all test regarding getting files will fail ([See line 199 and 200](https://github.com/georgesnow/netmiko/blob/d476fc3ab706ead6e30eb2c0a2ab94e2487fd295/netmiko/ciena/ciena_saos_ssh.py#L199)).

**Comment by georgesnow** [comment]
i will take a look. I really don't think there is that much space. Also, I am working on overriding the method, and building the functionality rather than just passing it. we will see how far i get. thanks!

**Comment by georgesnow** [comment]
good call on the size. apparently this ciena box i am testing against has 120GB. now passing on that test

**Comment by georgesnow** [comment]
$ py.test -v -p no:cacheprovider test_netmiko_scp.py --test_device cienalab
================================= test session starts ==================================
platform linux -- Python 3.6.8, pytest-5.1.0, py-1.8.0, pluggy-0.12.0 -- /usr/bin/python3
rootdir: /usr/local/lib/python3.6/dist-packages/netmiko/tests
collected 12 items

test_netmiko_scp.py::test_scp_put PASSED                                         [  8%]
test_netmiko_scp.py::test_remote_space_available PASSED                          [ 16%]
test_netmiko_scp.py::test_local_space_available PASSED                           [ 25%]
test_netmiko_scp.py::test_verify_space_available_put PASSED                      [ 33%]
test_netmiko_scp.py::test_remote_file_size PASSED                                [ 41%]
test_netmiko_scp.py::test_md5_methods PASSED                                     [ 50%]
test_netmiko_scp.py::test_disconnect PASSED                                      [ 58%]
test_netmiko_scp.py::test_verify_space_available_get PASSED                      [ 66%]
test_netmiko_scp.py::test_scp_get PASSED                                         [ 75%]
test_netmiko_scp.py::test_md5_methods_get PASSED                                 [ 83%]
test_netmiko_scp.py::test_disconnect_get PASSED                                  [ 91%]
test_netmiko_scp.py::test_file_transfer PASSED                                   [100%]

============================ 12 passed in 75.92s (0:01:15) =============================

**Comment by georgesnow** [comment]
turns out this ciena box has 120GB of space

**Comment by Aacis01** [comment]
Hi David,
 Well I was trying to add a template for Ciena Switches in my rconfig. But somehow i am not able to telnet to the switches. Can you please help me out on it??

**Comment by ktbyers** [comment]
I fixed the merge conflict and made some updates to this mainly in the Secure Copy section here:

https://github.com/ktbyers/netmiko/pull/1384

Sorry for the delay in getting to this.

**Pull request closed without merging**
