### PR TITLE
Use sendall() instead of send().

### LINKED ISSUE #100: Send() method used without checking that all data was sent
The [send()](http://paramiko-docs.readthedocs.org/en/latest/api/channel.html#paramiko.channel.Channel.send) method of Paramiko channels doesn't guarantee that all the data gets sent, but there is a [sendall()](http://paramiko-docs.readthedocs.org/en/latest/api/channel.html#paramiko.channel.Channel.sendall) method that does. Using sendall() saves you from having to write your own loop.

This is an easy swap - I'll submit a PR for review.

### PR DESCRIPTION
**Pull request by yourteamneedsadam**
Paramiko's send() method doesn't guarantee that all data will be
sent, but sendall() does.

Fixes #100

### CODE REVIEW

**Comment by yourteamneedsadam** [comment]
Build failed but it looks like an unrelated error - let me know if you see anything in this that needs fixing and I'll update it.

**Comment by ktbyers** [comment]
Yes, this should be fine. I looked at Paramiko docs and sendall() looked to be a superior way to do this. Will integrate into code and double check the Travis CI build.

**Comment by ktbyers** [comment]
@yourteamneedsadam FYI, I am planning on converting the license to Apache2 (as it provides a better framework for contributions from a set of contributors). Let me know that you are okay with this.

**Comment by yourteamneedsadam** [comment]
@ktbyers Apache2 license is great - thanks for checking!

**Pull request merged**
