### PR TITLE
Don't wait for "any key" message in HP ProCurve

### PR DESCRIPTION
**Pull request by jobec**
The HP ProCurve driver seems to wait for the "press any key" message after logging in. But this message appears before login. Hence it's waiting and spending time for noting.

### CODE REVIEW

**Comment by jobec** [comment]
@ktbyers Any change you could look into this already?

**Comment by ktbyers** [comment]
Re-tested on my old ProCurve and the `press any key to continue` is after the SSH login so this change would break those set of devices.

**Comment by ktbyers** [comment]
@jobec Just let me know what you find when you re-test on your devices for SSH/telnet. I was not able to test on telnet given my current setup.

**Comment by jobec** [comment]
It's indeed telnet specific 🤦‍♂ 

### Telnet
```
ProCurve J4900B Switch 2626
Software revision H.xx.xx

Copyright (C) 1991-2010 Hewlett-Packard Co.  All Rights Reserved.

                           RESTRICTED RIGHTS LEGEND

 Use, duplication, or disclosure by the Government is subject to restrictions
 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
 Computer Software clause at 52.227-7013.

         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303

** This device is owned and managed by xxxxxx. Unauthorized access prohibited. **
Press any key to continue
Please Enter Login Name: xxxx
Please Enter Password:


tty=none device1#
```
### SSH (in putty)
```
login as: xxxx
** This device is owned and managed by xxxx. Unauthorized access prohibited. **
xxxx@device2's password:

ProCurve J8164A Switch 2626-PWR
Software revision H.xx.xx

Copyright (C) 1991-2010 Hewlett-Packard Co.  All Rights Reserved.

                           RESTRICTED RIGHTS LEGEND

 Use, duplication, or disclosure by the Government is subject to restrictions
 as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
 Computer Software clause at 52.227-7013.

         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303

Press any key to continue


tty=none device2#
```

**Comment by jobec** [comment]
Fixed by performing the wait only on SSH, not on Telnet.

**Comment by jobec** [comment]
Looks like it's working fine

**Pull request merged**
