### PR TITLE
ScreenOS - Fix a problem with finding the base_prompt

### PR DESCRIPTION
**Pull request by nebi**
Due to some command is changing the base_prompt.

Example :

```
ssg5-serial-> set vrouter test
ssg5-serial(test)->
```

The solution is to remove "(VROUTERNAME)" and trailing "-" from base_prompt so it only looking for the hostname. 

```
Starting tests...good luck:
================== test session starts ===================
platform darwin -- Python 3.7.4, pytest-5.3.1, py-1.8.0, p
luggy-0.13.1 -- /Users/juhchr/venv/netmiko/bin/python
cachedir: .pytest_cache
rootdir: /Users/juhchr/Project/netscreen/netmiko, inifile:
 setup.cfg
plugins: pylama-7.7.1
collected 15 items                                       

test_netmiko_show.py::test_disable_paging PASSED   [  6%]
test_netmiko_show.py::test_ssh_connect PASSED      [ 13%]
test_netmiko_show.py::test_ssh_connect_cm PASSED   [ 20%]
test_netmiko_show.py::test_send_command_timing PASSED [ 26
%]
test_netmiko_show.py::test_send_command PASSED     [ 33%]
test_netmiko_show.py::test_send_command_juniper SKIPPED [ 
40%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED [ 46%]
test_netmiko_show.py::test_send_command_genie SKIPPED [ 53%]
test_netmiko_show.py::test_base_prompt PASSED      [ 60%]
test_netmiko_show.py::test_strip_prompt PASSED     [ 66%]
test_netmiko_show.py::test_strip_command PASSED    [ 73%]
test_netmiko_show.py::test_normalize_linefeeds PASSED [ 80%]
test_netmiko_show.py::test_clear_buffer PASSED     [ 86%]
test_netmiko_show.py::test_enable_mode PASSED      [ 93%]
test_netmiko_show.py::test_disconnect PASSED       [100%]

================ short test summary info =================
SKIPPED [1] /Users/juhchr/Project/netscreen/netmiko/tests/test_netmiko_show.py:74: <Skipped instance>
SKIPPED [1] /Users/juhchr/Project/netscreen/netmiko/tests/test_netmiko_show.py:96: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /Users/juhchr/Project/netscreen/netmiko/tests/test_netmiko_show.py:122: Genie not supported on this platform
============= 12 passed, 3 skipped in 39.39s =============
================== test session starts ===================
platform darwin -- Python 3.7.4, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- /Users/juhchr/venv/netmiko/bin/python
cachedir: .pytest_cache
rootdir: /Users/juhchr/Project/netscreen/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 7 items                                        

test_netmiko_config.py::test_ssh_connect PASSED    [ 14%]
test_netmiko_config.py::test_enable_mode PASSED    [ 28%]
test_netmiko_config.py::test_config_mode PASSED    [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED [ 57%]
test_netmiko_config.py::test_command_set PASSED    [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED [ 85%]
test_netmiko_config.py::test_disconnect PASSED     [100%]

=================== 7 passed in 8.37s ====================
```

### CODE REVIEW

**Comment by ktbyers** [comment]
@nebi This:

`set vrouter test` is a configuration change--correct?

**Comment by nebi** [comment]
> 
> 
> @nebi This:
> 
> `set vrouter test` is a configuration change--correct?

Yes and no, if you just using `set vrouter test` it will do nothing itself , you just enter "configuration mode" or what to call it for that vrouter so you can add configuration for the vrouter like static route etc. But if you use `set vrouter test route 100.65.0.0/24 gateway 192.168.2.1` it will made a configuration change. And if you create it that way is doesn't change the base_prompt at all : 

```
ssg5-serial-> set vrouter test route 100.65.0.0/24 gateway 192.168.2.1
ssg5-serial->
```

I hope this make sense.

**Comment by ktbyers** [comment]
@nebi Can you post the Python code and exception that causes an issue? Basically, I think what you are referring to is likely not an issue (but I want to look at your case where you are seeing an issue to get more data on the context).


Thanks, Kirk

**Comment by nebi** [comment]
@ktbyers  : 

```
from netmiko import ConnectHandler
import logging
logging.basicConfig(filename='test-final.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

device_config = {
 "device_type": "juniper_screenos",
 "ip": "100.65.1.1",
 "username": "netscreen",
 "password": "netscreen",
 "verbose": True,
}

connection = ConnectHandler(**device_config)


connection.send_command("set vr sasho")
connection.send_command('unset route 33.33.33.1/24 gateway 1.1.1.1')
connection.save_config()
```

Error : 
```
Traceback (most recent call last):
  File "screenostest.py", line 17, in <module>
    connection.send_command("set vr sasho")
  File "/Users/juhchr/Project/netmiko-upstream/netmikovenv/lib/python3.7/site-packages/netmiko/base_connection.py", line 1407, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: ssg5\-serial\->
```

log:
```

DEBUG:netmiko:read_channel: Remote Management Console
ssg5-serial-> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
ssg5-serial-> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is ssg5-serial->
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: set console page 0

DEBUG:netmiko:write_channel: b'set console page 0\n'
DEBUG:netmiko:Pattern is: set\ console\ page\ 0
DEBUG:netmiko:_read_channel_expect read_data: set console page 0

DEBUG:netmiko:Pattern found: set\ console\ page\ 0 set console page 0

DEBUG:netmiko:set console page 0

DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel: ssg5-serial-> 
DEBUG:netmiko:Clear buffer detects data in the channel
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel: 
ssg5-serial-> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:[find_prompt()]: prompt is ssg5-serial->
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:write_channel: b'set vr sasho\n'
DEBUG:netmiko:Pattern is: set\ vr\ sasho
DEBUG:netmiko:_read_channel_expect read_data: set vr sasho

DEBUG:netmiko:Pattern found: set\ vr\ sasho set vr sasho

DEBUG:netmiko:read_channel: ssg5-serial(sasho)-> 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
DEBUG:netmiko:read_channel: 
REPEATING THIS MESSAGE 500-TIMES
```

**Comment by ktbyers** [comment]
@nebi 

Yes, this is invalid:

```
connection.send_command("set vr sasho")
connection.send_command('unset route 33.33.33.1/24 gateway 1.1.1.1')
connection.send_command("exit")
connection.save_config()
```

You are trying to do configuration commands using `send_command` and not `send_config_set`.

I would expect you would either fully qualify your commands and use send_config_set(). For example:

```python
connection.send_config_set("set vrouter test route 100.65.0.0/24 gateway 192.168.2.1")
```

Or you would change the configuration context first, then reset the base prompt and perform the configuration commands:

```python
connection.send_command("set vr sasho")
connection.set_base_prompt()
connection.send_config_set('unset route 33.33.33.1/24 gateway 1.1.1.1')
connection.send_command("exit")
connection.set_base_prompt()
```

The first pattern would be the pattern Netmiko would be expecting i.e. that you wouldn't be changing into a sub-context to change the config for that subcontext (that you would be putting in the fully-qualified set commands instead).

Let me know if this doesn't make sense or I am incorrectly understanding the ScreenOs behavior here.


Regards,

Kirk

**Comment by ktbyers** [comment]
It looks like this should be unneeded if send_config_set() is used instead.

**Pull request closed without merging**
