### PR TITLE
Converting to standard no-enable and no-config

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@elavaud Can you re-run the both the "show" and the "config" tests and post the output here? I like to have a record that the tests were passing when the driver was created.

Thanks.

**Comment by elavaud** [comment]
show:

```
========================================================================================================================================================== test session starts ==========================================================================================================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/edouard/Documents/www/github/netmiko/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/edouard/Documents/www/github/netmiko, configfile: setup.cfg
plugins: pylama-7.7.1
collected 24 items                                                                                                                                                                                                                                                                                                                      

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                                                                                                                                                                                  [  4%]
test_netmiko_show.py::test_terminal_width PASSED                                                                                                                                                                                                                                                                                  [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                                                                                                                                                                     [ 12%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                                                                                                                                                                  [ 16%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                                                                                                                                                             [ 20%]
test_netmiko_show.py::test_send_command_timing_no_cmd_verify SKIPPED                                                                                                                                                                                                                                                              [ 25%]
test_netmiko_show.py::test_send_command PASSED                                                                                                                                                                                                                                                                                    [ 29%]
test_netmiko_show.py::test_send_command_no_cmd_verify SKIPPED                                                                                                                                                                                                                                                                     [ 33%]
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED                                                                                                                                                                                                                                                                     [ 37%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED (TextFSM/ntc-templates not supported on this platform)                                                                                                                                                                                                                    [ 41%]
test_netmiko_show.py::test_send_command_ttp SKIPPED (TTP template not existing for this platform)                                                                                                                                                                                                                                 [ 45%]
test_netmiko_show.py::test_send_command_genie SKIPPED (Genie not supported on this platform)                                                                                                                                                                                                                                      [ 50%]
test_netmiko_show.py::test_send_multiline_timing SKIPPED                                                                                                                                                                                                                                                                          [ 54%]
test_netmiko_show.py::test_send_multiline SKIPPED                                                                                                                                                                                                                                                                                 [ 58%]
test_netmiko_show.py::test_send_multiline_prompt SKIPPED                                                                                                                                                                                                                                                                          [ 62%]
test_netmiko_show.py::test_send_multiline_simple SKIPPED                                                                                                                                                                                                                                                                          [ 66%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                                                                                                                                                                     [ 70%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                                                                                                                                                                    [ 75%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                                                                                                                                                                                   [ 79%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                                                                                                                                                             [ 83%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                                                                                                                                                                    [ 87%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                                                                                                                                                                     [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                                                                                                                                                                                      [ 95%]
test_netmiko_show.py::test_disconnect_no_enable PASSED                                                                                                                                                                                                                                                                            [100%]

=========================================================================================================================================================== warnings summary ============================================================================================================================================================
tests/test_netmiko_show.py::test_disable_paging
tests/test_netmiko_show.py::test_ssh_connect_cm
tests/test_netmiko_show.py::test_send_command_timing
tests/test_netmiko_show.py::test_strip_prompt
tests/test_netmiko_show.py::test_strip_command
tests/test_netmiko_show.py::test_normalize_linefeeds
tests/test_netmiko_show.py::test_disconnect_no_enable
  /home/edouard/Documents/www/github/netmiko/netmiko/base_connection.py:678: DeprecationWarning: 
  
  Netmiko 4.x and later has deprecated the use of delay_factor and/or max_loops in
  this context. You should remove any use of delay_factor=x from this method call.
  
    warnings.warn(DELAY_FACTOR_DEPR_SIMPLE_MSG, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================================================================================== short test summary info ========================================================================================================================================================
SKIPPED [1] test_netmiko_show.py:70: Skipped
SKIPPED [1] test_netmiko_show.py:88: Skipped
SKIPPED [1] test_netmiko_show.py:110: Skipped
SKIPPED [1] test_netmiko_show.py:131: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] test_netmiko_show.py:153: TTP template not existing for this platform
SKIPPED [1] test_netmiko_show.py:193: Genie not supported on this platform
SKIPPED [1] test_netmiko_show.py:213: Skipped
SKIPPED [1] test_netmiko_show.py:229: Skipped
SKIPPED [1] test_netmiko_show.py:254: Skipped
SKIPPED [1] test_netmiko_show.py:278: Skipped
============================================================================================================================================== 14 passed, 10 skipped, 7 warnings in 47.37s ==============================================================================================================================================
```

**Comment by elavaud** [comment]
However I have some issues now with test_exit_config_mode of test_config.
There is no config mode on zyxel

```
_________________________________________________________________________________________________________________________________________________________ test_exit_config_mode _________________________________________________________________________________________________________________________________________________________

net_connect = <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7f28d633ea90>, commands = {'basic': 'cfg lan get', 'config': ["cfg wlan edit --Band 2.4GHz --MainSSID 1 --SSID 'NetmikoTest'", "cfg wlan edit --...--MainSSID 1 --SSID 'magic2000'"], 'config_verification': 'cfg intf_group get', 'extended_output': 'cfg wlan get', ...}
expected_responses = {'base_prompt': 'ZySH', 'cmd_response_final': 'magic2000', 'cmd_response_init': 'NetmikoTest', 'enable_prompt': 'ZySH>', ...}

    def test_exit_config_mode(net_connect, commands, expected_responses):
        """Test exit config mode."""
        if net_connect._config_mode:
            net_connect.exit_config_mode()
>           assert net_connect.check_config_mode() is False
E           assert True is False
E            +  where True = <bound method NoConfig.check_config_mode of <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7f28d633ea90>>()
E            +    where <bound method NoConfig.check_config_mode of <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7f28d633ea90>> = <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7f28d633ea90>.check_config_mode

test_netmiko_config.py:44: AssertionError
```

**Comment by ktbyers** [comment]
@elavaud Okay that is fine to skip that. Did the rest of the config tests pass?

I will try to fix that test so that it properly detects the `NoConfig`.

**Comment by elavaud** [comment]
Yip, otherwise all tests pass:

```
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/edouard/Documents/www/github/netmiko/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/edouard/Documents/www/github/netmiko, configfile: setup.cfg
plugins: pylama-7.7.1
collecting ... collected 12 items

test_netmiko_config.py::test_ssh_connect PASSED                          [  8%]
test_netmiko_config.py::test_enable_mode PASSED                          [ 16%]
test_netmiko_config.py::test_config_mode SKIPPED (Platform doesn't s...) [ 25%]
test_netmiko_config.py::test_exit_config_mode FAILED                     [ 33%]
test_netmiko_config.py::test_config_set PASSED                           [ 41%]
test_netmiko_config.py::test_config_set_longcommand PASSED               [ 50%]
test_netmiko_config.py::test_config_hostname PASSED                      [ 58%]
test_netmiko_config.py::test_config_from_file SKIPPED                    [ 66%]
test_netmiko_config.py::test_config_error_pattern SKIPPED (No error_...) [ 75%]
test_netmiko_config.py::test_banner SKIPPED (No banner defined.)         [ 83%]
test_netmiko_config.py::test_global_cmd_verify SKIPPED (No banner de...) [ 91%]
test_netmiko_config.py::test_disconnect PASSED                           [100%]

=================================== FAILURES ===================================
____________________________ test_exit_config_mode _____________________________

net_connect = <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7fc64ff3d730>
commands = {'basic': 'cfg lan get', 'config': ["cfg wlan edit --Index 1 --SSID 'NetmikoTest'", "cfg wlan edit --Index 1 --SSID 'magic2000'"], 'config_verification': 'cfg intf_group get', 'extended_output': 'cfg wlan get', ...}
expected_responses = {'base_prompt': 'ZySH', 'cmd_response_final': 'magic2000', 'cmd_response_init': 'NetmikoTest', 'enable_prompt': 'ZySH>', ...}

    def test_exit_config_mode(net_connect, commands, expected_responses):
        """Test exit config mode."""
        if net_connect._config_mode:
            net_connect.exit_config_mode()
>           assert net_connect.check_config_mode() is False
E           assert True is False
E            +  where True = <bound method NoConfig.check_config_mode of <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7fc64ff3d730>>()
E            +    where <bound method NoConfig.check_config_mode of <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7fc64ff3d730>> = <netmiko.zyxel.zyxel_ssh.ZyxelSSH object at 0x7fc64ff3d730>.check_config_mode

test_netmiko_config.py:44: AssertionError
=============================== warnings summary ===============================
tests/test_netmiko_config.py::test_ssh_connect
  /home/edouard/Documents/www/github/netmiko/netmiko/base_connection.py:678: DeprecationWarning: 
  
  Netmiko 4.x and later has deprecated the use of delay_factor and/or max_loops in
  this context. You should remove any use of delay_factor=x from this method call.
  
    warnings.warn(DELAY_FACTOR_DEPR_SIMPLE_MSG, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
SKIPPED [1] test_netmiko_config.py:37: Platform doesn't support config mode.
SKIPPED [1] test_netmiko_config.py:114: Skipped
SKIPPED [1] test_netmiko_config.py:126: No error_pattern defined.
SKIPPED [1] test_netmiko_config.py:160: No banner defined.
SKIPPED [1] test_netmiko_config.py:193: No banner defined.
============== 1 failed, 6 passed, 5 skipped, 1 warning in 21.38s ==============
```

**Comment by ktbyers** [comment]
Okay, sounds good. Thanks for doing this testing @elavaud

**Pull request merged**
