### PR TITLE
RAD ETX Support (rebased)

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@smk4664 I saw your comment about needing a global_delay_factor of 2 was needed for SSH. I am planning on just setting this to be the default in the rad code.

Let me know if you see any issues with that.


Kirk

**Comment by smk4664** [comment]
I don't have any issues with that.  I was hoping to only have it needed on the SSH, but, slow and stable is better.

**Comment by ktbyers** [comment]
I implemented the delay only on the SSH. I made some very minor modifications to what you had. Let me know if you get a chance and can sanity-check/re-test the develop branch post merge (as I don't have one of these devices to test with).

@smk4664

**Comment by smk4664** [comment]
I pulled the develop branch and reran all tests, everything passed. Thank You!  I am looking forward to the next release!

@ktbyers

**Comment by ktbyers** [comment]
Okay...nice. Thanks for re-testing.



Kirk

**Pull request merged**
