### PR TITLE
Dell SONiC File Transfer implementation

### PR DESCRIPTION
**Pull request by aravindmani-1**
**What i did:**

- To fix https://github.com/ktbyers/netmiko/issues/3102

**How i did:**

- Modified the code to support Dell SONiC SCP File Transfer implementation.

**How to verify it:**

        ./dellsonic_test.sh
        Starting tests...good luck:
        Dell SONiC Networking
        ==================================================================================== test session starts ====================================================================================
        platform linux -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0 -- /usr/bin/python3
        cachedir: .pytest_cache
        rootdir: /home/am1/netmiko, configfile: setup.cfg
        plugins: cov-4.0.0, pylama-8.4.1, pythonpath-0.7.4, json-0.4.0
        collected 25 items
        
        test_netmiko_show.py::test_failed_key SKIPPED (Not using SSH-keys)                                                                                                                    [  4%]
        test_netmiko_show.py::test_disable_paging PASSED                                                                                                                                      [  8%]
        test_netmiko_show.py::test_terminal_width PASSED                                                                                                                                      [ 12%]
        test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                         [ 16%]
        test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                      [ 20%]
        test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                 [ 24%]
        test_netmiko_show.py::test_send_command_timing_no_cmd_verify SKIPPED                                                                                                                  [ 28%]
        test_netmiko_show.py::test_send_command PASSED                                                                                                                                        [ 32%]
        test_netmiko_show.py::test_send_command_no_cmd_verify SKIPPED                                                                                                                         [ 36%]
        test_netmiko_show.py::test_complete_on_space_disabled SKIPPED                                                                                                                         [ 40%]
        test_netmiko_show.py::test_send_command_textfsm SKIPPED (TextFSM/ntc-templates not supported on this platform)                                                                        [ 44%]
        test_netmiko_show.py::test_send_command_ttp SKIPPED (TTP template not existing for this platform)                                                                                     [ 48%]
        test_netmiko_show.py::test_send_command_genie SKIPPED (Genie not supported on this platform)                                                                                          [ 52%]
        test_netmiko_show.py::test_send_multiline_timing SKIPPED                                                                                                                              [ 56%]
        test_netmiko_show.py::test_send_multiline SKIPPED                                                                                                                                     [ 60%]
        test_netmiko_show.py::test_send_multiline_prompt SKIPPED                                                                                                                              [ 64%]
        test_netmiko_show.py::test_send_multiline_simple SKIPPED                                                                                                                              [ 68%]
        test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                         [ 72%]
        test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                        [ 76%]
        test_netmiko_show.py::test_strip_command PASSED                                                                                                                                       [ 80%]
        test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                 [ 84%]
        test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                        [ 88%]
        test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                         [ 92%]
        test_netmiko_show.py::test_disconnect PASSED                                                                                                                                          [ 96%]
        test_netmiko_show.py::test_disconnect_no_enable SKIPPED                                                                                                                               [100%]
        
        ================================================================================== short test summary info ==================================================================================
        SKIPPED [1] test_netmiko_show.py:25: Not using SSH-keys
        SKIPPED [1] test_netmiko_show.py:88: Skipped
        SKIPPED [1] test_netmiko_show.py:106: Skipped
        SKIPPED [1] test_netmiko_show.py:128: Skipped
        SKIPPED [1] test_netmiko_show.py:149: TextFSM/ntc-templates not supported on this platform
        SKIPPED [1] test_netmiko_show.py:171: TTP template not existing for this platform
        SKIPPED [1] test_netmiko_show.py:211: Genie not supported on this platform
        SKIPPED [1] test_netmiko_show.py:231: Skipped
        SKIPPED [1] test_netmiko_show.py:247: Skipped
        SKIPPED [1] test_netmiko_show.py:272: Skipped
        SKIPPED [1] test_netmiko_show.py:296: Skipped
        SKIPPED [1] test_netmiko_show.py:401: Skipped
        ============================================================================== 13 passed, 12 skipped in 50.03s ==============================================================================
        ==================================================================================== test session starts ====================================================================================
        platform linux -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0 -- /usr/bin/python3
        cachedir: .pytest_cache
        rootdir: /home/am1/netmiko, configfile: setup.cfg
        plugins: cov-4.0.0, pylama-8.4.1, pythonpath-0.7.4, json-0.4.0
        collected 13 items
        
        test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                                       [  7%]
        test_netmiko_config.py::test_enable_mode PASSED                                                                                                                                       [ 15%]
        test_netmiko_config.py::test_config_mode PASSED                                                                                                                                       [ 23%]
        test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                                  [ 30%]
        test_netmiko_config.py::test_config_set PASSED                                                                                                                                        [ 38%]
        test_netmiko_config.py::test_config_set_generator PASSED                                                                                                                              [ 46%]
        test_netmiko_config.py::test_config_set_longcommand PASSED                                                                                                                            [ 53%]
        test_netmiko_config.py::test_config_hostname PASSED                                                                                                                                   [ 61%]
        test_netmiko_config.py::test_config_from_file SKIPPED                                                                                                                                 [ 69%]
        test_netmiko_config.py::test_config_error_pattern SKIPPED (No error_pattern defined.)                                                                                                 [ 76%]
        test_netmiko_config.py::test_banner SKIPPED (No banner defined.)                                                                                                                      [ 84%]
        test_netmiko_config.py::test_global_cmd_verify SKIPPED (No banner defined.)                                                                                                           [ 92%]
        test_netmiko_config.py::test_disconnect PASSED                                                                                                                                        [100%]
        
        ================================================================================== short test summary info ==================================================================================
        SKIPPED [1] test_netmiko_config.py:163: Skipped
        SKIPPED [1] test_netmiko_config.py:175: No error_pattern defined.
        SKIPPED [1] test_netmiko_config.py:209: No banner defined.
        SKIPPED [1] test_netmiko_config.py:242: No banner defined.
        ========================================================================== 9 passed, 4 skipped in 65.57s (0:01:05) ==========================================================================
        ==================================================================================== test session starts ====================================================================================
        platform linux -- Python 3.8.10, pytest-7.2.0, pluggy-1.0.0 -- /usr/bin/python3
        cachedir: .pytest_cache
        rootdir: /home/am1/netmiko, configfile: setup.cfg
        plugins: cov-4.0.0, pylama-8.4.1, pythonpath-0.7.4, json-0.4.0
        collected 12 items
        
        test_netmiko_scp.py::test_scp_put PASSED                                                                                                                                              [  8%]
        test_netmiko_scp.py::test_remote_space_available PASSED                                                                                                                               [ 16%]
        test_netmiko_scp.py::test_local_space_available PASSED                                                                                                                                [ 25%]
        test_netmiko_scp.py::test_verify_space_available_put PASSED                                                                                                                           [ 33%]
        test_netmiko_scp.py::test_remote_file_size PASSED                                                                                                                                     [ 41%]
        test_netmiko_scp.py::test_md5_methods PASSED                                                                                                                                          [ 50%]
        test_netmiko_scp.py::test_disconnect PASSED                                                                                                                                           [ 58%]
        test_netmiko_scp.py::test_verify_space_available_get PASSED                                                                                                                           [ 66%]
        test_netmiko_scp.py::test_scp_get PASSED                                                                                                                                              [ 75%]
        test_netmiko_scp.py::test_md5_methods_get PASSED                                                                                                                                      [ 83%]
        test_netmiko_scp.py::test_disconnect_get PASSED                                                                                                                                       [ 91%]
        test_netmiko_scp.py::test_file_transfer PASSED                                                                                                                                        [100%]
        
        ==================================================================================== 12 passed in 51.14s ====================================================================================

### CODE REVIEW

**Comment by ktbyers** [comment]
@aravindmani-1 It looks like you have an error in one of your files that is failing on the automated tests (see the test output above).

Can you fix that issue?

**Comment by aravindmani-1** [comment]
> @aravindmani-1 It looks like you have an error in one of your files that is failing on the automated tests (see the test output above).
> 
> Can you fix that issue?

Thanks @ktbyers. recreated the error using pylint and resolved the same in latest commit.

**Comment by aravindmani-1** [comment]
Hi @ktbyers From the latest build failure, it is unclear what the issue is?. Is this build issue?.

**Logs:**
would reformat netmiko/dell/dell_sonic_ssh.py
would reformat tests/conftest.py
  
  Oh no! 💥 💔 💥
  2 files would be reformatted, 251 files would be left unchanged.
  Error: The operation was canceled.

**Comment by aravindmani-1** [comment]
Local black test,pylama logs:
[local_build_logs.txt](https://github.com/ktbyers/netmiko/files/10593779/local_build_logs.txt)

**Comment by aravindmani-1** [comment]
**Black,pylama, UT results:**
[test_results.txt](https://github.com/ktbyers/netmiko/files/10594091/test_results.txt)

**Comment by ktbyers** [comment]
Just run `black .` at the base of the repository and that should auto reformat the code @aravindmani-1 (for the files that are failing).

**Comment by aravindmani-1** [comment]
> Just run `black .` at the base of the repository and that should auto reformat the code @aravindmani-1 (for the files that are failing).

Thanks @ktbyers. 
Attached the black test results:
[black_test_results.txt](https://github.com/ktbyers/netmiko/files/10671218/black_test_results.txt)

**Comment by aravindmani-1** [comment]
@ktbyers  I don't see any black test failures locally but in remote, it seems to be failing. Do i need to do force commit?.
        am1@sonic-maa:~/sonic/netmiko$ black .
        All done! ✨ ð��° ✨
        253 files left unchanged.

**Comment by ktbyers** [comment]
@aravindmani-1 I will probably reimplement this PR as something went pretty wrong here (i.e. the PR shouldn't be changing 42-files).

**Comment by aravindmani-1** [comment]
> @aravindmani-1 I will probably reimplement this PR as something went pretty wrong here (i.e. the PR shouldn't be changing 42-files).

Thanks. Currently, there is no black test failure but mypy seems to be failing.
 By default(without my changes), black test is trying to reformat 26 files.
        
        (.venv) am1@sonic-maa:~/netmiko$ black .
        reformatted /home/am1/netmiko/netmiko/adva/adva_aos_fsp_150_f2.py
        reformatted /home/am1/netmiko/netmiko/adva/adva_aos_fsp_150_f3.py
        reformatted /home/am1/netmiko/netmiko/centec/centec_os.py
        reformatted /home/am1/netmiko/netmiko/apresia/apresia_aeos.py
        reformatted /home/am1/netmiko/netmiko/cisco/cisco_ios.py
        reformatted /home/am1/netmiko/netmiko/cisco/cisco_wlc_ssh.py
        reformatted /home/am1/netmiko/netmiko/audiocode/audiocode_ssh.py
        reformatted /home/am1/netmiko/netmiko/ruijie/ruijie_os.py
        reformatted /home/am1/netmiko/netmiko/hp/hp_procurve.py
        reformatted /home/am1/netmiko/netmiko/nokia/nokia_srl.py
        reformatted /home/am1/netmiko/netmiko/sixwind/sixwind_os.py
        reformatted /home/am1/netmiko/netmiko/raisecom/raisecom_roap.py
        reformatted /home/am1/netmiko/netmiko/paloalto/paloalto_panos.py
        reformatted /home/am1/netmiko/tests/test_timeout_read_timing.py
        reformatted /home/am1/netmiko/tests/test_timeout_read_until_pattern.py
        reformatted /home/am1/netmiko/netmiko/snmp_autodetect.py
        reformatted /home/am1/netmiko/tests/test_timeout_send_command_timing.py
        reformatted /home/am1/netmiko/tests/network_utilities.py
        reformatted /home/am1/netmiko/tests/performance/test_scrapli_new.py
        reformatted /home/am1/netmiko/tests/performance/test_netmiko.py
        reformatted /home/am1/netmiko/tests/test_timeout_send_command.py
        reformatted /home/am1/netmiko/netmiko/ssh_dispatcher.py
        reformatted /home/am1/netmiko/tests/test_netmiko_commit.py
        reformatted /home/am1/netmiko/tests/unit/test_utilities.py
        reformatted /home/am1/netmiko/tests/test_netmiko_show.py
        reformatted /home/am1/netmiko/netmiko/base_connection.py
        
        All done! ✨ ð��° ✨
        26 files reformatted, 227 files left unchanged.
        (.venv) am1@sonic-maa:~/netmiko$

**Comment by aravindmani-1** [comment]
@ktbyers  shall i close this PR and open a new PR with my changes alone?.

**Comment by ktbyers** [comment]
@aravindmani-1 Yeah, if you want to rebase your PR and resubmit that would be great.

If not, just leave it open and I will see if I can fix it.

**Comment by aravindmani-1** [comment]
Thanks @ktbyers . https://github.com/ktbyers/netmiko/pull/3122 has been raised with Dell specific changes. I also observed that changes made under the directory https://github.com/ktbyers/netmiko/tree/develop/tests/etc/ are not added to the committed files(git add doesn't add it).

**Comment by ktbyers** [comment]
@aravindmani-1 I will fix this PR (unless you are planning on resubmitting it).

**Comment by aravindmani-1** [comment]
> @aravindmani-1 I will fix this PR (unless you are planning on resubmitting it).

Hi @ktbyers  I've already submitted a new PR: https://github.com/ktbyers/netmiko/pull/3122. please review.

**Pull request closed without merging**
