### PR TITLE
Add support for a SessionLog object for session_log in __init__.py

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@dannywade FYI, I made some minor updates to the test code (call .open(), there was a missing .get, and needed to place at the end of tests).

I needed to relocate it to the end of the tests is the test doesn't reinitialize so using a SessionLog object was breaking some of the tests that followed it (hence I made it be the last test).

**Comment by ktbyers** [comment]
```
test_netmiko_session_log.py::test_session_log PASSED
test_netmiko_session_log.py::test_session_log_write PASSED
test_netmiko_session_log.py::test_session_log_append PASSED
test_netmiko_session_log.py::test_session_log_secrets PASSED
test_netmiko_session_log.py::test_logging_filter_secrets PASSED
test_netmiko_session_log.py::test_unicode PASSED
test_netmiko_session_log.py::test_session_log_bytesio PASSED
test_netmiko_session_log.py::test_session_log_custom_secrets PASSED
```

**Comment by dannywade** [comment]
@ktbyers Thank you! When are you planning the next release of netmiko?

**Comment by ktbyers** [comment]
@dannywade Maybe a month or so. I don't have a specific date.

You should be able to use the `develop` branch, however, so I should not be gating you.

**Pull request merged**
