### PR TITLE
linux_ssh: fix for 'Invalid output from MD5 command'

### PR DESCRIPTION
**Pull request by pestophagous**
I believe that this:

fixes issue #3209

Original credit goes to commenter on the issue: https://github.com/ktbyers/netmiko/issues/3209#issuecomment-2245991018

Locally I am using this change and it fixes the problem.

### CODE REVIEW

**Comment by pestophagous** [comment]
I really hope this fix (or any fix for the minor bug) can be merged, because I very much want to use the only-copy-when-necessary feature. It's a great feature. Thank you for thinking of it in the design of your library.

**Review by ktbyers — APPROVED** [review]

**Comment by pestophagous** [comment]
@ktbyers thank you for your time and your FOSS service!  What's the best way for me to watch the release rollout and know which release-version (for `requirements.txt`) will contain this fix?

**Comment by ktbyers** [comment]
Yeah, I don't know when I will do the next release.

I assume you can just `git clone` the develop branch or to the specific commit containing that fix?

**Comment by pestophagous** [comment]
> Yeah, I don't know when I will do the next release.
> 
> I assume you can just `git clone` the develop branch or to the specific commit containing that fix?

Ah yes. Branch name or commit will work. Thanks a bunch!

**Comment by pestophagous** [comment]
> Branch name or commit will work. Thanks a bunch!

In case anyone else lands on this webpage and wants to `pip install -r` a version that has this linux md5 fix, this is exactly the line that I ended up with in `requirements.txt`:

```
netmiko @ git+https://github.com/ktbyers/netmiko@eefa4c4cc3 # can use release semver after next release
```

**Pull request merged**
