### PR TITLE
Regex for stripping most ansi escape codes

### PR DESCRIPTION
**Pull request by Benedikt1992**
As @smnmtzgr already metioned in Issue #164 the function find_prompt() can't find the prompt if there are colors enabled. Technically speaking the function strip_ansi_escape_codes() doesn't even get called and can't remove all escape codes.

Therefore I enhanced the function to remove the most of possible escape codes (maybe there are some special codes that are not matched) and introduced a new argument to enable the stripping of escape codes. Default is not to strip escape codes (as it is today).

### CODE REVIEW

**Comment by ktbyers** [comment]
@Benedikt1992 Yes, historically strip_ansi_escape_codes wasn't for Cisco (only cases where needed mainly HP ProCurve).

The NEXUS color issue is a fairly new issue.

Is this NEXUS color enabled by default? I seem to recall no (could be wrong on this)? Also why not just turn it off (at least for scripts)? Do many people use this?

Reluctant to change this without a better reason as stripping data from output is not that great of a practice. 

Also probably wouldn't accept this change anyways (at a minimum you would have to document the regex). 

I think the previous way is better i.e. explicitly identify the ANSI escape codes to strip. So if we want to fix the NEXUS color issue then would have to look at the ANSI codes it generates. 

If this is impractical due too many ANSI escape codes or there isn't some simpler pattern that we could match on, then we could possibly go to a more complex regex pattern. I am pretty strongly against complex regex patterns, however, as they are really hard to understand, maintain, and test.

**Comment by Benedikt1992** [comment]
@ktbyers As @smnmtzgr wrote this color feature is disabled by default. If you want to use this feature you can enable it per user. So if you want to disable it for scripts you have 3 options
1. You run the script with an different user
2. You don't use the feature
3. Each script checks if there is the color feature enabled. If appplicable the script turns off the feature in the beginning and reenables it when finished.

The last two option feels a little bit dirty to me. The first option may works in many cases. Nevertheless filtering those problematic escape codes seems the clearst solution to me. Basically every command line tool has to filter those escape codes. Since every command line tool strips those escape codes it's not necessarily trivial to determine which Codes are used. Filtering every escape code seems to be much easier.

The regex isn't easy at all. How would you imagine such a documentation?

**Comment by ktbyers** [comment]
@Benedikt1992 @smnmtzgr 1 or 2 sound fine to me (especially since this feature is not enabled by default). 

> Basically every command line tool has to filter those escape codes. Since every command line tool strips those escape codes it's not necessarily trivial to determine which Codes are used.

We only need to solve the NEXUS color escape codes, not every possible ANSI escape code. This is probably a pretty small set of escape codes. It is pretty rare for me to run into ANSI escape codes in router output.

The flip side is filtering output from the output stream is not a great idea (in general). I also don't know all of the uses for ANSI escape codes so I am reluctant to have a broad filter (especially when it rarely applies to router output).

Can someone post the output that you get back from the Nexus with the ANSI escape codes embedded in it?

**Comment by ktbyers** [comment]
I think we are at an impasse on this. 

I am open to other solutions on this, my preferred solution is just to add the ANSI color codes that that the Nexus uses in its output and strip them specifically. I don't have access to a Nexus so I can't test right now.

I have been working on getting a virtual Nexus working on KVM, but am still running into issues. I will probably try to fix this once I get that working.

In the interim, I will track this as an issue in GitHub.

**Comment by ktbyers** [comment]
Tracking this issue here https://github.com/ktbyers/netmiko/issues/168

**Pull request closed without merging**
