### PR TITLE
Add Ericsson IPOS support

### PR DESCRIPTION
**Pull request by DylanHamel**
Add basic functions for Ericsson IPOS

### CODE REVIEW

**Comment by ktbyers** [comment]
It looks like you are failing on Python black. You should just need to run `black .` from the base of the Netmiko repository.

**Comment by DylanHamel** [comment]
Hi, I executed `black .` in my last commit (`Reformatted with Black`).

**Comment by ktbyers** [comment]
@DylanHamel Tests (black-check) is still failing. See CI-CD output above.

**Comment by DylanHamel** [comment]
@ktbyers, Sorry I was using an other version of `black` ...

**Comment by lutfisan** [comment]
when this will release?

**Comment by ktbyers** [comment]
@lutfisan I am not sure when I will review/approve this...but there is nothing stopping you from using it (i.e. you can just clone this branch and use it).


Kirk

**Comment by ktbyers** [comment]
Did anyone ever run the unit tests on this?

If so can you please post the test results into this issue.

Testing process is here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by DylanHamel** [comment]
Hi @ktbyers,
Sorry for this response time ...
I added missing functions and run tests.

```
$ py.test -v test_netmiko_show.py --test_device ericsson_ipos
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.6.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/dhamel/netmiko/bin/python3
cachedir: .pytest_cache
rootdir: /home/dhamel/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 15 items                                                                                                                                                       

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                   [  6%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                      [ 13%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                   [ 20%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                              [ 26%]
test_netmiko_show.py::test_send_command PASSED                                                                                                                     [ 33%]
test_netmiko_show.py::test_send_command_juniper SKIPPED                                                                                                            [ 40%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED                                                                                                            [ 46%]
test_netmiko_show.py::test_send_command_genie SKIPPED                                                                                                              [ 53%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                      [ 60%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                     [ 66%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                    [ 73%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                              [ 80%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                     [ 86%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                      [ 93%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                       [100%]

======================================================================== short test summary info =========================================================================
SKIPPED [1] /home/dhamel/netmiko/tests/test_netmiko_show.py:74: <Skipped instance>
SKIPPED [1] /home/dhamel/netmiko/tests/test_netmiko_show.py:96: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /home/dhamel/netmiko/tests/test_netmiko_show.py:122: Genie not supported on this platform
===================================================================== 12 passed, 3 skipped in 44.67s =====================================================================
```

**Comment by DylanHamel** [comment]
PS: Probably, it's needed to run "lint" tests

**Comment by ktbyers** [comment]
How about Config Tests--can you run those as well?

```
$ py.test -v test_netmiko_config.py --test_device ericsson_ipos
```

**Comment by DylanHamel** [comment]
Sorry, I missed it ....

```
$ py.test -v test_netmiko_config.py --test_device ericsson_ipos
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.6.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/taahady1/netmiko/bin/python3
cachedir: .pytest_cache
rootdir: /home/taahady1/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 7 items                                                                                                                                                        

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                    [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                    [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                    [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                               [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                                                    [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                                             [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                     [100%]

=========================================================================== 7 passed in 52.85s ===========================================================================


$ py.test -v test_netmiko_show.py --test_device ericsson_ipos
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.6.8, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/taahady1/netmiko/bin/python3
cachedir: .pytest_cache
rootdir: /home/taahady1/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 15 items                                                                                                                                                       

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                   [  6%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                      [ 13%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                   [ 20%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                              [ 26%]
test_netmiko_show.py::test_send_command PASSED                                                                                                                     [ 33%]
test_netmiko_show.py::test_send_command_juniper SKIPPED                                                                                                            [ 40%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED                                                                                                            [ 46%]
test_netmiko_show.py::test_send_command_genie SKIPPED                                                                                                              [ 53%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                      [ 60%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                     [ 66%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                    [ 73%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                              [ 80%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                     [ 86%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                      [ 93%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                       [100%]

======================================================================== short test summary info =========================================================================
SKIPPED [1] /home/taahady1/netmiko/tests/test_netmiko_show.py:74: <Skipped instance>
SKIPPED [1] /home/taahady1/netmiko/tests/test_netmiko_show.py:96: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /home/taahady1/netmiko/tests/test_netmiko_show.py:122: Genie not supported on this platform
===================================================================== 12 passed, 3 skipped in 49.84s =====================================================================

$ pylama netmiko                       
$ black --check netmiko
All done! ✨ 🍰 ✨
125 files would be left unchanged.
```

**Comment by DylanHamel** [comment]
Hi @ktbyers,
Did you plan to merge this request ?
Cheers,
Dylan

**Comment by ktbyers** [comment]
Yeah, let me see if I can get this done in the next few weeks.


Regards, Kirk

**Pull request merged**
