### PR TITLE
Added new version of local_space_available that works under Windows

### LINKED ISSUE #1207: Unable to SCP using Windows
When trying to copy a file from cisco_ios device to my local windows machine using SCP, I am getting this error:
```
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_functions.py", line 104, in file_transfer
    verifyspace_and_transferfile(scp_transfer)
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_functions.py", line 18, in verifyspace_and_transferfile
    if not scp_transfer.verify_space_available():
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_handler.py", line 160, in verify_space_available
    space_avail = self.local_space_available()
  File "C:\hbdata\network\lib\site-packages\netmiko\scp_handler.py", line 152, in local_space_available
    destination_stats = os.statvfs(".")
AttributeError: module 'os' has no attribute 'statvfs'
```
I am using Python 3.7.3 on Windows 10

### PR DESCRIPTION
**Pull request by bouchardh**
Fixe issue when SCP from cisco_ios to Windows workstation.

Closes #1207

### CODE REVIEW

**Comment by ktbyers** [comment]
@bouchardh I can probably fix the linting/black errors.

Regards, Kirk

**Comment by carlniger** [comment]
@bouchardh  Took a quick peak that this -- would you be able to refactor it to something more like this:

```
    def local_space_available(self):
        """Return space available on local filesystem."""
        if platform.system() == "Windows":
            import ctypes
            free_bytes = ctypes.c_ulonglong(0)
            ctypes.windll.kernel32.GetDiskFreeSpaceExW(
                ctypes.c_wchar_p("."), None, None, ctypes.pointer(free_bytes)
            )
            return free_bytes
        else: 
            destination_stats = os.statvfs(".")
            return destination_stats.f_bsize * destination_stats.f_bavail
```

And retest on windows? 

I think the above should work but just hacked it together real quick. This would be a smaller change and keep the pattern more consistent with the rest of Netmiko. 

Thanks!

**Comment by bouchardh** [comment]
@carlniger Looks much better this way. I will update the code and test.

On first look, I see that you have
`return free_bytes` 
instead of
`return free_bytes.value`
Are they the same?

Sorry if it sounds like a basic question, just starting in Python.

Thanks!

**Comment by bouchardh** [comment]
Hi,

I tested on Windows 10 with Python 3.7 and it did not work without the ".value",no error but no copy either. I finally figured out how to run black locally and it would have failed black checks again.

Here is the final code:
```
    def local_space_available(self):
        """Return space available on local filesystem."""
        if platform.system() == "Windows":
            import ctypes

            free_bytes = ctypes.c_ulonglong(0)
            ctypes.windll.kernel32.GetDiskFreeSpaceExW(
                ctypes.c_wchar_p("."), None, None, ctypes.pointer(free_bytes)
            )
            return free_bytes.value
        else:
            destination_stats = os.statvfs(".")
            return destination_stats.f_bsize * destination_stats.f_bavail
```
If it looks good to you, I will commit and push. Still trying to understand the workflow with git, github and the CI part.

Thanks again for your help and understanding!

**Comment by carlniger** [comment]
@bouchardh Looks good -- yep I just was jotting things down quick and probably missed that value bit, go ahead and push it and we'll confirm its all good/passing CI bits! Thanks!

**Pull request merged**
