### PR TITLE
Started adding PaloAlto support

### PR DESCRIPTION
**Pull request by GGabriele**
Hey,
I'm starting adding support for PaloAlto devices. I still have some issues with commit commands but I've already obtained some basic functionalities.

Also, send_command outputs doesn't look always the same and so I think that I should adjust some delay_factor somewhere. I'll dig it deeper.

### CODE REVIEW

**Comment by ktbyers** [comment]
@GGabriele For the ssh_dispatcher and class name, we are trying to standardize on a convention of

vendor_platform_transport for example:

cisco_ios_ssh
cisco_asa_ssh

Can you add platform into the naming for palo alto? Probably should be:

paloalto_panos_ssh

I am not that familiar with PA, however, so if something is more logical, just let me know.

**Comment by GGabriele** [comment]
Sure, it makes sense. So, should it be PaloAltoPanosSSH for class name instead?

**Comment by ktbyers** [comment]
Yes, that sounds fine.


Kirk

On Wed, Apr 27, 2016 at 1:13 PM, Gabriele <notifications@github.com> wrote:

> Sure, it makes sense. So, should it be PaloAltoPanosSSH for class name
> instead?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/pull/197#issuecomment-215213744>
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation

**Comment by GGabriele** [comment]
Done. Now all the basic functionalities should work, it support all the needed functions and commit as well.

I've tested it against `test_netmiko_config` and it passed all the checks except one, and against `test_netmiko_show` where some more failed. Probably I should still play with `strip_command` and `strip_prompt`.

**Comment by ktbyers** [comment]
@GGabriele Yes, let's try to get it working with all of the unit test. 

Let me know what unit tests are failing and I can see if I can spot the issue.

**Comment by GGabriele** [comment]
Hey @ktbyers, now `test_netmiko_show` is successful, I only had to add a `delay_factor` in tests. Instead, I receive this error with `test_netmiko_config`:

    ================================================================== FAILURES ===================================================================
    ______________________________________________________________ test_command_set _______________________________________________________________

    net_connect = <netmiko.paloalto.paloalto_panos_ssh.PaloAltoPanosSSH object at 0x7f596bc1dd50>
    commands = {'basic': 'show system info', 'config': ['set network vlan testing', 'set network vlan testingggg'], 'config_verification': 'run show vlan all', 'extended_output': 'show system info', ...}
    expected_responses = {'base_prompt': 'ntc@pa1', 'enable_prompt': 'ntc@pa1>', 'interface_ip': '10.0.0.90', 'multiple_line_output': 'logdb-version: 7.0.9', ...}
    
        def test_command_set(net_connect, commands, expected_responses):
            '''
            Test sending configuration commands
            '''
            print(1)
            config_commands = commands['config']
            support_commit = commands.get('support_commit')
            config_verify = commands['config_verification']
        
            print(2)
            net_connect.send_config_set(config_commands[0:1])
            if support_commit:
                net_connect.commit()
        
            print(3)
            cmd_response = expected_responses.get('cmd_response_init')
            config_commands_output = net_connect.send_command_expect(config_verify)
            if cmd_response:
                assert cmd_response in config_commands_output
            else:
    >           assert config_commands[0] in config_commands_output
    E           assert 'set network vlan testing' in '\ntotal vlan shown :                    12\n\nname                interface         virtual interface   \n---------------...30                  -                 \n40                  -                 \n50                  -                 \n\n'

Anyway, I think the reason is that I'm still inexperienced with PAN-OS cli and I'm using a wrong combination in `responses.yml` and `commands.yml`

**Comment by ktbyers** [comment]
When you execute the following on the PA (from the CLI):

set network vlan testingggg

Then what does the following show you?
run show vlan all

**Comment by GGabriele** [comment]
If we don't commit, the output would be something like this:

    ntc@pa1# run show vlan all

    total vlan shown :                    2

    name                interface         virtual interface
    --------------------------------------------------------------------------------
    test                -
    ntc                 -

Anyway, I've just modified responses.yml like this:

    paloalto_panos:
      base_prompt: ntc@pa1
      router_prompt: ntc@pa1>
      enable_prompt: ntc@pa1>
      interface_ip: '10.0.0.90'
      multiple_line_output: 'logdb-version: 7.0.9'
      version_banner: 'sw-version: 7.0.1'
      cmd_response_init: 'new_test'
      cmd_response_final: 'another_test'
 
 ..and commands.yml like this:

    paloalto_panos:
      version: "show system info | match version"
      basic: "show system info"
      extended_output: "show system info"
      config:
        - 'set network vlan new_test'
        - 'set network vlan another_test'
      support_commit: True
      config_verification: 'run show vlan all'

..and now passed all tests.

**Comment by ktbyers** [comment]
@GGabriele Does it pass the test_netmiko_commit tests also?

**Pull request merged**
