### PR TITLE
Add support for scp on Ubiquiti edgerouter

### PR DESCRIPTION
**Pull request by elavaud**
Adding SCP support for Ubiquit edgerouter

### CODE REVIEW

**Comment by ktbyers** [comment]
@elavaud Thanks for contributions. Let me try to review this in the next week.

**Comment by elavaud** [comment]
Thanks Kirk. Just corrected the linting on that PR.

**Comment by ktbyers** [comment]
This all looks good (reviewed by me today).

Did you run the Netmiko secure copy tests against this code. If so, can you post the unit test output into this PR?

Thanks for this contribution @elavaud

**Comment by ktbyers** [comment]
Any update on this? @elavaud

**Comment by elavaud** [comment]
@ktbyers sorry, priorities keep changing. Ubiquiti still in the pipe but at a much later date.

**Comment by ktbyers** [comment]
@elavaud I am going to close the PR...just create a new PR when you start working on this again.


Regards, Kirk

**Pull request closed without merging**
