### PR TITLE
Fix the pan-os acknowledgment banner issue

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
Can someone with a pan-os device test this proposed fix?

We need to test both when the acknowledgement banner exists and also when it doesn't exist.

**Comment by MoakiBE** [comment]
Hi @ktbyers , I'm interested in helping to figure this one out . Have multiple network automatisations running thanks to your work, so might as well try to give something back.  How do I go about testing this? I've tried replacing the paloalto_panos.py with your changed version, but this might not be enough. Could you advise on how to test this and what outputs you expect?

**Comment by ktbyers** [comment]
@MoakiBE Basically, panos has some sort of a feature which breaks the standard SSH login. It should look similar to the following:

```
        login as: admin
        
        Do you accept and acknowledge the statement above ? (yes/no) : yes
        Password:
```

So with this PR, Netmiko should properly handle that issue (if you have it configured on your device). Also it should not break standard login if you do not have it configured.

Can you test/verify this.


I will fix the merge conflicts now (so you can directly test it).

**Comment by MoakiBE** [comment]
Installed by using: pip install https://github.com/ktbyers/netmiko/archive/develop.zip
Confirmed that the files contain the correct code.
Turned off the acknowledge button on the firewalls, code still functions correctly.
Turned on the acknowledge button on the firewalls, and I got an authentication exception after enabling it.
How do I collect extra logging so this makes more sense to you?

**Comment by ktbyers** [comment]
@MoakiBE Install process would be:

```
git clone https://github.com/ktbyers/netmiko
cd netmiko
git fetch origin
git checkout -b panos_prompting origin/panos_prompting
# Install current directory as active code
pip install -e .
```

This code isn't merged so installing `develop.zip` wouldn't work.


Let me know if that install process works and what you see when you re-test it.


Thanks, Kirk

**Comment by MoakiBE** [comment]
Installation method worked flawless, I can see netmiko has been removed from default site-packages folder. Tried some aruba scripts, those still work fine. PaloAlto script fails with authentication exception in both scenario's now, something might be broken.

**Comment by ktbyers** [comment]
Yep, makes sense.

Can you post the exception stack trace that you are receiving.

Also can you show me what a manual CLI interaction looks like with banner acknowledgement enabled?

Thanks.

**Comment by MoakiBE** [comment]
CLI:
=============
login as: username
Pre-authentication banner message from server:
| WARNING: The use of this system is restricted to authorized users only.
| Unauthorized access, use, or modification of this system or of the data conta
> ined herein or in transmit to/from this system may subject you to criminal pr
> osecution.
| These systems and equipment are subject to monitoring to ensure proper perfor
> mance of applicable security features or procedures.
| Such monitoring may result in the acquisition, recording and analysis of all
> data being communicated, transmitted, processed or stored in this system by a
>  user. If monitoring reveals possible evidence of criminal activity, such evi
> dence may be provided to law enforcement personnel.
End of banner message from server
Keyboard-interactive authentication prompts from server:
| Do you accept and acknowledge the statement above ? (yes/no) : yes
| Password:
=============
Exceptions:
=============
Exception has occurred: BadAuthenticationType
Bad authentication type; allowed types: ['publickey', 'password', 'keyboard-interactive']
  File "C:\Temp\netmiko\netmiko\netmiko\paloalto\paloalto_panos.py", line 16, in _auth
    self._transport.auth_none(username)
  File "C:\Temp\netmiko\netmiko\netmiko\base_connection.py", line 967, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Temp\netmiko\netmiko\netmiko\base_connection.py", line 410, in _open
    self.establish_connection()
  File "C:\Temp\netmiko\netmiko\netmiko\base_connection.py", line 405, in __init__
    self._open()
  File "C:\Temp\netmiko\netmiko\netmiko\ssh_dispatcher.py", line 330, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "H:\Scripting\Python\Backup\PaloAlto\PaloAltoBackup.py", line 24, in sshsession
    ssh=netmiko.ConnectHandler(ip=ipaddress,device_type='paloalto_panos',username=user,password=passwd,global_delay_factor=2,blocking_timeout=16)

===

Exception has occurred: NetmikoAuthenticationException
Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: paloalto_panos x.x.x.x:22


Bad authentication type; allowed types: ['publickey', 'password', 'keyboard-interactive']
  File "C:\Temp\netmiko\netmiko\netmiko\base_connection.py", line 967, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "C:\Temp\netmiko\netmiko\netmiko\paloalto\paloalto_panos.py", line 16, in _auth
    self._transport.auth_none(username)

During handling of the above exception, another exception occurred:

  File "C:\Temp\netmiko\netmiko\netmiko\base_connection.py", line 405, in __init__
    self._open()
  File "C:\Temp\netmiko\netmiko\netmiko\ssh_dispatcher.py", line 330, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "H:\Scripting\Python\Backup\PaloAlto\PaloAltoBackup.py", line 24, in sshsession
    ssh=netmiko.ConnectHandler(ip=ipaddress,device_type='paloalto_panos',username=user,password=passwd,global_delay_factor=2,blocking_timeout=16)

**Comment by ktbyers** [comment]
Hmmmm, I will need to look at this some more. I looked at it yesterday, but not sure what is happening here.


Kirk

**Comment by Snackhous3** [comment]
> Hmmmm, I will need to look at this some more. I looked at it yesterday, but not sure what is happening here.
> 
> Kirk

I have password login issues too.  This is a systemic problem with Palo Alto and Paramiko. Here is a mention of what appears the be the issue some SSH servers and with Paramiko handling: https://github.com/paramiko/paramiko/issues/1476

After much testing and research, Palo Alto does not have a problem with the Banner itself it has a problem when you activate the "Force Admins to Acknowledge Login Banner" feature. It forces the 'yes/no' answer from "Do you accept and acknowledge the statement above? (yes/no)" question.

Output from my test:

ssh -vvv cli_user@192.168.50.100

image


I am experimenting on a fix but I need to wade through Paramiko first and find the time.

Kirk, let me know if I can assist on my end with output from the gear.


Thanks and let's try and fix this!

**Comment by ktbyers** [comment]
@Snackhous3 Yeah, the Paramiko issue you linked to https://github.com/paramiko/paramiko/issues/1476 references the solution we have implemented here, but for some reason it isn't working (where it has worked with a bunch of other platforms that do similar things).

@Snackhous3 is it possible for you to capture the Netmiko log file, but using the code implemented in this PR?

```
git fetch origin
git checkout -b panos_prompting origin/panos_prompting
pip install -e .
```

Logging setup is here:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by Snackhous3** [comment]
I am willing to do that, however I ran into this problem with my Paramiko code, not Netmiko. Earlier this week I read this and rewrote my attempts in Netmiko but would like to confirm the commands the OP and you suggest running for Netmiko.

Is this appropriate?

import sys
import netmiko
from netmiko import ConnectHandler

    pan_os = {
    'device_type': 'paloalto_panos',
    'host': '192.168.50.100',
    'username': pano_user,
    'password': pano_p
    }

    pan_os = netmiko.paloalto.paloalto_panos.PaloAltoPanosSSH(
    host='192.168.50.100',
    username=pano_user,
    password=pano_p
    )


    output = pan_os.send_command('show admins')
    print(output)

**Comment by ktbyers** [comment]
@Snackhous3 In Netmiko you should pretty much always use ConnectHandler to connect (and Netmiko will pick the correct class to use based on your device_type), so a minor update to your code is as follows:

```python
from netmiko import ConnectHandler

pan_os = {
    "device_type": "paloalto_panos",
    "host": "192.168.50.100",
    "username": "pano_user",
    "password": "pano_p",
}

# Pass in the device you defined above to ConnectHandler
ssh_conn = ConnectHandler(**pan_os)
output = ssh_conn.send_command("show admins")
print(output)
```

Note, I converted pano_user and pano_p over to strings for your username and password. I assume that is what you meant.



Regards,

Kirk

**Comment by Snackhous3** [comment]
@ktbyers 

Thank you.

Yes they are strings. Above code did not get copied.

**Comment by seanyoungberg** [comment]
Another interested party here. Testing with code from this PR and getting the same results. Any ideas or any data I can help gather?

`DEBUG:paramiko.transport:starting thread (client mode): 0x9f09c5e0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.7
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.7)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for x.x.x.48: b'9b0804dd01589af9bdddfd88ce5114ed'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Auth banner: b'DO YOU ACCEPT\n'
DEBUG:paramiko.transport:Authentication type (none) not permitted.
DEBUG:paramiko.transport:Allowed methods: ['publickey', 'password', 'keyboard-interactive']
DEBUG:paramiko.transport:EOF in transport thread
`

**Comment by ktbyers** [comment]
Okay, let me look at it.

**Comment by seanyoungberg** [comment]
Thanks @ktbyers ! I can give you connect details for a device if you want to test from your end. I messaged you on slack or reach out to sean.youngberg at gmail

**Comment by ktbyers** [comment]
@seanyoungberg Sounds good...just pinged you on Slack.


Kirk

**Comment by Snackhous3** [comment]
Whoa I completely forgot about this testing. Busy with work. Glad someone else picked it up.

Know what bypasses this issue? Using a PEM key.

Looks like the Palo SSH module rejects the initial password  (notice the send packet and receive packet types), intercepts the connection (violates RFC?), expects the word 'yes' as the password (three fails and connection fails). then moves on to the actual password input.

Probably adding a switch which lets Netmiko know the 'admin confirm' is on will work. Detect those send/receive packet types for the prompt, send a 'yes', confirm the actual prompt, and then send the password attempt.

**Comment by ktbyers** [comment]
Tested show commands both with the banner acknowledgement and without it:

```
DO YOU ACCEPT
Do you accept and acknowledge the statement above ? (yes/no) :
```

Testing output (with banner acknowledgement):

```
$ py.test -s -v -x test_netmiko_config.py --test_device pan_device
=========================================== test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 10 items                                                                                         

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode PASSED
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_config_set PASSED
test_netmiko_config.py::test_config_set_longcommand PASSED
test_netmiko_config.py::test_config_hostname PASSED
test_netmiko_config.py::test_config_from_file SKIPPED
test_netmiko_config.py::test_config_error_pattern SKIPPED
test_netmiko_config.py::test_disconnect PASSED

========================================= short test summary info ==========================================
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_config.py:114: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_config.py:126: No error_pattern defined.
================================= 8 passed, 2 skipped in 117.58s (0:01:57) =================================

[py39_netmiko] kbyers@pydev1 ~/netmiko/tests 
$ py.test -s -v -x test_netmiko_show.py --test_device pan_device
=========================================== test session starts ============================================
platform linux -- Python 3.9.5, pytest-5.1.2, py-1.10.0, pluggy-0.13.1 -- /home/kbyers/VENV/py39_netmiko/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/kbyers/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 24 items                                                                                         

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_terminal_width PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_timing_no_cmd_verify SKIPPED
test_netmiko_show.py::test_send_command PASSED
test_netmiko_show.py::test_send_command_no_cmd_verify SKIPPED
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED
test_netmiko_show.py::test_send_command_textfsm SKIPPED
test_netmiko_show.py::test_send_command_ttp SKIPPED
test_netmiko_show.py::test_send_command_genie SKIPPED
test_netmiko_show.py::test_send_multiline_timing SKIPPED
test_netmiko_show.py::test_send_multiline SKIPPED
test_netmiko_show.py::test_send_multiline_prompt SKIPPED
test_netmiko_show.py::test_send_multiline_simple SKIPPED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED
test_netmiko_show.py::test_disconnect_no_enable PASSED

========================================= short test summary info ==========================================
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:71: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:89: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:111: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:132: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:154: TTP template not existing for this platform
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:194: Genie not supported on this platform
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:214: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:230: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:255: <Skipped instance>
SKIPPED [1] /home/kbyers/netmiko/tests/test_netmiko_show.py:279: <Skipped instance>
===================================== 14 passed, 10 skipped in 49.42s ======================================

```

**Comment by ktbyers** [comment]
@seanyoungberg Thanks for access to a device.

**Comment by Snackhous3** [comment]
@seanyoungberg @ktbyers 

Kirk I saw you did a commit. Is the admin_auth login working with the recent changes or are you still testing?

**Comment by ktbyers** [comment]
@Snackhous3 Yes, this fix has been merged into the `develop` branch. 

I had a device to test against courtesy of @seanyoungberg so it should all be good to go.

**Comment by Snackhous3** [comment]
> @Snackhous3 Yes, this fix has been merged into the `develop` branch.
> 
> I had a device to test against courtesy of @seanyoungberg so it should all be good to go.

@ktbyers 

Got a traceback error, but it did connect and log into the palo fw. My "show admins" send_command did not appear in the logs. Please see below.

---------------------------------------------------------------------------------------------------------------------------


I installed the 'develop' branch

Used the following code:

`from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

pan_os = {
    "device_type": "paloalto_panos",
    "host": "192.168.50.100",
    "username": "pano_user",
    "password": "pano_p",
}

# Pass in the device you defined above to ConnectHandler
ssh_conn = ConnectHandler(**pan_os)
output = ssh_conn.send_command("show admins")
print(output)`

Console output is as follows:

`python3 devsuggeest_working_netmiko.py 
Traceback (most recent call last):
  File "devsuggeest_working_netmiko.py", line 15, in <module>
    ssh_conn = ConnectHandler(**pan_os)
  File "/home/don/repos/netmiko/netmiko/netmiko/ssh_dispatcher.py", line 339, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/don/repos/netmiko/netmiko/netmiko/base_connection.py", line 413, in __init__
    self._open()
  File "/home/don/repos/netmiko/netmiko/netmiko/base_connection.py", line 419, in _open
    self._try_session_preparation()
  File "/home/don/repos/netmiko/netmiko/netmiko/base_connection.py", line 858, in _try_session_preparation
    self.session_preparation()
  File "/home/don/repos/netmiko/netmiko/netmiko/paloalto/paloalto_panos.py", line 70, in session_preparation
    self.set_terminal_width(
  File "/home/don/repos/netmiko/netmiko/netmiko/base_connection.py", line 1213, in set_terminal_width
    output = self.read_until_pattern(pattern=pattern)
  File "/home/don/repos/netmiko/netmiko/netmiko/base_connection.py", line 630, in read_until_pattern
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 

Pattern not detected: 'set cli terminal width 500' in output.

Things you might try to fix this:
1. Adjust the regex pattern to better identify the terminating string. Note, in
many situations the pattern is automatically based on the network device's prompt.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
`

Attaching global log
[netmiko_global.log](https://github.com/ktbyers/netmiko/files/7018970/netmiko_global.log)

**Comment by ktbyers** [comment]
@Snackhous3 Does your device support this command?

`set cli terminal width 500`

You should open up a new issue as this isn't related to the banner acknowledgement behavior (i.e. this is all after SSH login).

**Comment by Snackhous3** [comment]
> @Snackhous3 Does this change / PR fix your issue?
> 
> #2455

The changes from 2455 do resolve that error. I do not get an output via log or console

Manual SSH login with 'show admins' command run:
```
ssh admin@192.168.50.100
Login Banner
Do you accept and acknowledge the statement above ? (yes/no) : yes
Password: 
Last login: Thu Aug 19 21:19:03 2021 from 192.168.50.232



Number of failed attempts since last successful login: 0


admin@PA-220> show admins

Admin                           From   Client Session-start      Idle-for 
--------------------------------------------------------------------------
admin                 192.168.50.232      CLI 08/19 21:17:41     00:08:54s
admin                 192.168.50.232      CLI 08/19 21:11:13     00:15:22s
admin                 192.168.50.232      CLI 08/19 21:16:30     00:10:05s
admin                 192.168.50.232      CLI 08/19 21:15:20     00:11:16s
admin                 192.168.50.232      CLI 08/19 21:19:06     00:07:29s
admin                 192.168.50.232      CLI 08/19 21:26:32     00:00:00s
admin                 192.168.50.232      CLI 08/19 21:18:22     00:08:14s

admin@PA-220>
```


Attached log with 2455 changes:
[netmiko_global_2455.log](https://github.com/ktbyers/netmiko/files/7019154/netmiko_global_2455.log)

**Comment by ktbyers** [comment]
@Snackhous3 Is this device really, really slow?

**Comment by Snackhous3** [comment]
> @Snackhous3 Is this device really, really slow?
> 
> It looks like your device really, really lags what is sent down the SSH channel...and consequently is causing send_command to fail (i.e. Netmiko sends `show admins` and then the PA device responds with the prompt from a while back.

@ktbyers 

Running 'show admins' is immediate. Time might be 30ms? With my Paramiko code I did give it a time.sleep() delay between send-and-receive. You are right that seems to be my issue here, yeah.

**Custom Paramiko def for waiting:**
```
def send_and_wait(s, cmd):
    s.send(cmd +"\n")
    time.sleep(4)
    output = s.recv(10000).decode('utf_8').split('\n')
    print (output)
```

Is there a delay option in Netmiko to manually adjustable delay from send-and-receive?

**Current test code:**
``` 
# Pass in the device you defined above to ConnectHandler
ssh_conn = ConnectHandler(**pan_os)
output = ssh_conn.send_command("show admins")
print(output)

```

PA-220 physical device
https://www.paloaltonetworks.com/resources/pa-series-next-generation-firewalls-hardware-architectures

**Comment by ktbyers** [comment]
time.sleep(4) is a very large sleep.

Does it work with a more reasonable 1/2 a second sleep?

**Comment by ktbyers** [comment]
Let's try to work out a general solution as if you are running into it with a physical device other people will too...

**Comment by Snackhous3** [comment]
@ktbyers 

For sure.  I just built an entire fully automated deployment solution (tested on all device classes) and you have to either factor in a send-and-receive delay or wait for output to come back (and even then just a smidge more time to output).

The management plane get VERY busy, and slower, when it is running 24/7 heavy traffic.

**Comment by Snackhous3** [comment]
> sleep?

I missed this question, my apologies.

I did 4 seconds during testing for console list output reading and just left it there.

Just tested 0.5 seconds and it worked just fine on a PA-220 with no traffic flowing through it, no GUI users active, and no commits happening.

**Comment by Snackhous3** [comment]
To be clear, time.sleep() does not fix my output in the Netmiko code, only in Paramiko.

**Comment by Snackhous3** [comment]
@ktbyers 

Kirk, are you working on the timing issue here or do I need to open up a new issue?

**Comment by ktbyers** [comment]
@Snackhous3 I forgot about this...you should definitely open a new issue (or this issue will just get lost)...since it is a different issue, and the original issue is now closed.

**Comment by ktbyers** [comment]
@Snackhous3 Just got tied up in other things...so don't let me forget about this issue.

**Comment by seanyoungberg** [comment]
The PA-220 device is notoriously slow, more so than the VMs even. I had to add some sleep calls in my code as well to wait for the buffer to complete, but didn't investigate much. So agreed this is a worthy of another issue.

The admin banner issue from this PR is working great though!

**Comment by Snackhous3** [comment]
**First I installed the 'develop' branch**
```
git fetch origin
pip install -e .
```


**Used the following code:**

```from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

pan_os = {
    "device_type": "paloalto_panos",
    "host": "192.168.50.100",
    "username": "pano_user",
    "password": "pano_p",
}

ssh_conn = ConnectHandler(**pan_os)
output = ssh_conn.send_command("show admins")
print(output)
```



**Console output is as follows:**

```

**First I installed the 'develop' branch**
```
git fetch origin
pip install -e .
```


**Used the following code:**

```from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='netmiko_global.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

pan_os = {
    "device_type": "paloalto_panos",
    "host": "192.168.50.100",
    "username": "pano_user",
    "password": "pano_p",
}

ssh_conn = ConnectHandler(**pan_os)
output = ssh_conn.send_command("show admins")
print(output)
```



**Console output is as follows:**
```
$ python3 devsuggeest_working_netmiko.py 

$
```

**Attaching Global Log**

[netmiko_global_2455.log](https://github.com/ktbyers/netmiko/files/7103338/netmiko_global_2455.log)

**Comment by Snackhous3** [comment]
When I add more commands the 'show admins' output to terminal but the other commands do not execute correctly.


**Used the following code:**

```from netmiko import ConnectHandler
import logging

logging.basicConfig(filename='netmiko_global_a2455.log', level=logging.DEBUG)
logger = logging.getLogger("netmiko")

pan_os = {
    "device_type": "paloalto_panos",
    "host": "192.168.50.100",
    "username": "pano_user",
    "password": "pano_p",
}

ssh_conn = ConnectHandler(**pan_os)
output = ssh_conn.send_command("show admins")
print(output)
output = ssh_conn.send_command("show interface all")
print(output)
output = ssh_conn.send_command("show dhcp client state all")
print(output)
```




**Console output is as follows:**
```
$ python3 devsuggeest_working_netmiko.py 

$
```

**Attaching Global Log**

[netmiko_global_b2455.log](https://github.com/ktbyers/netmiko/files/7103391/netmiko_global_b2455.log)

**Pull request merged**
