### PR TITLE
Adds Ciena SAOS support (experimental)

### PR DESCRIPTION
**Pull request by rodecker**
This adds support for Ciena SAOS carrier Ethernet switches. SAOS does not have enable or config mode.

### CODE REVIEW

**Comment by ktbyers** [comment]
@rodecker Can you run the standard unit tests against this driver? This should be both the 'show' and 'config' unit tests. There might be some that will fail...need to be skipped given that there is no enable or config mode.

See this document:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md


Let me know if you need assistance.

**Comment by rodecker** [comment]
@ktbyers test_netmiko_show.py passes. Indeed I need to disable test_config_mode and test_exit_config_mode for test_netmiko_config.py to pass.

**Comment by ktbyers** [comment]
@rodecker Okay, so all the tests in `show` pass and all the tests in `config` pass except for `test_config_mode` and `test_exit_config_mode`?

**Comment by rodecker** [comment]
@ktbyers yes

**Pull request merged**
