### PR TITLE
Add a config command rate-limiter

### PR DESCRIPTION
**Pull request by aedwardstx**
Rate-limits commands sent on the channel based on prompts seen.

Arbiter is a send command rate limiter that maintains the command buffer at `bucket_size` number of commands. It would allow sending of bucket_size commands, when it sees X prompts come back, it allows another X command(s). If it doesn’t see a prompt come back in some time, it figures “I must have missed it” and sends another command. This continues until the config set is depleted.

ref #1058

Recent relevant article: https://blog.ipspace.net/2019/01/not-so-fast-ansible-cisco-ios-cant-keep.html

### CODE REVIEW

**Comment by ktbyers** [comment]
FYI, the issue is probably not relevant i.e. that issue is probably not an input buffer overload problem (I don't think there are enough commands to overload the input buffer and the description of the failure is not consistent with an input buffer overload).

Also FWIW I couldn't reproduce the issue described (though I only tested with a copy-and-paste and not with Ansible's ios_config).

**Comment by aedwardstx** [comment]
I agree the article does not exactly fit the situation but I chose to reference it as it provides a bit of background. The referenced issue is on point for what's being addressed in the PR.

**Comment by ktbyers** [comment]
How would the PR fix the referenced issue? I don't think it would even at a command buffer size of 1?

**Comment by aedwardstx** [comment]
Issue #1058 describes a situation where `send_config_set()` sent hundreds of lines to a Nexus3k. A large part of that config was an ACL. The device took a long time to process each ACL line and ended up tail dropping ACL config lines in the limited command buffer. The article touches on this a little bit.
Arbiter watches for prompts in the output to know when the device has processed a command indicating that its safe to send another. It allows for `bucket_size` commands to be unacknowledged at a time. 

There's two basic approaches to solve for this:
- Send one line after seeing one prompt with no outstanding lines
  - This approach leaves the device idle for periods of time in between commands
- Send X lines and allow another to be sent for each prompt seen <- Arbiter
  - This is as fast as `send_config_set()` method of sending the commands in bulk without the risk of overrunning the command buffer.

**Comment by ktbyers** [comment]
@aedwardstx I know this is not exactly what you were looking for, but we fixed this problem by essentially going to a command-buffer of one i.e. Netmiko won't write the next command in send_config_set until the last one has been properly echoed/handled by the device.

That fix is in the Netmiko develop branch and there is a modification to the behavior here:

https://github.com/ktbyers/netmiko/pull/1447

I need to make some slight changes to that PR1447 as I have hard-coded a terminating char '#' in there, but I will update that shortly.

**Pull request closed without merging**
