### PR TITLE
Support APRESIA Systems AEOS

### PR DESCRIPTION
**Pull request by nmisaki**
Added support APRESIA Systems AEOS
http://www.apresia.jp/en/products/ent/series/10g_1g.html#ap15000-64xl-psr

Test Results
```
(venv) [nmisaki@dev01 tests]$ ./test_apresia_aeos.sh
Starting tests...good luck:
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.6.4, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /home/nmisaki/python/netmiko-devel/venv/bin/python3
cachedir: ../.pytest_cache
rootdir: /home/nmisaki/python/netmiko-devel/netmiko, inifile:
plugins: pylama-7.4.3
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                          [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                             [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                          [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                     [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                                                     [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                             [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                            [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                           [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                     [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                            [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                             [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                              [100%]

========================================================================== 12 passed in 46.92 seconds ===========================================================================
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.6.4, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /home/nmisaki/python/netmiko-hp/venv/bin/python3
cachedir: ../.pytest_cache
rootdir: /home/nmisaki/python/netmiko-devel/netmiko, inifile:
plugins: pylama-7.4.3
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                           [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                           [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                           [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                      [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                                                           [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                                                    [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                            [100%]

=========================================================================== 7 passed in 54.33 seconds ===========================================================================
(venv) [nmisaki@dev01 tests]$
```

### CODE REVIEW

**Comment by ktbyers** [comment]
@nmisaki Thanks for submitting this.

So there is no way on the Apresia devices to disable the prompting for `--- More ---`?

I assume that is why you had to overwrite the standard send_command method?


Kirk

**Comment by nmisaki** [comment]
@ktbyers Yes. Apresia AEOS have neither `no-more` nor `terminal length 0` in user/privileged mode.
Only in configuration mode we can.
That's why I had to do so.

```
apresia15k# show run | ?
  begin    Begin with the line that matches
  exclude  Exclude lines that match
  include  Include lines that match

apresia15k# terminal ?
  monitor  Copy debug output to the current terminal line
  no       Negate a command or set its defaults

apresia15k# terminal no ?
  monitor  Copy debug output to the current terminal line

apresia15k# configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
apresia15k(config)# terminal length ?
  0  No pausing
```

**Comment by ktbyers** [comment]
Okay, I think it would probably be better if we went into configuration mode and disabled paging (i.e. executed `terminal length 0` in config mode.

This is more consistent with what we have done elsewhere in Netmiko.

Also I am worried about unexpected behavior we are going to get from not doing this.

Any objections to doing this?

The negative is that a configuration change is being made, but I think that is better than trying to manually handle the paging.

**Comment by nmisaki** [comment]
@ktbyers Thanks.
> The negative is that a configuration change is being made

I was just worried about that.
But, surely consistency is very important.
I will try it as you say.

**Comment by nmisaki** [comment]
@ktbyers I changed it as suggested to you.
I think that it has become quite simple indeed.
All the tests are passed.

**Comment by ktbyers** [comment]
Thanks @nmisaki!

**Pull request merged**
