### PR TITLE
adding arista&juniper telnet class

### PR DESCRIPTION
**Pull request by nmisaki**
device type
- arista_eos_telnet
- juniper_junos_telnet

### CODE REVIEW

**Comment by ktbyers** [comment]
@nmisaki Did you test that both of Juniper and Arista work properly using telnet?

Any possibility you could run the unit tests against them (using telnet for the transport)?

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by nmisaki** [comment]
I tested on following.

- Arista: vEOS-4.16.13M on Virtualbox

- Juniper: ffp-12.1X47-D15.4 on Virtualbox

```
[vagrant@localhost tests]$ ./test_arista_telnet.sh
Starting tests...good luck:
Arista
======================================= test session starts =======================================
platform linux -- Python 3.6.4, pytest-3.4.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.6
cachedir: ../.pytest_cache
rootdir: /home/vagrant/python/netmiko, inifile:
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                            [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                               [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                            [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                       [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                       [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                               [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                              [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                             [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                       [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                              [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                               [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                [100%]

=================================== 12 passed in 41.50 seconds ====================================
======================================= test session starts =======================================
platform linux -- Python 3.6.4, pytest-3.4.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.6
cachedir: ../.pytest_cache
rootdir: /home/vagrant/python/netmiko, inifile:
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                             [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                             [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                             [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                        [ 57%]
test_netmiko_config.py::test_command_set PASSED                                             [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                      [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                              [100%]

==================================== 7 passed in 21.73 seconds ====================================
```

```
[vagrant@localhost tests]$ ./test_juniper_telnet.sh
Starting tests...good luck:
======================================= test session starts =======================================
platform linux -- Python 3.6.4, pytest-3.4.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.6
cachedir: ../.pytest_cache
rootdir: /home/vagrant/python/netmiko, inifile:
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                            [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                               [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                            [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                       [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                       [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                               [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                              [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                             [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                       [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                              [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                               [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                [100%]

=================================== 12 passed in 39.33 seconds ====================================
======================================= test session starts =======================================
platform linux -- Python 3.6.4, pytest-3.4.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.6
cachedir: ../.pytest_cache
rootdir: /home/vagrant/python/netmiko, inifile:
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                             [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                             [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                             [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                        [ 57%]
test_netmiko_config.py::test_command_set PASSED                                             [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                      [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                              [100%]

==================================== 7 passed in 66.01 seconds ====================================
======================================= test session starts =======================================
platform linux -- Python 3.6.4, pytest-3.4.1, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3.6
cachedir: ../.pytest_cache
rootdir: /home/vagrant/python/netmiko, inifile:
collected 15 items

test_netmiko_commit.py::test_ssh_connect PASSED                                             [  6%]
test_netmiko_commit.py::test_config_mode PASSED                                             [ 13%]
test_netmiko_commit.py::test_commit_base PASSED                                             [ 20%]
test_netmiko_commit.py::test_commit_confirm PASSED                                          [ 26%]
test_netmiko_commit.py::test_confirm_delay PASSED                                           [ 33%]
test_netmiko_commit.py::test_no_confirm PASSED                                              [ 40%]
test_netmiko_commit.py::test_clear_msg PASSED                                               [ 46%]
test_netmiko_commit.py::test_commit_check PASSED                                            [ 53%]
test_netmiko_commit.py::test_commit_comment PASSED                                          [ 60%]
test_netmiko_commit.py::test_commit_andquit PASSED                                          [ 66%]
test_netmiko_commit.py::test_commit_label PASSED                                            [ 73%]
test_netmiko_commit.py::test_commit_label_comment PASSED                                    [ 80%]
test_netmiko_commit.py::test_commit_label_confirm PASSED                                    [ 86%]
test_netmiko_commit.py::test_exit_config_mode PASSED                                        [ 93%]
test_netmiko_commit.py::test_disconnect PASSED                                              [100%]

=================================== 15 passed in 435.83 seconds ===================================
```

**Comment by ktbyers** [comment]
Nice, I will see if I can get this reviewed this weekend or early next week (hopefully, this weekend).

**Comment by ktbyers** [comment]
Thanks for this contribution.

**Pull request merged**
