### PR TITLE
Add option for progress display during SCP

### PR DESCRIPTION
**Pull request by TomCos**
Just pushing the progress callback at SCP object establish.

### CODE REVIEW

**Comment by ktbyers** [comment]
It looks like you would also need to add the `progress` function somewhere (i.e. that function/method needs to exist).

https://stackoverflow.com/questions/49657776/python-scpclient-copy-progress-check

You can fix or leave this PR open and I can potentially fix.


Regards, Kirk

**Comment by TomCos** [comment]
I don't think the function needs to exist if the variable defaults to None, as it also does in the SCPClient code (https://github.com/jbardin/scp.py/blob/master/scp.py) and my merge is based off his examples on the readme page (https://github.com/jbardin/scp.py).

My thought process was, there are probably 1000 different ways people are going to want the data displayed, from print, to logging, writing to files, etc, all different formats.  I figured leave it as None and let the users make their own progress function displays.

Saw the errors from the build, just fixed them.

**Comment by TomCos** [comment]
It's also worth discussing, my implementation just into the establish_scp_conn function is because of the issues I was facing here (https://github.com/ktbyers/netmiko/issues/922), so I was skipping the file_transfer class and just calling the function in FileTransfer directly.  Thinking in the context of a normal implementation, the progress variable is going to need to be carried through BaseFileTransfer as well, correct?

**Comment by ktbyers** [comment]
You still have some minor lint errors that you need to fix here.

**Comment by bradh11** [comment]
In reviewing the paramiko implementation it seems to have a function called progress_tracker which is a member of the SCPClient class.  This seems to be related to what you are trying to do. 

‘’’
def _progress_tracker(self, method, basename, size, file_pos, peername):
        #count number of arguments
        count = method.__code__.co_argcount
        if count == 3:
            method(basename, size, file_pos)
        elif count == 4:
            method(basename, size, file_pos, peername)
        else:
            #do not break, just skip
            pass
‘’’

**Comment by ktbyers** [comment]
This PR looks like it was never fully implemented so I am going to close. Feel free to re-open/re-create if you want to re-implement it.

**Comment by assadniang** [comment]
Was wondering if this has been implemented in netmiko scp function, and how to use it.

**Comment by ktbyers** [comment]
No, there never was a working implementation of this built.

**Pull request closed without merging**
