### PR TITLE
Aruba AOS-CX vendor module

### PR DESCRIPTION
**Pull request by pietos**
We created and tested on both a physical and virtual Aruba AOSCX the functionality of this vendor module.

### CODE REVIEW

**Comment by ktbyers** [comment]
@pietos Can you post the `show` and `config` test output here (it is good for me to have a record of this so I can circle back to it, if issues come up).

**Comment by pietos** [comment]
@ktbyers I will close this request and do it over with the pylama fixes and the required configuration examples

**Comment by pietos** [comment]
**Show**
`commands = ["show version"]`

**Output**
`-----------------------------------------------------------------------------
ArubaOS-CX
(c) Copyright Hewlett Packard Enterprise Development LP
-----------------------------------------------------------------------------
Version      : Virtual.10.04.1000
Build Date   :
Build ID     : ArubaOS-CX:Virtual.10.04.1000:3f752af05989:202003111738       
Build SHA    : 3f752af05989429ecb5ca258aa66dbd282f60ab2
Active Image :

Service OS Version :
BIOS Version       :`

**Config**
```
config_commands = [
        'vlan 10',
        'name Test_VLAN',
        'exit',
        'interface vlan 10',
        'ip address 192.168.10.1/24',
        'exit',
        'write memory'
    ]
```

**Output**

` configure term
switch(config)#  vlan 10
switch(config-vlan-10)# name Test_VLAN
VLAN name Test_VLAN is already used for VLAN 10.
switch(config-vlan-10)# exit
switch(config)# interface vlan 10
switch(config-if-vlan)# ip address 192.168.10.1/24
switch(config-if-vlan)# exit
switch(config)# write memory
Configuration changes will take time to process, please be patient.
switch(config)#  end
switch#`

**Comment by ktbyers** [comment]
Superseded by:

https://github.com/ktbyers/netmiko/pull/3430

**Pull request merged**
