### PR TITLE
Add Mellanox MLNX-OS Switch support

### PR DESCRIPTION
**Pull request by vasorokin**
The original content of netmiko/mellanox was not working with Mellanox MLNX-OS based switches, like SX1410, SX1700. I guess the original code is for the older devices.
I tested what I made here from OpenStack's networking-generic-switch Neutron plugin.

### CODE REVIEW

**Comment by vasorokin** [comment]
Committed the change https://review.openstack.org/#/c/642565/1 to OpenStack networking-generic-switch project, which is on hold (work in progress) now, waiting for this change to be reviewed/accepted

**Comment by ktbyers** [comment]
@vasorokin FYI, this project is licensed under the MIT-license so you would need to strip out the Apache2 license references included in `netmiko/mellanox/mellanox__mlnxos_ssh.py`.

cc: @juliakreger 

Regards, Kirk

**Comment by ktbyers** [comment]
@vasorokin @juliakreger 

I am probably going to try to do a Netmiko release very shortly (release to pypi). If you can get back to me on the above Apache2 license removal I can see if I can get this included.

Regards, Kirk

**Comment by vasorokin** [comment]
Kirk, I have removed the license from netmiko/mellanox/mellanox__mlnxos_ssh.py
Regards,
--Vlad

**Comment by ktbyers** [comment]
Thanks @vasorokin. Will try to review now.

**Comment by ktbyers** [comment]
Replacing this PR with the updated PR here:

https://github.com/ktbyers/netmiko/pull/1267

**Pull request closed without merging**
