### PR TITLE
Add basic viptela support

### PR DESCRIPTION
**Pull request by benmcbenben**
Just adding in support to connect to Viptela devices

### CODE REVIEW

**Comment by ktbyers** [comment]
Can you include the test results for both the show commands and the config commands. More details can be found here:

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

**Comment by ktbyers** [comment]
@benmcbenben Any update on posting the test output?

Thanks, Kirk

**Comment by benmcbenben** [comment]
Sorry about the delay, 
see test output below:

```(netmiko_test) [bhohnke@hostname tests]$ py.test -v test_netmiko_config.py --test_device cisco_viptela
===================================================================== test session starts ======================================================================
platform linux -- Python 3.6.8, pytest-5.1.2, py-1.8.1, pluggy-0.13.1 -- /home/bhohnke/netmiko_test/bin/python3
cachedir: .pytest_cache
rootdir: /home/bhohnke/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 8 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                          [ 12%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                          [ 25%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                          [ 37%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                     [ 50%]
test_netmiko_config.py::test_config_set PASSED                                                                                                           [ 62%]
test_netmiko_config.py::test_config_set_longcommand PASSED                                                                                               [ 75%]
test_netmiko_config.py::test_config_from_file PASSED                                                                                                     [ 87%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                           [100%]

====================================================================== 8 passed in 15.20s ======================================================================
(netmiko_test) [bhohnke@hostname tests]$ py.test -v test_netmiko_show.py --test_device cisco_viptela
===================================================================== test session starts ======================================================================
platform linux -- Python 3.6.8, pytest-5.1.2, py-1.8.1, pluggy-0.13.1 -- /home/bhohnke/netmiko_test/bin/python3
cachedir: .pytest_cache
rootdir: /home/bhohnke/netmiko, inifile: setup.cfg
plugins: pylama-7.7.1
collected 19 items

test_netmiko_show.py::test_disable_paging PASSED                                                                                                         [  5%]
test_netmiko_show.py::test_terminal_width PASSED                                                                                                         [ 10%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                            [ 15%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                         [ 21%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                    [ 26%]
test_netmiko_show.py::test_send_command PASSED                                                                                                           [ 31%]
test_netmiko_show.py::test_cmd_verify_decorator PASSED                                                                                                   [ 36%]
test_netmiko_show.py::test_send_command_global_cmd_verify PASSED                                                                                         [ 42%]
test_netmiko_show.py::test_send_command_juniper SKIPPED                                                                                                  [ 47%]
test_netmiko_show.py::test_send_command_textfsm SKIPPED                                                                                                  [ 52%]
test_netmiko_show.py::test_send_command_genie SKIPPED                                                                                                    [ 57%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                            [ 63%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                           [ 68%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                          [ 73%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                    [ 78%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                           [ 84%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                            [ 89%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                             [ 94%]
test_netmiko_show.py::test_disconnect_no_enable PASSED                                                                                                   [100%]

=================================================================== short test summary info ====================================================================
SKIPPED [1] /home/bhohnke/netmiko/tests/test_netmiko_show.py:132: <Skipped instance>
SKIPPED [1] /home/bhohnke/netmiko/tests/test_netmiko_show.py:153: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] /home/bhohnke/netmiko/tests/test_netmiko_show.py:178: Genie not supported on this platform
================================================================ 16 passed, 3 skipped in 57.63s ================================================================
(netmiko_test) [bhohnke@hostname tests]$```

**Comment by benmcbenben** [comment]
Above tests were done with d0ac704 - forgot to commit + push changes before commenting

**Comment by lamoni** [comment]
Any update on this being accepted?

Thanks!

**Comment by ktbyers** [comment]
Superseded by:

https://github.com/ktbyers/netmiko/pull/2243

**Pull request closed without merging**
