### PR TITLE
New Driver for H3C

### PR DESCRIPTION
**Pull request by ktbyers**
@TanY0Y0

### CODE REVIEW

**Comment by ktbyers** [comment]
@TanY0Y0 I assume this is using "Comware7" OS?

**Comment by TanY0Y0** [comment]
> @TanY0Y0 I assume this is using "Comware7" OS?

ok

**Comment by ktbyers** [comment]
@TanY0Y0 Is that a yes, that the underlying OS here is essentially ComWare7?

**Comment by TanY0Y0** [comment]
> @TanY0Y0 Is that a yes, that the underlying OS here is essentially ComWare7?

yes,its OS is comware7

**Comment by ktbyers** [comment]
@TanY0Y0 Are you still interested in having this H3C driver included in Netmiko?

**Comment by TanY0Y0** [comment]
@ktbyers yes，I still interested in

**Comment by ktbyers** [comment]
I think we would have to start again on this driver.

I apologize that I couldn't get this done earlier. If you want to resubmit it, I would be open to it, but totally understand if you are unwilling to do it.

**Pull request closed without merging**
