### PR TITLE
Add code 'ESC[c' into method 'strip_ansi_escape_codes'

### PR DESCRIPTION
**Pull request by max-dw-i**
Some 'MikroTik' devices add ANSI escape codes 'ESC[c' to the end of the output when in 'safe-mode'

### CODE REVIEW

**Comment by ktbyers** [comment]
@max-dw-i Can you show me an output capture with this character sequence? I am not seeing/finding any references to `ESC[c` looking at ANSI reference codes?

**Comment by max-dw-i** [comment]
Yeah, I couldn't find either but as far as I understand there might be not typical codes.
Here is an output example:
1. We send `\u0018` (ctrl-x) to enter the `safe-mode` via `send_command_timing`:
```
[Safe Mode taken]
[user@HOSTNAME] <SAFE>
```
2. Then run any command:
```
/system identity print

name: HOSTNAME
\x1b[9999B[user@HOSTNAME] <SAFE> \x1b[c
```

**Comment by ktbyers** [comment]
Looks like it is probably:

```
Device Status
The following codes are used for reporting terminal/display settings, and vary depending on the implementation:
Query Device Code	<ESC>[c
Requests a Report Device Code response from the device.
```

From here:

https://www2.ccs.neu.edu/research/gpc/VonaUtils/vona/terminal/vtansi.htm

**Comment by ktbyers** [comment]
Superceded by: 

https://github.com/ktbyers/netmiko/pull/3457

**Pull request closed without merging**
