### PR TITLE
Updated Adva drivers

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@guychilton77 Can you regression test this with your test device(s). Most of these items we covered in the other PR. I also fixed some mypy issues and made a few other things more consistent with typical/common Netmiko patterns.

**Comment by ktbyers** [comment]
Note, I changed the `device_type` names to:

```python
    "adva_fsp150f2": AdvaAosFsp150F2SSH,
    "adva_fsp150f3": AdvaAosFsp150F3SSH,
```

Format should be:

```
vendor_platform_transport
```

Where transport defaults to `ssh` automatically.

If there are better names for the `platform` field just let me know.

**Comment by guychilton77** [comment]
@ktbyers perfect thanks for your help and work on this. No issues with the device_type name changes, they look perfect. I'll try and get the regression testing done over the weekend or first thing Monday morning and will post up the results

**Comment by ktbyers** [comment]
I am going to go ahead and `merge` this into `develop` and then we can do an additional PR if there are additional changes that are necessary.

**Comment by guychilton77** [comment]
@ktbyers Regression tests passed fine.

(net_reg_tests) [guych@spiderbaby test_adva]$ ./adva_tests.sh 
Starting tests...good luck:
Adva F3
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/guych/projects_python/netmiko, configfile: setup.cfg
plugins: cov-3.0.0, mock-3.6.1
collected 32 items                                                                                                                                                                                                                                                                       

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_terminal_width PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_timing_no_cmd_verify SKIPPED
test_netmiko_show.py::test_send_command PASSED
test_netmiko_show.py::test_send_command_no_cmd_verify SKIPPED
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED
test_netmiko_show.py::test_send_command_textfsm SKIPPED (TextFSM/ntc-templates not supported on this platform)
test_netmiko_show.py::test_send_command_ttp SKIPPED (TTP template not existing for this platform)
test_netmiko_show.py::test_send_command_genie SKIPPED (Genie not supported on this platform)
test_netmiko_show.py::test_send_multiline_timing SKIPPED
test_netmiko_show.py::test_send_multiline_timing_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_prompt_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_simple_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_timing_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline_prompt_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline_simple_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline SKIPPED
test_netmiko_show.py::test_send_multiline_prompt SKIPPED
test_netmiko_show.py::test_send_multiline_simple SKIPPED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED
test_netmiko_show.py::test_disconnect_no_enable SKIPPED

================================================================================================================================ short test summary info =================================================================================================================================
SKIPPED [1] test_netmiko_show.py:70: Skipped
SKIPPED [1] test_netmiko_show.py:88: Skipped
SKIPPED [1] test_netmiko_show.py:110: Skipped
SKIPPED [1] test_netmiko_show.py:131: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] test_netmiko_show.py:153: TTP template not existing for this platform
SKIPPED [1] test_netmiko_show.py:193: Genie not supported on this platform
SKIPPED [1] test_netmiko_show.py:213: Skipped
SKIPPED [1] test_netmiko_show.py:226: Skipped
SKIPPED [1] test_netmiko_show.py:245: Skipped
SKIPPED [1] test_netmiko_show.py:262: Skipped
SKIPPED [1] test_netmiko_show.py:282: Skipped
SKIPPED [1] test_netmiko_show.py:301: Skipped
SKIPPED [1] test_netmiko_show.py:316: Skipped
SKIPPED [1] test_netmiko_show.py:332: Skipped
SKIPPED [1] test_netmiko_show.py:352: Skipped
SKIPPED [1] test_netmiko_show.py:374: Skipped
SKIPPED [1] test_netmiko_show.py:399: Skipped
SKIPPED [1] test_netmiko_show.py:423: Skipped
SKIPPED [1] test_netmiko_show.py:525: Skipped
============================================================================================================================ 13 passed, 19 skipped in 34.07s =============================================================================================================================
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/guych/projects_python/netmiko, configfile: setup.cfg
plugins: cov-3.0.0, mock-3.6.1
collected 12 items                                                                                                                                                                                                                                                                       

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode SKIPPED (Platform doesn't support config mode.)
test_netmiko_config.py::test_exit_config_mode SKIPPED (Platform doesn't support config mode.)
test_netmiko_config.py::test_config_set PASSED
test_netmiko_config.py::test_config_set_longcommand PASSED
test_netmiko_config.py::test_config_hostname PASSED
test_netmiko_config.py::test_config_from_file PASSED
test_netmiko_config.py::test_config_error_pattern PASSED
test_netmiko_config.py::test_banner SKIPPED (No banner defined.)
test_netmiko_config.py::test_global_cmd_verify SKIPPED (No banner defined.)
test_netmiko_config.py::test_disconnect PASSED

================================================================================================================================ short test summary info =================================================================================================================================
SKIPPED [1] test_netmiko_config.py:39: Platform doesn't support config mode.
SKIPPED [1] test_netmiko_config.py:48: Platform doesn't support config mode.
SKIPPED [1] test_netmiko_config.py:164: No banner defined.
SKIPPED [1] test_netmiko_config.py:197: No banner defined.
============================================================================================================================= 8 passed, 4 skipped in 43.30s ==============================================================================================================================
Adva F2
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/guych/projects_python/netmiko, configfile: setup.cfg
plugins: cov-3.0.0, mock-3.6.1
collected 32 items                                                                                                                                                                                                                                                                       

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_terminal_width PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_timing_no_cmd_verify SKIPPED
test_netmiko_show.py::test_send_command PASSED
test_netmiko_show.py::test_send_command_no_cmd_verify SKIPPED
test_netmiko_show.py::test_complete_on_space_disabled SKIPPED
test_netmiko_show.py::test_send_command_textfsm SKIPPED (TextFSM/ntc-templates not supported on this platform)
test_netmiko_show.py::test_send_command_ttp SKIPPED (TTP template not existing for this platform)
test_netmiko_show.py::test_send_command_genie SKIPPED (Genie not supported on this platform)
test_netmiko_show.py::test_send_multiline_timing SKIPPED
test_netmiko_show.py::test_send_multiline_timing_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_prompt_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_simple_adva_f3 SKIPPED
test_netmiko_show.py::test_send_multiline_timing_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline_prompt_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline_simple_adva_f2 SKIPPED
test_netmiko_show.py::test_send_multiline SKIPPED
test_netmiko_show.py::test_send_multiline_prompt SKIPPED
test_netmiko_show.py::test_send_multiline_simple SKIPPED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED
test_netmiko_show.py::test_disconnect_no_enable SKIPPED

================================================================================================================================ short test summary info =================================================================================================================================
SKIPPED [1] test_netmiko_show.py:70: Skipped
SKIPPED [1] test_netmiko_show.py:88: Skipped
SKIPPED [1] test_netmiko_show.py:110: Skipped
SKIPPED [1] test_netmiko_show.py:131: TextFSM/ntc-templates not supported on this platform
SKIPPED [1] test_netmiko_show.py:153: TTP template not existing for this platform
SKIPPED [1] test_netmiko_show.py:193: Genie not supported on this platform
SKIPPED [1] test_netmiko_show.py:213: Skipped
SKIPPED [1] test_netmiko_show.py:226: Skipped
SKIPPED [1] test_netmiko_show.py:245: Skipped
SKIPPED [1] test_netmiko_show.py:262: Skipped
SKIPPED [1] test_netmiko_show.py:282: Skipped
SKIPPED [1] test_netmiko_show.py:301: Skipped
SKIPPED [1] test_netmiko_show.py:316: Skipped
SKIPPED [1] test_netmiko_show.py:332: Skipped
SKIPPED [1] test_netmiko_show.py:352: Skipped
SKIPPED [1] test_netmiko_show.py:374: Skipped
SKIPPED [1] test_netmiko_show.py:399: Skipped
SKIPPED [1] test_netmiko_show.py:423: Skipped
SKIPPED [1] test_netmiko_show.py:525: Skipped
============================================================================================================================ 13 passed, 19 skipped in 24.50s =============================================================================================================================
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.9.7, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/guych/projects_python/netmiko, configfile: setup.cfg
plugins: cov-3.0.0, mock-3.6.1
collected 12 items                                                                                                                                                                                                                                                                       

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode SKIPPED (Platform doesn't support config mode.)
test_netmiko_config.py::test_exit_config_mode SKIPPED (Platform doesn't support config mode.)
test_netmiko_config.py::test_config_set PASSED
test_netmiko_config.py::test_config_set_longcommand PASSED
test_netmiko_config.py::test_config_hostname PASSED
test_netmiko_config.py::test_config_from_file PASSED
test_netmiko_config.py::test_config_error_pattern PASSED
test_netmiko_config.py::test_banner SKIPPED (No banner defined.)
test_netmiko_config.py::test_global_cmd_verify SKIPPED (No banner defined.)
test_netmiko_config.py::test_disconnect PASSED

================================================================================================================================ short test summary info =================================================================================================================================
SKIPPED [1] test_netmiko_config.py:39: Platform doesn't support config mode.
SKIPPED [1] test_netmiko_config.py:48: Platform doesn't support config mode.
SKIPPED [1] test_netmiko_config.py:164: No banner defined.
SKIPPED [1] test_netmiko_config.py:197: No banner defined.
============================================================================================================================= 8 passed, 4 skipped in 14.87s ==============================================================================================================================

**Comment by ktbyers** [comment]
@guychilton77 Thanks for all your help on this.

**Pull request merged**
