### PR TITLE
Patch for enter issue on IP Infusion

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@mvsiva Does it work if we do this?

**Comment by ktbyers** [comment]
Okay, bummer...

I will switch it back more like your original solution, I sort of wanted to avoid that as I didn't want to duplicate an almost exact replica of the `enable()` method...but it looks like that is what we probably need to do.

Although maybe I will code that as an optional argument directly into the parent method.

**Comment by ktbyers** [comment]
@mvsiva Okay, I made updates to this. Can you test and see if this new fix works?

This also relates to this Aruba issue which has a very similar issue:

https://github.com/ktbyers/netmiko/issues/890

**Comment by mvsiva** [comment]
@ktbyers Yes.. All tests for ssh and telnet passing now with both enable password being set and not set.. Thanks.

**Pull request merged**
