### PR TITLE
Added support Dell EMC Networking OS10

### PR DESCRIPTION
**Pull request by skg-net**
Added support Dell EMC Networking OS10

Test Results:
=======
(netmiko) skg@skg-dev ~/dev/github/netmiko/tests $ ./test_dellos10.sh
Starting tests...good luck:
Dell EMC Networking dellos10
===================================================================================================================================================================== test session starts =====================================================================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /home/skg/.virtualenvs/netmiko/bin/python
cachedir: ../.pytest_cache
rootdir: /home/skg/dev/github/netmiko, inifile:
plugins: pylama-7.4.3
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                                                                                                                                                                                                        [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                                                                                                                                                                                           [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                                                                                                                                                                                        [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                                                                                                                                                                                   [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                                                                                                                                                                                                                                   [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                                                                                                                                                                                           [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                                                                                                                                                                                          [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                                                                                                                                                                                                         [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                                                                                                                                                                                   [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                                                                                                                                                                                          [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                                                                                                                                                                                           [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                                                                                                                                                                                                            [100%]

================================================================================================================================================================= 12 passed in 31.93 seconds ==================================================================================================================================================================
===================================================================================================================================================================== test session starts =====================================================================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /home/skg/.virtualenvs/netmiko/bin/python
cachedir: ../.pytest_cache
rootdir: /home/skg/dev/github/netmiko, inifile:
plugins: pylama-7.4.3
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                                                                                                                                                                                                         [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                                                                                                                                                                                                         [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                                                                                                                                                                                                         [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                                                                                                                                                                                                    [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                                                                                                                                                                                                                                         [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                                                                                                                                                                                                                                  [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                                                                                                                                                                                                          [100%]

================================================================================================================================================================== 7 passed in 46.59 seconds ==================================================================================================================================================================
(netmiko) skg@skg-dev ~/dev/github/netmiko/tests $

### CODE REVIEW

**Comment by skg-net** [comment]
@ktbyers Please take a look at it and merge.

**Comment by ktbyers** [comment]
@skg-net Sounds good. Let me review this.

**Comment by skg-net** [comment]
@ktbyers Any update ??

**Comment by ktbyers** [comment]
Haven't got to it...let me see if I can get to it by the end of this weekend.

**Comment by ktbyers** [comment]
@skg-net This looks fine for the main driver. For the file copy operation, can you run this set of unit tests against it and post the results here:

```
py.test -v test_netmiko_scp.py --test_device dell_device
```

This runs the following set of tests:

```
def test_scp_put(scp_fixture):
def test_remote_space_available(scp_fixture, expected_responses):
def test_local_space_available(scp_fixture):
def test_verify_space_available_put(scp_fixture):
def test_remote_file_size(scp_fixture):
def test_md5_methods(scp_fixture):
def test_disconnect(scp_fixture):
def test_verify_space_available_get(scp_fixture_get):
def test_scp_get(scp_fixture_get):
def test_md5_methods_get(scp_fixture_get):
def test_disconnect_get(scp_fixture_get):
def test_file_transfer(scp_file_transfer):
```

Also for this device what is the process for saving running-config to startup-config. We recently added a `save_config` method so it would be good to get this covered as well.

Here is what is looks like for the Dell Force10 driver (DNOS9):

```
    def save_config(self, cmd='copy running-configuration startup-configuration', confirm=False):
        """Saves Config"""
        return super(DellForce10SSH, self).save_config(cmd=cmd, confirm=confirm)
```

If you show me what it looks like on the CLI (the `copy run start` I can create it quickly).

**Comment by skg-net** [comment]
Thanks, @ktbyers, I will run the test and provide you the results. Looks like it needs some additional changes. For the save_config the same command should work for os10 as well.

**Comment by ktbyers** [comment]
@skg-net I think I will probably merge the SSH support and then you can resubmit the SCP separately (that way that part is done).

If you get it updated before then, we can just couple them together.

**Comment by skg-net** [comment]
##Test Results:
(netmiko) skg@skg-dev ~/dev/github/netmiko/tests $ ./test_dellos10.sh
Starting tests...good luck:
Dell EMC Networking dellos10
===================================================================================================================================================================== test session starts =====================================================================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /home/skg/.virtualenvs/netmiko/bin/python
cachedir: ../.pytest_cache
rootdir: /home/skg/dev/github/netmiko, inifile:
plugins: pylama-7.4.3
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED                                                                                                                                                                                                                                                                                                        [  8%]
test_netmiko_show.py::test_ssh_connect PASSED                                                                                                                                                                                                                                                                                                           [ 16%]
test_netmiko_show.py::test_ssh_connect_cm PASSED                                                                                                                                                                                                                                                                                                        [ 25%]
test_netmiko_show.py::test_send_command_timing PASSED                                                                                                                                                                                                                                                                                                   [ 33%]
test_netmiko_show.py::test_send_command_expect PASSED                                                                                                                                                                                                                                                                                                   [ 41%]
test_netmiko_show.py::test_base_prompt PASSED                                                                                                                                                                                                                                                                                                           [ 50%]
test_netmiko_show.py::test_strip_prompt PASSED                                                                                                                                                                                                                                                                                                          [ 58%]
test_netmiko_show.py::test_strip_command PASSED                                                                                                                                                                                                                                                                                                         [ 66%]
test_netmiko_show.py::test_normalize_linefeeds PASSED                                                                                                                                                                                                                                                                                                   [ 75%]
test_netmiko_show.py::test_clear_buffer PASSED                                                                                                                                                                                                                                                                                                          [ 83%]
test_netmiko_show.py::test_enable_mode PASSED                                                                                                                                                                                                                                                                                                           [ 91%]
test_netmiko_show.py::test_disconnect PASSED                                                                                                                                                                                                                                                                                                            [100%]

================================================================================================================================================================= 12 passed in 38.10 seconds ==================================================================================================================================================================
===================================================================================================================================================================== test session starts =====================================================================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /home/skg/.virtualenvs/netmiko/bin/python
cachedir: ../.pytest_cache
rootdir: /home/skg/dev/github/netmiko, inifile:
plugins: pylama-7.4.3
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED                                                                                                                                                                                                                                                                                                         [ 14%]
test_netmiko_config.py::test_enable_mode PASSED                                                                                                                                                                                                                                                                                                         [ 28%]
test_netmiko_config.py::test_config_mode PASSED                                                                                                                                                                                                                                                                                                         [ 42%]
test_netmiko_config.py::test_exit_config_mode PASSED                                                                                                                                                                                                                                                                                                    [ 57%]
test_netmiko_config.py::test_command_set PASSED                                                                                                                                                                                                                                                                                                         [ 71%]
test_netmiko_config.py::test_commands_from_file PASSED                                                                                                                                                                                                                                                                                                  [ 85%]
test_netmiko_config.py::test_disconnect PASSED                                                                                                                                                                                                                                                                                                          [100%]

================================================================================================================================================================== 7 passed in 49.83 seconds ==================================================================================================================================================================
===================================================================================================================================================================== test session starts =====================================================================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /home/skg/.virtualenvs/netmiko/bin/python
cachedir: ../.pytest_cache
rootdir: /home/skg/dev/github/netmiko, inifile:
plugins: pylama-7.4.3
collected 12 items

test_netmiko_scp.py::test_scp_put PASSED                                                                                                                                                                                                                                                                                                                [  8%]
test_netmiko_scp.py::test_remote_space_available PASSED                                                                                                                                                                                                                                                                                                 [ 16%]
test_netmiko_scp.py::test_local_space_available PASSED                                                                                                                                                                                                                                                                                                  [ 25%]
test_netmiko_scp.py::test_verify_space_available_put PASSED                                                                                                                                                                                                                                                                                             [ 33%]
test_netmiko_scp.py::test_remote_file_size PASSED                                                                                                                                                                                                                                                                                                       [ 41%]
test_netmiko_scp.py::test_md5_methods PASSED                                                                                                                                                                                                                                                                                                            [ 50%]
test_netmiko_scp.py::test_disconnect PASSED                                                                                                                                                                                                                                                                                                             [ 58%]
test_netmiko_scp.py::test_verify_space_available_get PASSED                                                                                                                                                                                                                                                                                             [ 66%]
test_netmiko_scp.py::test_scp_get PASSED                                                                                                                                                                                                                                                                                                                [ 75%]
test_netmiko_scp.py::test_md5_methods_get PASSED                                                                                                                                                                                                                                                                                                        [ 83%]
test_netmiko_scp.py::test_disconnect_get PASSED                                                                                                                                                                                                                                                                                                         [ 91%]
test_netmiko_scp.py::test_file_transfer PASSED                                                                                                                                                                                                                                                                                                          [100%]

================================================================================================================================================================= 12 passed in 53.92 seconds ==================================================================================================================================================================
(netmiko) skg@skg-dev ~/dev/github/netmiko/tests $

**Comment by skg-net** [comment]
@ktbyers Please check and merge

**Comment by skg-net** [comment]
@ktbyers can you please check and merge

**Comment by ktbyers** [comment]
@skg-net I merged this with a few changes. You might want to review my changes and regression test them.

A few questions:

Why is self.folder_name needed?
```
self.folder_name = '/config'
```

**Pull request merged**
