### PR TITLE
Ruckus fastiron does not reliably enter enable mode. #1125

### PR DESCRIPTION
**Pull request by zeropacket**
I fixed the while loop and limit it to only two tries. I also fixed my issue with my local repo.

### CODE REVIEW

**Comment by ktbyers** [comment]
@zeropacket Can you provide some more details on the underlying issue? I.E. what was not working.

Thanks, Kirk

**Comment by zeropacket** [comment]
This commit fixes the while loop based on issue #1125. The original while loop would not catch the password prompt at the correct time reliably. This caused it dumping the password into the command prompt and not into the password field. Below is a example of a failed attempt. 

SSH@ICX7450-LAB>enable
Password:
Error - Incorrect username or password.
SSH@ICX7450-LAB>PASSWORD123

Invalid input -> PASSWORD123
Type ? for a list
SSH@ICX7450-LAB>skip-page-display

Invalid input -> skip-page-display
Type ? for a list
SSH@ICX7450-LAB>SSH@ICX7450-LAB>

SSH@ICX7450-LAB>

**Comment by ktbyers** [comment]
@zeropacket I made an updated PR here:

https://github.com/ktbyers/netmiko/pull/1225

Let me know if you see any issues with it.

**Comment by zeropacket** [comment]
This PR works but if the password entered wrong it dumps the password into CLI.  PR I submitted doesn't have that issue. 


SSH@ICX7450-LAB>

SSH@ICX7450-LAB>

SSH@ICX7450-LAB>

SSH@ICX7450-LAB>enable

Password:
Error - Incorrect username or password.
SSH@ICX7450-LAB>PASSWORD123

Invalid input -> PASSWORD123
Type ? for a list
SSH@ICX7450-LAB>enable

Password:
Error - Incorrect username or password.
SSH@ICX7450-LAB>

SSH@ICX7450-LAB>exit

**Pull request closed without merging**
