### PR TITLE
IP Infusion OcNOS Support

### PR DESCRIPTION
**Pull request by ktbyers**
Some updates to the original PR.

### CODE REVIEW

**Comment by ktbyers** [comment]
@mvsiva I am going to go ahead and merge this. If you see issues with it (when you test), just let me know.

**Comment by mvsiva** [comment]
Hi Kirk, Seeing strange behavior while running tests after I did a fresh clone of your develop branch.  While running 'test_ipinfusion.sh' ( SSH connection tests) , 'test_strip_prompt" fails. I see that the output of the 'send_command_timing' contains the 'prompt' as well.   Strangely, this works fine with 'test_ipinfusion_telnet.sh'(telnet connection tests. 

Attaching the logs for your reference. 
[test_ipinfusion.sh.txt](https://github.com/ktbyers/netmiko/files/2262458/test_ipinfusion.sh.txt)
[test_ipinfusion_telnet.sh.txt](https://github.com/ktbyers/netmiko/files/2262459/test_ipinfusion_telnet.sh.txt)

**Comment by mvsiva** [comment]
Confirmed that the behavior is due to the 'default_enter' value. 
```
#! /usr/bin/env python3
from netmiko import ConnectHandler

ipi1 = {
    'device_type': 'ipinfusion_ocnos',
    'ip':   '10.12.39.95',
    'username': 'ocnos',
    'password': 'ocnos',
    'default_enter': '\n'
    }

ipi2 = {
    'device_type': 'ipinfusion_ocnos',
    'ip':   '10.12.39.95',
    'username': 'ocnos',
    'password': 'ocnos',
    'default_enter': '\r\n'
    }


all_devices = [ipi1, ipi2]

for device in all_devices:
    cli_session = ConnectHandler(**device)
    output = cli_session.send_command('show clock')
    print("Output:", output)

```

While executing the above piece of code the output generated is as follows. 
```
osboxes@osboxes:~/scripts$ ./testShowClock.py
Output: 12:49:34  UTC Mon Aug 06 2018
Output: 12:49:39  UTC Mon Aug 06 2018
rtr1>
osboxes@osboxes:~/scripts$
```

**Comment by mvsiva** [comment]
With 'default_enter' as '\n'  
```
DEBUG:netmiko:write_channel: b'show clock\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: show clock^M^M
13:51:50  UTC Mon Aug 06 2018^M
rtr1>

```
With 'default_enter' as '\r\n'  
```
DEBUG:netmiko:write_channel: b'show clock\r\n'
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel: show clock^M^M
13:48:11  UTC Mon Aug 06 2018^M
rtr1>^M^M
rtr1>

```

**Pull request merged**
