### PR TITLE
added "post-login-banner" fix for Fortinet

### PR DESCRIPTION
**Pull request by jaaacck**

### CODE REVIEW

**Comment by jaaacck** [comment]
- closing to fix CI/DC errors

**Comment by carlniger** [comment]
@ktbyers this looks reasonable to me (pretty much same as the procurve setup you mentioned in the issue)

**Comment by louis-oui** [comment]
@ktbyers is the fix accepted ? Thank you for your help

**Comment by jaaacck** [comment]
Can this get pushed through soon please?

**Comment by louis-oui** [comment]
@ktbyers I am using this fix for several without issue. Could you push the fix ?

**Pull request merged**
