### PR TITLE
Add FortiAnalyzer compatibility

### PR DESCRIPTION
**Pull request by Hyperion60**
FortiAnalyzer CLI use '>' as prompt, but actual pattern doesn't read it.

Example of FortiAnalyzer CLI :
```
> get system status
System:
        Version:              FACVM v6.2.1-build0552,201030 (GA)
        Branch point:         0552
        Architecture:         64-bit
        Serial number:        FAC-VMTM21006510
        System time:          Thu Aug 11 18:29:39 2022 up 169 days,  2:14
        Disk Usage:           0 GB
        Disk Size:            57 GB

HA Status:
        Enabled:              No
        Node Type:
        Role:                 Disabled
        Status:               Disabled
        Cluster size:
        Heartbeat interface:
        Priority:
        Node-Specific Gateway:
        Peer:
>
```

### CODE REVIEW

**Comment by Hyperion60** [comment]
I just tested, it works also with FortiAuthenticator and FortiManager

**Comment by ktbyers** [comment]
@Hyperion60 Are you still interested/willing to work on this issue?

**Comment by Hyperion60** [comment]
Yes

**Comment by dpinyol** [comment]
Hi,
Same issue in FortiAuthenticator:

  File "/home/dani/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1368, in set_base_prompt
    raise ValueError(f"Router prompt not found: {repr(prompt)}")
ValueError: Router prompt not found: '>'

**Comment by ktbyers** [comment]
@Hyperion60 Can you run Netmiko config and show test suite against a FortiAnalyzer device using this code.

The test process is here.

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

@dpinyol Does the `FortiAuthenticator` work with the code referenced here?

**Comment by Hyperion60** [comment]
I could work on it from the end of the week. My job has the priority.

**Comment by ktbyers** [comment]
@Hyperion60 Let me know if you can post the Netmiko test output into this PR.

**Comment by ktbyers** [comment]
PR is unfortunately no longer active...so closing.

**Pull request closed without merging**
