### PR TITLE
feat: add fsos v1 & v2 ssh connector

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
Implement FSOS v1 & v2 connector for napalm fsos driver
https://github.com/napalm-automation-community/napalm-fsos-ssh/issues/17

### CODE REVIEW

**Comment by ktbyers** [comment]
FYI @M0NsTeRRR I need to reconcile this PR with this PR here (since they are partially implementing the same thing).

https://github.com/ktbyers/netmiko/pull/3231

CC @shrank also.

**Comment by ktbyers** [comment]
@M0NsTeRRR @shrank Are the Fiberstore FSOS for the S3200 and the FSOS v2 the same thing (as far as operating system/behaviors)?

The driver implemented for Fiberstore S3200 needed a special SSH login handler (as it looked like, from the code, that the standard SSH login would not work)? Is this something that is S3200 specific or common to FSOS V2?

**Comment by M0NsTeRRR** [comment]
Hello,

My PR is related to v1 and v2 and has been tested on S3900 24T4S (v1, v2 not supported) and S3900 48T6S-R (v2). I don't know if this PR works on this switch because I don't know if it runs the same OS. FS is known for using differents OS on theirs switches. For example on Napalm some switches doesnt need my SSH driver because they have JSON RPC.
I've checked the release notes of [FSOS S3200](https://resource.fs.com/mall/doc/20230602170313965pk8.pdf) and it's run 1.0.X. Mine is running v1.7.6 [FSOS S3900 24T4S](https://resource.fs.com/mall/doc/20230605152743utgl3s.pdf).
As I see its differents OS and as I understand we should prefix ssh connector with FS series (S3200, S3900 etc...) with theirs versions.

Regards,

**Comment by shrank** [comment]
I will have a device available for testing next week. I just got a configuration snippet from our FS sales rep that might enable proper SSH authentication. We might still need the special login handler to access the switch running the default configuration, but that could just be a fallback method.

I will also ask her if there are names for the different firmware platforms. In the config file header, they seem to call it "KT-NOS": 

```
SYSTEM CONFIG FILE ::= BEGIN
! System Description: KT-NOS S3200-8MG4S-U Switch
! System Version: v1.0.1.14
! System Name: 28-255-s3200
```

**Comment by M0NsTeRRR** [comment]
> I will have a device available for testing next week. I just got a configuration snippet from our FS sales rep that might enable proper SSH authentication. We might still need the special login handler to access the switch running the default configuration, but that could just be a fallback method.
> 
> I will also ask her if there are names for the different firmware platforms. In the config file header, they seem to call it "KT-NOS":
> 
> ```
> SYSTEM CONFIG FILE ::= BEGIN
> ! System Description: KT-NOS S3200-8MG4S-U Switch
> ! System Version: v1.0.1.14
> ! System Name: 28-255-s3200
> ```

I've different config header, FS just buy switches and rebrand them under theirs names they don't manufacture it. Ok so let's wait next week :)

```
!<Version>0.0.2</Version>
```

**Comment by shrank** [comment]
The SSH config commands didn't work, it looks like None-Auth is the only option for the 3200 model. 

Here is the answer about the different FSOS platforms: "different software platforms do not have different names, you can call them with part numbers." 

I guess it's fine to call them s3200,s3900 etc

**Comment by ktbyers** [comment]
Yeah, the most logical naming from a Netmiko perspective is probably (given what @M0NsTeRRR and @shrank described above):

```
fiberstore_fsos-s3200
fiberstore_fsos-s3900v1
fiberstore_fsos-s3900v2
```

The underscore is the separator between vendor and network os (so the network os here becomes fsos-s3200, fsos-s3900v1, etc).

I will see if I can update though it might be a few weeks.

**Comment by ktbyers** [comment]
Yes, just leave this PR here and I will see if I can reconcile the three drivers (using this PR as the base for the two referenced in it).

**Comment by M0NsTeRRR** [comment]
Hello @ktbyers any news ? :)

**Comment by ktbyers** [comment]
@M0NsTeRRR Nope, but finished a large project so might have more time. Let me see if I can work on this in the next month.

**Comment by M0NsTeRRR** [comment]
Hello @ktbyers any news about this PR ? :smile:

**Comment by M0NsTeRRR** [comment]
I moved away from Netmiko to Paramiko. Feel free to open a new PR with this code if someone is willing to support it.

**Pull request closed without merging**
