### PR TITLE
Add Allied Telesis AlliedWare Plus Support

### PR DESCRIPTION
**Pull request by openmymai**

### CODE REVIEW

**Review by openmymai — COMMENTED** [review]
I have done testing with AT x930 switch and it works properly by the following code:

```
import xlrd
import os
import time
import netmiko
from netmiko import ConnectHandler
import sys
 
def run_script(excel_file, script_file, print_list):
    workbook = xlrd.open_workbook(excel_file)
    sheet = workbook.sheet_by_index(0)
    for index in range(1, sheet.nrows):
        hostname = sheet.row(index)[0].value
        ip = sheet.row(index)[1].value
        username = sheet.row(index)[2].value
        password = sheet.row(index)[3].value
        device = {'device_type':"awplus_telnet", 'ip': ip, 'username': username, 'password': password}
        if print_list == "1":
            print("run script to", hostname)
            try:
               net_connect = ConnectHandler(**device)
               net_connect.send_config_from_file(script_file)
               print(" script  done for", hostname)
               net_connect.disconnect()
            except Exception as e:
             print(e)
        else:
            print ("|", hostname, "|",ip,"|", username,"|", password,"|")
            print(" ----------------------------")
            print(" Press OK to show the script !")
            input()
            print(script_file)
            print(" ----------------------------")
 
print(" #### welcome to Allied Telesis script automation tool ####") 
print(" #### ----------------------------------------- ####") 
 
excel_file = sys.argv[1]
script_file = sys.argv[2]
 
run_script(excel_file,script_file, "0")
 
print(" Press OK to run the script !")
 
input()
 
run_script(excel_file,script_file, "1")
```

**Comment by openmymai** [comment]
It completely not work with Cisco IOS Base!!
It work with BaseConnection.

**Comment by ktbyers** [comment]
Naming should be `company_network-os`.

Also can you run the standard Netmiko tests against the driver?

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md


Thanks for the contribution.

**Comment by openmymai** [comment]
Thank you very much for your recommendation.
I will test and update very soon.

**Comment by ktbyers** [comment]
Superseded by https://github.com/ktbyers/netmiko/pull/2136

**Pull request closed without merging**
