### PR TITLE
Add support for Dell PowerConnect where Telnet is used.  

### PR DESCRIPTION
**Pull request by broncofan**
Tested with Dell 8024.

```
# py.test -v test_netmiko_config.py --test_device dell_powerconnect_telnet -x
=====================test session starts ==================
platform linux -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /usr/local/bin/python3.5
cachedir: .cache
rootdir: /usr/local/lib/python3.5/site-packages/netmiko-1.2.8-py3.5.egg/tests, inifile:
collected 7 items

test_netmiko_config.py::test_ssh_connect PASSED
test_netmiko_config.py::test_enable_mode PASSED
test_netmiko_config.py::test_config_mode PASSED
test_netmiko_config.py::test_exit_config_mode PASSED
test_netmiko_config.py::test_command_set PASSED
test_netmiko_config.py::test_commands_from_file PASSED
test_netmiko_config.py::test_disconnect PASSED

==================7 passed in 14.49 seconds ==================
# py.test -v test_netmiko_show.py --test_device dell_powerconnect_telnet -x
=====================test session starts ==================
platform linux -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0 -- /usr/local/bin/python3.5
cachedir: .cache
rootdir: /usr/local/lib/python3.5/site-packages/netmiko-1.2.8-py3.5.egg/tests, inifile:
collected 12 items

test_netmiko_show.py::test_disable_paging PASSED
test_netmiko_show.py::test_ssh_connect PASSED
test_netmiko_show.py::test_ssh_connect_cm PASSED
test_netmiko_show.py::test_send_command_timing PASSED
test_netmiko_show.py::test_send_command_expect PASSED
test_netmiko_show.py::test_base_prompt PASSED
test_netmiko_show.py::test_strip_prompt PASSED
test_netmiko_show.py::test_strip_command PASSED
test_netmiko_show.py::test_normalize_linefeeds PASSED
test_netmiko_show.py::test_clear_buffer PASSED
test_netmiko_show.py::test_enable_mode PASSED
test_netmiko_show.py::test_disconnect PASSED

==================12 passed in 29.00 seconds ==================
```

### CODE REVIEW

**Comment by ktbyers** [comment]
@broncofan Need to fix the Python linter failures (see above Travis failures).

**Comment by broncofan** [comment]
@ktbyers  Sorry about that, new to python.  Should be good to go now.

**Comment by ktbyers** [comment]
@broncofan Why does the SSH driver use the command "terminal datadump" to disable paging and the telnet driver uses "terminal length 0".

Are these different PowerConnect Platforms?

**Comment by ktbyers** [comment]
@broncofan Also, note, I replaced the telnet_login code with a super call back to the telnet_login code in the Cisco IOS driver. 

As far as I could tell it was identical except for two checks which should never get hit.

Let me know if you see any issues with this.

https://github.com/ktbyers/netmiko/commit/a4d5c0130ac0b29a656e9c52e31f16b64a318163

**Comment by broncofan** [comment]
@ktbyers  The Dell PowerConnect 8024 that I am using is version 5.0.1.3.  Telnet is enabled by default and SSH is available, but must be explicitly enabled.  For my switch, terminal length 0 works for both Telnet and SSH.  "terminal datadump" is not a valid command on my switch with the current firmware.  I would be curious as to what switch and version he used to test the SSH functionality.  Sounds like we will have a conflict if someone attempts to use the SSH code with the 8024 switch.

Looks like he used the 5524, which I don't have any to test.  Might see if @rverchere can check the 5524 to see if terminal length 0 will work for that platform.

**Comment by ktbyers** [comment]
Okay, I have created an issue for this. We might need to split out separate platforms if meaningful differences.

**Comment by rverchere** [comment]
Hi,

I'm using Dell PowerConnect 5524 with version 4.1.0.15.

The command `terminal length 0` does not exist on this version:

```
SW-1# terminal
  datadump             dump all output of a show command without prompting
  history              Enable and control the command history function
  no                   negate the command history function
```

**Comment by ktbyers** [comment]
@rverchere Okay, thanks. 

We will need to make separate platform distinctions in Netmiko to differentiate them.

**Pull request merged**
