### PR TITLE
Added new docs & corrected existing docstrings.

### PR DESCRIPTION
**Pull request by OzNetNerd**
Quite a few gems are hidden in the source code. This PR is aimed at raising awareness of their existence.

### CODE REVIEW

**Comment by ktbyers** [comment]
Thanks let me see if I can review this in the next few weeks. I would try to do it quicker, but I am worried I won't get to it before then.

**Comment by OzNetNerd** [comment]
No worries at all @ktbyers. I removed the build directory from the PR. Now it is a lot easier to read through. If you accept the PR, you can then generate and commit the docs.

**Comment by carlmontanari** [comment]
@OzNetNerd have you had a chance to check out the README and docs since the migration to pdoc3? Still a work in progress for sure but hopefully it addresses some of the stuff you were trying to add/clarify. Let us know and we can maybe close this and open a quick new one to add in any additional docstring/clarifications?

**Comment by ktbyers** [comment]
I am going to close this as I think this was replaced by the newer docs solution. If there are fixes modifications that need to be made we should do it upon that base.

Sorry this PR was stuck for so long.

**Pull request closed without merging**
