### PR TITLE
refactor, pep257, pep8

### PR DESCRIPTION
**Pull request by supertylerc**
Testing all methods:

```python
 ❯ python                                                                                                                                                                                       [15:59:03]
Python 2.7.9 (default, Dec 13 2014, 15:13:49)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netmiko
>>> params = {"device_type": "juniper",
...           "ip": "ngfw1",
...           "username": "ansible",
...           "password": "Ansible"}
>>> dispatcher = netmiko.ssh_dispatcher(device_type=params["device_type"])
>>> dev = dispatcher(**params)
SSH connection established to ngfw1:22
Interactive SSH session established
>>> results = dev.config_mode()
>>> print(results)
configure
Entering configuration mode
Users currently editing the configuration:
  root terminal p0 (pid 1295) on since 2015-03-07 23:10:57 UTC, idle 00:19:03
      [edit]

[edit]
ansible@bananas#
>>> results = dev.send_command("set system host-name apples")
>>> print(results)


>>> results = dev.commit()
>>> print(results)
commit and-quit
commit complete
Exiting configuration mode

ansible@apples>
>>> results = dev.config_mode()
>>> print(results)
configure
Entering configuration mode
Users currently editing the configuration:
  root terminal p0 (pid 1295) on since 2015-03-07 23:10:57 UTC, idle 00:19:37
      [edit]

[edit]
ansible@apples#
>>> results = dev.send_command("run show interfaces terse | match inet")
>>> print(results)

ge-0/0/0.0              up    up   inet     10.0.2.15/24
sp-0/0/0.0              up    up   inet
                                   inet6
sp-0/0/0.16383          up    up   inet     10.0.0.1            --> 10.0.0.16
ge-0/0/1.0              up    up   inet     172.16.0.1/31
ge-0/0/2.0              up    up   inet     192.168.0.200/24
lo0.16384               up    up   inet     127.0.0.1           --> 0/0
lo0.16385               up    up   inet     10.0.0.1            --> 0/0

[edit]
ansible@apples#
>>> results = dev.exit_config_mode()
>>> print(results)
exit
Exiting configuration mode

ansible@apples>
>>> results = dev.disconnect()
>>> print(results)
None
>>> ^D
```

### CODE REVIEW

**Comment by supertylerc** [comment]
I was unable to run the tests in `tests/test_juniper.*` due to it requiring modules that are not included, such as `DEVICE_CREDS`.

```
 ❯ python tests/test_juniper_srx.py                                                                                                                                                             [16:03:57]
Traceback (most recent call last):
  File "tests/test_juniper_srx.py", line 7, in <module>
    from DEVICE_CREDS import *
ImportError: No module named DEVICE_CREDS
```

**Comment by supertylerc** [comment]
This was done primarily for #55, but it also resolves #62, which was simple.

**Comment by ktbyers** [comment]
Yes, DEVICE_CREDS.py contains actual device credentials so it is intentionally excluded using .gitignore.

You can create it as such with your IP, user/password

juniper_srx = {
    'device_type': 'juniper',
    'ip':   '10.10.10.10',
    'username': 'user',
    'password': 'password'
}

You can then run py.test as follows:

$ py.test -s -v test_juniper_srx.py 
================================ test session starts ================================
platform linux2 -- Python 2.6.9 -- py-1.4.26 -- pytest-2.6.4 -- /usr/bin/python26

test_juniper_srx.py::test_disable_paging PASSED
test_juniper_srx.py::test_verify_ssh_connect PASSED
test_juniper_srx.py::test_verify_send_command PASSED
test_juniper_srx.py::test_base_prompt PASSED
test_juniper_srx.py::test_strip_prompt PASSED
test_juniper_srx.py::test_strip_command PASSED
test_juniper_srx.py::test_normalize_linefeeds PASSED
test_juniper_srx.py::test_clear_buffer PASSED

**Comment by supertylerc** [comment]
In that case, `check_config_mode()` needs to be removed from `SSHConnection()` and placed in `BaseSSHConnection()`.  It's an extremely generic method that accepts an argument for the correct string to check and can thus be used by any vendor without rewriting the method in every vendor's specific class.

If you really wanted end users to be able to just call `device.check_config_mode()`, then you could override the method and return a `super()` call to the parent class.  I don't think it's too much to ask end users to use the method correctly, though, and call the parent class's `check_config_mode()` properly by specifying the expected string (`device.check_config_mode(check_string="]")`, for example).  That would deduplicate code and remove the need for an overridden method in `JuniperSSH`.  It would also remove it from `HPComwareSSH` and `SSHConnection`, two places where it already exists.

**Comment by supertylerc** [comment]
Let me know what you think.  I can refactor that bit of code pretty quickly and easily and submit a PR.  Then nothing breaks, code duplication is reduced, and it's easily extended to other classes (`JuniperSSH`, for example) when it's needed.

**Comment by supertylerc** [comment]
And having `cli_mode()` doesn't make much sense.  It's only used when someone is in the shell, and a person should only be in the shell if they log in as root (or manually start the shell).  If you have to enter the shell in Junos, you're probably doing it wrong or doing manual troubleshooting.

Although the `cli_mode()` method won't return an error, the text return from Junos will be an error.  See below.

```
╭─tyler at deathstar-vi in ~ using ‹ruby-2.1.1› 15-03-08 - 9:47:16
╰─○ ssh fw1
--- JUNOS 12.1X44-D25.5 built 2013-10-24 20:59:21 UTC
No alarms currently active

{primary:node0}
tyler@fw1.example.com> cli
                       ^
unknown command.

{primary:node0}
tyler@fw1.example.com>
```

**Comment by ktbyers** [comment]
Yes, cli_mode() should be removed.

**Comment by ktbyers** [comment]
Merging and I will modify.

**Comment by ktbyers** [comment]
Okay, I just moved check_config_mode() to BaseSSHConnection. I created a Juniper specific version of this that users super().

**Pull request merged**
