### PR TITLE
Update hp_comware.py and hp_procurve.py to fix bug of output end error in disable paging

### PR DESCRIPTION
**Pull request by jiujing**
In disable paging，it is  ok to just send command. If we add a RETURN in command ，it will  make a muddledness with output，Netmiko receive RETURN's prompt and    think it is ok. Disable paging command's output is still in channel.

### CODE REVIEW

**Comment by ktbyers** [comment]
@jiujing Why does sending the extra `enter` matter? 

I believe there was a reason that I needed to do this and I am not seeing why it would matter (having the extra `enter` in the output)?

**Comment by ktbyers** [comment]
Can you expand or provide more details on why the current code causes you an issue?

**Comment by jiujing** [comment]
> @jiujing Why does sending the extra `enter` matter?
> 
> I believe there was a reason that I needed to do this and I am not seeing why it would matter (having the extra `enter` in the output)?

Let's assume this scenario, we log in to the device and send a command.Netmiko actually sends a carriage return, a command to cancel paging, a command that we actually want to send.The logic to cancel paging recognizes the echo of the first carriage return sent as the end. In fact, there is still an echo in the tunnel where we cancel pagination.
When we send the actual command to be executed, netmiko determines that the end is roughly determined by the pattern of the device name. The device gives us the echo of the corresponding command in the tunnel, but when we read the echo from the tunnel, we mistakenly end with the echo of the cancel paging command.
The real echo is still in the tunnel.
I'm a NetDevOps engineer doing some technical sharing in my spare time, and Netmiko is one of my favorite Python packages. My readers often encounter echo errors when using new versions of netmiko, and after giving them debugs, I locked in presumably because of this, and after modifying the source code, the error disappeared.
In netmiko 3.4.0 ，it use self.clear_buffer() to clear buffer to avoid this error，but it cancel in netmiko 4.
All of the above is machine translation, and I'm not sure if it's clear.

**Comment by spengjie** [comment]
This PR seems related to issue #3012 that I filed in 2022. But this PR may not resolve the issue since there are still some other RETURNs may cause an early prompt response.

**Comment by ktbyers** [comment]
Ended up merging both comware and procurve change (as I couldn't see a reason why the extra enter was really needed).

**Pull request merged**
