### PR TITLE
ZTE Driver Pull Request

### PR DESCRIPTION
**Pull request by ktbyers**

### CODE REVIEW

**Comment by ktbyers** [comment]
@TanY0Y0 I assume the OS here is ZXROS?

**Comment by ktbyers** [comment]
@TanY0Y0 I just split broke out ZTE in your earlier pull-request that had a bunch of different drivers so that it was easier for me to process. I will likely do this for the other drivers as well.

Note, I changed the naming slightly to include the Network OS name in the device_type.

**Comment by ktbyers** [comment]
This should be good to go...assuming that @TanY0Y0 is okay with the new naming.

**Comment by TanY0Y0** [comment]
> @TanY0Y0 I assume the OS here is ZXROS?

sure,it is

**Pull request merged**
