### PR TITLE
watchguard firebox support

### PR DESCRIPTION
**Pull request by dainok**
Added support for Watchguard Firebox. Tested with "show arp" command using a new template pulled to ntc-templates.

### CODE REVIEW

**Comment by ktbyers** [comment]
Linter is failing on CI-CD (see Travis above)

**Comment by dainok** [comment]
Sorry, didn't realize that. Now fixed.

**Comment by dainok** [comment]
Hi @ktbyers, I realize that this PR is still open. Can you merge?

**Comment by ktbyers** [comment]
Let me see if I can review it...looks pretty straightforward on quick glance.

**Comment by ktbyers** [comment]
PR replaced by:

https://github.com/ktbyers/netmiko/pull/1564

**Pull request closed without merging**
